'use client'
// Owner-keyed generations clear old history before replacement effects. Browser
// actions never select an outcome, reviewer roster, amount or settlement decision.
import {useCallback,useEffect,useRef,useState} from 'react'
import AccountPaymentNotices from './AccountPaymentNotices'
import {PaymentGeneration} from '../../lib/payments/card-ui-model'
import {audMoney} from '../../lib/payments/financial-ui-model'
import {exact,internalId} from '../../lib/payments/browser-dto-v1/primitives.mjs'
import {ownerReview,ownerHistory,reviewCommitments,reviewEvidence,reviewStatus,type ReviewCommitment,type ReviewEvidence,type OwnerReview,type HistoryItem} from '../../lib/payments/owner-review-model'
type Original={request_id:string;operation_id:string;action:'appeal'|'dispute'}
type View={owner:string;progress:OwnerReview|null;items:HistoryItem[];original:Original|null;more:boolean;commitments:ReviewCommitment[];commitmentCursor:string|null;evidence:ReviewEvidence[];evidenceCursor:string|null;message:string}
const initial=(owner:string):View=>({owner,progress:null,items:[],original:null,more:false,commitments:[],commitmentCursor:null,evidence:[],evidenceCursor:null,message:'Checking original commitment…'})
const button='rounded-lg bg-[#003a4a] px-4 py-2 text-white disabled:opacity-50'
const historyLabels:Record<string,string>={case:'Review case submitted',financial_outcome:'Original outcome recorded',proof_resolution_binding:'Proof outcome linked',delivered_notice:'Notice delivery recorded',financial_finality:'Financial decision recorded',orchestration_work:'Progress work recorded'}
function correlation(v:unknown):Original|null{if(v===null)return null;if(!exact(v,['request_id','operation_id','action']))throw Error('Unavailable original');const c=v as Original;if(!internalId(c.request_id)||!internalId(c.operation_id)||!['appeal','dispute'].includes(c.action))throw Error('Unavailable original');return c}
// Reuse the bounded history-item validator for the fixed HTTP items projection.
function page(v:unknown):HistoryItem[]{if(!exact(v,['items']))throw Error('Unavailable history');return ownerHistory({commitment_contract_version:1,authority_kind:'financial-history-v1',items:(v as {items:unknown}).items},null)}
export default function AccountPaymentReview({enabled,ownerId,noticesEnabled=false}:{enabled:boolean;ownerId?:string;noticesEnabled?:boolean}){
 const owner=ownerId??'',generation=useRef(new PaymentGeneration()),boundary=useRef({owner,enabled}),busyRef=useRef(false),[busy,setBusy]=useState(false),[state,setState]=useState<View>(initial(owner)),[reason,setReason]=useState(''),[action,setAction]=useState<'appeal'|'dispute'>('appeal'),[selectedAssets,setSelectedAssets]=useState<string[]>([])
 boundary.current={owner,enabled};const view=state.owner===owner?state:initial(owner)
 const request=useCallback(async(path:string,body?:unknown)=>{if(!boundary.current.enabled||boundary.current.owner!==owner)throw Error('Unavailable owner');const r=await fetch('/api/account/payment-review/'+path,{method:body===undefined?'GET':'POST',headers:{'X-Ante-Payment-Owner':owner,...(body===undefined?{}:{'content-type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)}),credentials:'same-origin',cache:'no-store',redirect:'error'});if(!r.ok)throw Error(r.status===429?'Please wait before checking again.':r.status===409?'Check the original request and commitment before continuing.':'Payment review information could not be confirmed.');return await r.json() as unknown},[owner])
 const refresh=useCallback(async()=>{const g=generation.current.next();setState(initial(owner));setSelectedAssets([]);const next=initial(owner);let partial=false;const reads=await Promise.allSettled([request('progress'),request('intent'),request('commitments',{after:null})]);if(!generation.current.current(g))return;try{if(reads[1].status==='fulfilled')next.original=correlation(reads[1].value);else partial=true;if(reads[2].status==='fulfilled'){const listed=reviewCommitments(reads[2].value,null);next.commitments=listed.items;next.commitmentCursor=listed.next_cursor}else partial=true;if(reads[0].status==='fulfilled'){const raw=reads[0].value,nextProgress=ownerReview(raw,(raw as OwnerReview).commitment_id);next.progress=nextProgress;next.items=page(await request('history',{after:null}));next.more=next.items.length===25;const evidence=reviewEvidence(await request('evidence',{after:null}),nextProgress.commitment_id,null);next.evidence=evidence.items;next.evidenceCursor=evidence.next_cursor}}catch{partial=true}if(generation.current.current(g))setState({...next,message:partial?'Some information could not be confirmed. Check the original request before submitting another.':next.progress?'':'Choose a recorded commitment to check its original outcome and history.'})},[owner,request])
 useEffect(()=>{const active=generation.current;busyRef.current=false;setBusy(false);setReason('');setSelectedAssets([]);if(enabled&&owner)void refresh();return()=>{active.next();busyRef.current=false}},[enabled,owner,refresh])
 // One busy lease covers reads and writes. Late results cannot overwrite a newer
 // owner's view; original execute/recover always uses the ACKed server intention.
 async function work(run:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(true);try{await run()}catch(error){setState(old=>old.owner===owner?{...old,message:error instanceof Error?error.message:'Original outcome unknown.'}:old)}finally{if(boundary.current.owner===owner){busyRef.current=false;setBusy(false)}}}
 async function submit(){const g=generation.current.next();const raw=await request('prepare',{request_id:crypto.randomUUID(),action,reason:reason.trim(),asset_ids:selectedAssets}),original=correlation(raw);if(!original||!generation.current.current(g))return;setState(v=>({...v,original,message:'Original request saved. Checking its response…'}));await request('execute',{request_id:original.request_id,operation_id:original.operation_id});if(generation.current.current(g))await refresh()}
 async function recover(execute:boolean){if(!view.original)return;const g=generation.current.next(),original=view.original;const raw=await request(execute?'execute':'recover',execute?{request_id:original.request_id,operation_id:original.operation_id}:{});if(!generation.current.current(g))return;if(!exact(raw,['commitment_contract_version','operation_id','operation_revision','status','result','error_code','retry_after_seconds'])||(raw as {operation_id:string}).operation_id!==original.operation_id)throw Error('Original outcome unknown.');await refresh()}
 async function more(){if(!view.more||!view.items.length)return;const g=generation.current.next(),last=view.items.at(-1)!.identity,items=page(await request('history',{after:last}));if(items.some(i=>i.identity<=last))throw Error('History could not be confirmed.');if(generation.current.current(g))setState(v=>({...v,items:[...v.items,...items],more:items.length===25}))}
 async function select(commitment:string){const g=generation.current.next();await request('select',{commitment_id:commitment});if(generation.current.current(g)){setReason('');setSelectedAssets([]);await refresh()}}
 async function commitmentsPage(){if(!view.commitmentCursor)return;const after=view.commitmentCursor,g=generation.current.next(),listed=reviewCommitments(await request('commitments',{after}),after);if(generation.current.current(g))setState(v=>({...v,commitments:listed.items,commitmentCursor:listed.next_cursor}))}
 async function evidencePage(){if(!view.evidenceCursor||!view.progress)return;const after=view.evidenceCursor,commitment=view.progress.commitment_id,g=generation.current.next(),listed=reviewEvidence(await request('evidence',{after}),commitment,after);if(generation.current.current(g))setState(v=>({...v,evidence:listed.items,evidenceCursor:listed.next_cursor}))}

 if(!enabled||!owner)return <main className="mx-auto max-w-3xl px-6 py-12"><h1 className="text-3xl font-semibold">Payment history and review</h1><p className="mt-4">Payment history and review are currently unavailable.</p></main>
 const p=view.progress,canReport=!!p?.outcome&&!busy,existing=p?.cases.some(c=>c.kind===(action==='appeal'?'appeal':'issuer_dispute'))
 return <main className="mx-auto max-w-3xl space-y-6 px-6 py-12 text-[#003a4a]"><h1 className="text-3xl font-semibold">Payment history and review</h1><p role="status">{view.message}</p><button className={button} disabled={busy} onClick={()=>void work(refresh)}>Check current progress</button>
 <section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Your recorded commitments</h2><p className="mt-2">Choose an earlier commitment. This checks its history without changing the task or payment operation.</p>{view.commitments.length?<ul className="mt-3 space-y-3">{view.commitments.map(c=><li key={c.commitment_id}><p className="break-words">{audMoney(c.amount_minor)} AUD · Task {c.task_id}</p><p className="text-sm">{c.started_at?'Started '+new Date(c.started_at).toLocaleString():'Start not confirmed'}</p><button className={button+' mt-2'} disabled={busy} onClick={()=>void work(()=>select(c.commitment_id))}>View commitment</button></li>)}</ul>:<p className="mt-3">No commitments were confirmed on this page.</p>}{view.commitmentCursor&&<button className={button+' mt-4'} disabled={busy} onClick={()=>void work(commitmentsPage)}>Next commitment page</button>}</section>
 {p&&<section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Original task commitment</h2><p className="mt-3">{audMoney(p.amount_minor)} AUD · Revision {p.revision}</p><p>{p.started_at?'Started amount is fixed.':'Task start has not been confirmed.'}</p><p className="mt-3">{reviewStatus(p)}</p><p>Funding: {p.funding_state?.replaceAll('_',' ')??'unknown'}</p>{p.started_at&&<a className="mt-3 inline-block underline" href={'/account/financial-tasks/collection/'+p.commitment_id+'/'+p.revision}>Check original task payment progress</a>}{p.cases.map(c=><p key={c.case_id}>{c.kind==='appeal'?'Appeal':'Dispute report'}: {c.state.replaceAll('_',' ')}</p>)}<p className="mt-3 text-sm">Appeals return to the original reviewers. Reviewer silence escalates for review without automatic collection. A dispute report does not confirm an issuer dispute or refund.</p></section>}
 {view.original&&<section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Original {view.original.action==='appeal'?'appeal':'dispute report'}</h2><p>Check the original response before submitting another request.</p><div className="mt-3 flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>void work(()=>recover(false))}>Check original response</button><button className={button} disabled={busy} onClick={()=>void work(()=>recover(true))}>Resume original request</button></div></section>}
 {p&&<section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Ask for review</h2><p className="mt-2">Your reason is attached to the original outcome and commitment. Existing evidence remains with the original reviewers.</p><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();void work(submit)}}><label className="block">Request<select className="ml-3 rounded border p-2" value={action} disabled={busy} onChange={e=>setAction(e.target.value as 'appeal'|'dispute')}><option value="appeal">Appeal task outcome</option><option value="dispute">Report payment dispute</option></select></label><label className="block">Reason<textarea className="mt-2 block w-full rounded border p-3" rows={4} maxLength={1200} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><fieldset className="space-y-2"><legend>Attach existing proof evidence (up to five)</legend>{view.evidence.map(asset=><label className="block break-words" key={asset.asset_id}><input type="checkbox" checked={selectedAssets.includes(asset.asset_id)} disabled={busy||!selectedAssets.includes(asset.asset_id)&&selectedAssets.length>=5} onChange={e=>setSelectedAssets(previous=>e.target.checked?[...previous,asset.asset_id]:previous.filter(id=>id!==asset.asset_id))}/> Proof {asset.asset_id} · {new Date(asset.created_at).toLocaleString()}</label>)}{!view.evidence.length&&<p>No existing proof evidence was confirmed on this page.</p>}{view.evidenceCursor&&<button type="button" className={button} disabled={busy} onClick={()=>void work(evidencePage)}>Next evidence page</button>}<p className="text-sm">Only previously recorded proof assets for this original task can be attached. This form does not upload new evidence.</p></fieldset><button className={button} disabled={!canReport||existing||!reason.trim()||new TextEncoder().encode(reason.trim()).length>1200||action==='appeal'&&!!p.finality}>Submit review request</button><p className="text-sm">Availability and deadlines are checked by the original server rules. Approved consent and policy configuration are required.</p></form></section>}
 <section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Recorded history</h2>{view.items.length?<ol className="mt-3 space-y-3">{view.items.map(i=><li key={i.identity}><p>{historyLabels[i.kind]}</p><time className="text-sm" dateTime={i.occurred_at}>{new Date(i.occurred_at).toLocaleString()}</time></li>)}</ol>:<p className="mt-3">{p?'No recorded entries in this page.':'History could not be confirmed.'}</p>}{view.more&&<button className={button+' mt-4'} disabled={busy} onClick={()=>void work(more)}>Load more recorded entries</button>}<p className="mt-4 text-sm">Entries are immutable records. A notice delivery record does not confirm financial settlement.</p></section><AccountPaymentNotices key={owner} ownerId={owner} enabled={noticesEnabled}/></main>
}
