// Separate read-only browser admission: a later long-task failure is not the
// thirty-minute Task10 admission. This AEAD stores no provider object/secret and
// cannot authorize an effect. SQL binds its immutable root to one collection.
import 'server-only'
import {createCipheriv,createDecipheriv,randomBytes,randomUUID,createHash} from 'node:crypto'
import {exact,internalId} from '../payments/collection-v4/scripts/backend/web-payment-provider-contract.mjs'
import type {NextResponse} from 'next/server'
export type CollectionAdmission={ownerId:string;commitmentId:string;commitmentRevision:number;returnAdmissionId:string;nonce:string;expiresAt:number}
export const collectionAdmissionCookie='__Host-ante-long-collection-read',collectionCapsuleCookie='__Host-ante-long-collection-return'
const aad=Buffer.from('ante-long-collection-browser-read-v1'),options={httpOnly:true,secure:true,sameSite:'strict' as const,path:'/'}
function valid(v:CollectionAdmission,owner:string){return exact(v,['ownerId','commitmentId','commitmentRevision','returnAdmissionId','nonce','expiresAt'])&&v.ownerId===owner&&[v.ownerId,v.commitmentId,v.returnAdmissionId].every(internalId)&&Number.isInteger(v.commitmentRevision)&&v.commitmentRevision>0&&v.commitmentRevision<=2147483647&&/^[A-Za-z0-9_-]{43}$/.test(v.nonce)&&Number.isSafeInteger(v.expiresAt)&&v.expiresAt>Date.now()&&v.expiresAt<=Date.now()+1800000}
export function newCollectionAdmission(ownerId:string,commitmentId:string,commitmentRevision:number):CollectionAdmission{return {ownerId,commitmentId,commitmentRevision,returnAdmissionId:randomUUID(),nonce:randomBytes(32).toString('base64url'),expiresAt:Date.now()+1800000}}
export function encodeCollectionAdmission(v:CollectionAdmission,key:Buffer){if(key.length!==32||!valid(v,v.ownerId))throw new Error('browser_lineage_required');const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(aad);const body=Buffer.concat([cipher.update(JSON.stringify(v)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url')}
export function decodeCollectionAdmission(token:string|null,key:Buffer,owner:string):CollectionAdmission|null{if(!token)return null;try{if(key.length!==32||token.length>2048||!/^[A-Za-z0-9_-]+$/.test(token))throw new Error();const bytes=Buffer.from(token,'base64url');if(bytes.length<29||bytes.toString('base64url')!==token)throw new Error();const decipher=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));decipher.setAAD(aad);decipher.setAuthTag(bytes.subarray(12,28));const value=JSON.parse(Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString('utf8'));if(!valid(value,owner))throw new Error();return value}catch{throw new Error('browser_lineage_required')}}
export function collectionBrowserDigest(v:CollectionAdmission){return createHash('sha256').update('ante-long-collection-browser-read-v1:'+v.ownerId+':'+v.nonce).digest('hex')}
export function installCollectionAdmission(response:NextResponse,v:CollectionAdmission,key:Buffer){response.cookies.set(collectionAdmissionCookie,encodeCollectionAdmission(v,key),{...options,expires:new Date(v.expiresAt)})}
export function installCollectionCapsule(response:NextResponse,token:string,expiry:string){if(!/^alc1\.[A-Za-z0-9_-]{43}\.[A-Za-z0-9_-]{43}$/.test(token)||!/^[1-9][0-9]{0,18}$/.test(expiry))throw new Error('browser_lineage_required');const ms=Number(BigInt(expiry)/1000n);if(!Number.isSafeInteger(ms)||ms<=Date.now()||ms>Date.now()+300000)throw new Error('browser_lineage_required');response.cookies.set(collectionCapsuleCookie,token,{...options,expires:new Date(ms)})}
