// Actual Next route/cookie execution is exercised with fixed owner SQL doubles.
// IDs are server allocated; no Auth, provider or hosted network is called.
import { beforeEach, expect, it, vi } from 'vitest'
import { NextRequest, NextResponse } from 'next/server'
vi.mock('server-only',()=>({}))
const gate=vi.hoisted(()=>({admit:vi.fn(async()=>null),identity:vi.fn()}))
vi.mock('../lib/supabase/config',()=>({accountConfig:()=>({siteOrigin:'https://antedotal.com'})}))
vi.mock('../lib/server/callback-admission',()=>({admitAccountVisitor:gate.admit}))
vi.mock('../lib/server/profile-photo-session',()=>({verifyProfilePhotoSession:gate.identity}))
import { createAccountFinancialHandler } from '../lib/server/account-financial'
import { decodeFinancialFamily } from '../lib/server/financial-cookies'
import type { FinancialWebsiteBindings } from '../lib/server/financial-bridge'
const uuid=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,ownerId=uuid(1),requestId=uuid(2),key=Buffer.alloc(32,2)
const selection={configuration_id:uuid(3),configuration_revision:1,card_id:uuid(4),card_revision:1,consent_id:uuid(5),consent_revision:1,settings_hash:'a'.repeat(64),eligibility_revision:1},context={policies:[],task:{selections:[{funding_mode:'short_authorization',cutoff_seconds:172800,processing_buffer_seconds:3600,selection}],lists:[{list_id:'tasks',label:'Tasks'}],verifiers:[{verifier_id:uuid(6),label:'Friend'}],available:true},premium:{plans:[],available:false}},draft={title:'Original task',details:null,due_date:'2030-01-01T00:00:00.000Z',difficulty_preset:'easy',list_id:'tasks',verifier_ids:[uuid(6)],funding_mode:'short_authorization'}
let originals:Record<string,unknown>,task:ReturnType<typeof vi.fn>,premium:ReturnType<typeof vi.fn>,contextRead:ReturnType<typeof vi.fn>,bindings:FinancialWebsiteBindings
function request(purpose:'task'|'premium',path:string,input?:unknown,cookie?:string,expectedOwner=ownerId){return new NextRequest(`https://antedotal.com/api/account/financial/${purpose}/${path}`,{method:input===undefined?'GET':'POST',headers:{host:'antedotal.com',origin:'https://antedotal.com','X-Ante-Payment-Owner':expectedOwner,...(input===undefined?{}:{'content-type':'application/json'}),...(cookie?{cookie}:{})},...(input===undefined?{}:{body:JSON.stringify(input)})})}
function cookie(response:Response){return response.headers.get('set-cookie')!.split(';')[0]}
function envelope(operationId:string|null,result:unknown,status='completed',error:null|string=null){return {financial_task_contract_version:1,operation_id:operationId,operation_revision:operationId?1:null,resource_revision:result&&typeof result==='object'&&'task_revision'in result?(result as {task_revision:number}).task_revision:null,status,result,error_code:error,retry_after_seconds:null}}
beforeEach(()=>{originals={};contextRead=vi.fn(async()=>structuredClone(context));task=vi.fn(async(action:string,input:Record<string,unknown>)=>{if(action==='quote'){const result={quote_id:uuid(7),quote_hash:'b'.repeat(64),task_id:input.task_id,task_revision:1,amount_minor:'1000',currency:'AUD',expires_at:'2030-01-01T00:00:00.000Z',eligibility_revision:1,snapshot_hash:'c'.repeat(64)},r=envelope(String(input.operation_id),result);originals[String(input.operation_id)]=r;return r}if(action==='recover')return originals[String(input.operation_id)]??envelope(null,null,'denied','not_found');return envelope(null,null,'denied','not_found')});premium=vi.fn();gate.identity.mockResolvedValue({kind:'verified',session:{ownerId,token:'a.b.c',provisional:new NextResponse(null)}});gate.admit.mockClear();bindings={enabled:true,cookieKeys:{task:key,premium:key},services:{owner:async()=>({ownerId,fresh:async()=>{},context:contextRead,task,premium})},publishableKey:'pk_test_fixture'} as unknown as FinancialWebsiteBindings})
it('closed financial page routes perform no admission or Auth',async()=>{const r=await createAccountFinancialHandler(()=>null)(request('task','intent'),'task','intent');expect(r.status).toBe(503);expect(gate.admit).not.toHaveBeenCalled();expect(gate.identity).not.toHaveBeenCalled()})
it('client money/configuration/operation injection and missing affirmative deny before admission',async()=>{for(const [action,input]of [['task.quote',{...draft,amount_minor:'1'}],['task.admit',{affirmative:false}],['task.quote',{...draft,configuration_id:uuid(8)}]] as const){const r=await createAccountFinancialHandler(()=>bindings)(request('task','prepare',{request_id:requestId,action,input}),'task','prepare');expect(r.status).toBe(400)}expect(gate.admit).not.toHaveBeenCalled()})
it('prepare lost ACK/restored reload retain original frozen selection without new context',async()=>{const run=createAccountFinancialHandler(()=>bindings),body={request_id:requestId,action:'task.quote',input:draft},first=await run(request('task','prepare',body),'task','prepare'),original=await first.json(),stored=cookie(first),second=await run(request('task','prepare',body,stored),'task','prepare');expect(await second.json()).toEqual(original);expect(contextRead).toHaveBeenCalledOnce();const restored=await run(request('task','intent',undefined,stored),'task','intent');expect(await restored.json()).toEqual({primary:original,secondary:null});expect(JSON.stringify(original)).not.toMatch(/nonce|admission|secret|configuration/)})
it('a prepare-only original with no SQL row blocks replacement and resumes under exact cookie ID',async()=>{const run=createAccountFinancialHandler(()=>bindings),first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare'),original=await first.json(),stored=cookie(first),replace=await run(request('task','prepare',{request_id:uuid(9),action:'task.quote',input:draft},stored),'task','prepare');expect(replace.status).toBe(409);const executed=await run(request('task','execute',{request_id:requestId,expected_operation_id:original.operation_id},stored),'task','execute');expect(executed.status).toBe(200);expect(task).toHaveBeenLastCalledWith('quote',expect.objectContaining({...selection,operation_id:original.operation_id}));expect(task.mock.calls.at(-1)![1]).not.toHaveProperty('funding_mode')})
it('forged execute IDs and changed owner never call SQL mutation',async()=>{const run=createAccountFinancialHandler(()=>bindings),first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare'),stored=cookie(first),forged=await run(request('task','execute',{request_id:requestId,expected_operation_id:uuid(77)},stored),'task','execute');expect(forged.status).toBe(409);const changed=await run(request('task','intent',undefined,stored,uuid(88)),'task','intent');expect(changed.status).toBe(409);expect(task).not.toHaveBeenCalled()})
it('task admission freezes the actual original quote and same nonce/expiry lineage',async()=>{const run=createAccountFinancialHandler(()=>bindings),first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare'),ack=await first.json(),stored=cookie(first);await run(request('task','execute',{request_id:requestId,expected_operation_id:ack.operation_id},stored),'task','execute');const admitted=await run(request('task','prepare',{request_id:uuid(9),action:'task.admit',input:{affirmative:true,quote_id:uuid(7),quote_hash:'b'.repeat(64),task_revision:1}},stored),'task','prepare');expect(admitted.status).toBe(200);const before=decodeFinancialFamily(stored.split('=')[1],key,'task',ownerId)!,after=decodeFinancialFamily(cookie(admitted).split('=')[1],key,'task',ownerId)!;expect(after.primary).toEqual(before.primary);expect(after.secondary?.expiresAt).toBe(before.primary.expiresAt);expect(after.secondary?.input).toEqual({quote_id:uuid(7),quote_hash:'b'.repeat(64),task_revision:1,eligibility_revision:1,affirmative:true})})
it('settings rate receipt maps429 and original retry header',async()=>{task.mockResolvedValue({...envelope(null,null,'denied','rate_limited'),retry_after_seconds:23});const r=await createAccountFinancialHandler(()=>bindings)(request('task','settings'),'task','settings');expect(r.status).toBe(429);expect(r.headers.get('retry-after')).toBe('23')})
// Original task review is a safe projection of the ACKed cookie input, never a
// browser-selected SQL operation or replacement of the immutable quote receipt.
it('reload review preserves original task details and excludes commercial/secret lineage',async()=>{const run=createAccountFinancialHandler(()=>bindings),first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare'),stored=cookie(first),review=await run(request('task','review',undefined,stored),'task','review');expect(review.status).toBe(200);expect(await review.json()).toEqual({...draft,task_id:decodeFinancialFamily(stored.split('=')[1],key,'task',ownerId)!.primary.input.task_id});expect(review.headers.get('cache-control')).toContain('no-store')})
it('fixed Premium page cursor selects only bounded owned list read without any cookie or mutation',async()=>{const cursor='d'.repeat(32);premium.mockResolvedValue({subscription_contract_version:1,operation_id:null,operation_revision:null,resource_revision:null,status:'completed',result:{subscriptions:[],next_cursor:null},error_code:null,retry_after_seconds:null});const r=await createAccountFinancialHandler(()=>bindings)(request('premium','subscriptions',{cursor}),'premium','subscriptions');expect(r.status).toBe(200);expect(premium).toHaveBeenCalledWith('subscription.list',{limit:50,cursor});const bad=await createAccountFinancialHandler(()=>bindings)(request('premium','subscriptions',{cursor:'arbitrary',operation_id:uuid(77)}),'premium','subscriptions');expect(bad.status).toBe(400)})
it('rate limited context uses429 with policies independently present',async()=>{contextRead.mockResolvedValue({...context,error_code:'rate_limited',retry_after_seconds:19});const r=await createAccountFinancialHandler(()=>bindings)(request('task','context'),'task','context');expect(r.status).toBe(429);expect(r.headers.get('Retry-After')).toBe('19')})
it('rate limited fixed context during new preparation maps original429 before allocating a family',async()=>{contextRead.mockResolvedValue({...context,error_code:'rate_limited',retry_after_seconds:19});const r=await createAccountFinancialHandler(()=>bindings)(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare');expect(r.status).toBe(429);expect(r.headers.get('Retry-After')).toBe('19');expect(r.headers.get('Set-Cookie')).toBeNull()})
it('saved default amounts use fixed original owner setter without rewriting the prepared quote lineage',async()=>{const write=vi.fn(async()=>({ok:true,presets:{currency:'AUD',easy_cents:1500,medium_cents:2500,hard_cents:3500,updated_at:'2026-10-08T00:00:00.000Z'}}));const originalOwner=bindings.services.owner;bindings.services={...bindings.services,owner:async(...args:Parameters<typeof originalOwner>)=>({...await originalOwner(...args),settingsWrite:write})};const run=createAccountFinancialHandler(()=>bindings),first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare'),stored=cookie(first),before=decodeFinancialFamily(stored.split('=')[1],key,'task',ownerId),saved=await run(request('task','defaults',{easy_cents:1500,medium_cents:2500,hard_cents:3500},stored),'task','defaults');expect(saved.status).toBe(200);expect(write).toHaveBeenCalledWith({easy_cents:1500,medium_cents:2500,hard_cents:3500});expect(saved.headers.get('Set-Cookie')).toBeNull();expect(decodeFinancialFamily(stored.split('=')[1],key,'task',ownerId)).toEqual(before)})
function premiumEnvelope(result:unknown,operation:string|null=null,status='completed',error:string|null=null){return {subscription_contract_version:1,operation_id:operation,operation_revision:operation?1:null,resource_revision:result&&typeof result==='object'&&'revision'in result?(result as {revision:number}).revision:null,status,result,error_code:error,retry_after_seconds:null}}
const originalSubscription={subscription_id:uuid(50),revision:3,plan_key:'monthly',state:'active',paid_through:'2030-01-01T00:00:00.000Z',cancel_at_period_end:false,checkout_url:null},originalEntitlement={revision:2,tier:'premium',provider_verified:true,effective_until:'2030-01-01T00:00:00.000Z',cap_configuration_id:uuid(55),cap_configuration_revision:1}
function ownedPremium(){premium.mockImplementation(async(action:string,input:Record<string,unknown>)=>action==='subscription.read'?premiumEnvelope(originalSubscription):action==='entitlement.read'?premiumEnvelope(originalEntitlement):action==='subscription.recover'?premiumEnvelope(null,null,'denied','not_found'):premiumEnvelope(originalSubscription,String(input.operation_id),'pending'))}
it('historical cancel prepares and resumes its own original without an available plan or purchase cookie',async()=>{ownedPremium();const run=createAccountFinancialHandler(()=>bindings),body={request_id:requestId,action:'premium.cancel',input:{subscription_id:originalSubscription.subscription_id}},first=await run(request('premium','prepare',body),'premium','prepare');expect(first.status).toBe(200);const ack=await first.json(),stored=cookie(first),retry=await run(request('premium','prepare',body,stored),'premium','prepare');expect(await retry.json()).toEqual(ack);const restored=await run(request('premium','intent',undefined,stored),'premium','intent');expect(await restored.json()).toEqual({primary:ack,secondary:null});const execute=await run(request('premium','execute',{request_id:requestId,expected_operation_id:ack.operation_id},stored),'premium','execute');expect(execute.status).toBe(200);expect(premium).toHaveBeenLastCalledWith('subscription.manage',{operation_id:ack.operation_id,subscription_id:originalSubscription.subscription_id,subscription_revision:3,entitlement_revision:2,action:'cancel_at_period_end'});expect(contextRead).not.toHaveBeenCalled()})
it('pending original purchase retains one bounded cancel child after lost ACK and denies conflicting child prepares',async()=>{ownedPremium();const plan={plan_key:'monthly',amount_minor:'1000',currency:'AUD',selection:{customer_revision:2,entitlement_revision:2,configuration_id:uuid(3),configuration_revision:1,consent_id:uuid(5),consent_revision:1}};contextRead.mockResolvedValue({...context,premium:{available:true,plans:[plan]}});const run=createAccountFinancialHandler(()=>bindings),purchase=await run(request('premium','prepare',{request_id:requestId,action:'premium.checkout',input:{plan_key:'monthly'}}),'premium','prepare'),original=cookie(purchase),before=decodeFinancialFamily(original.split('=')[1],key,'premium',ownerId)!,body={request_id:uuid(60),action:'premium.cancel',input:{subscription_id:originalSubscription.subscription_id}},cancel=await run(request('premium','prepare',body,original),'premium','prepare');expect(cancel.status).toBe(200);const ack=await cancel.json(),withChild=cookie(cancel),after=decodeFinancialFamily(withChild.split('=')[1],key,'premium',ownerId)!;expect(after.primary).toEqual(before.primary);expect(after.secondary?.expiresAt).toBe(before.primary.expiresAt);const retry=await run(request('premium','prepare',body,withChild),'premium','prepare');expect(await retry.json()).toEqual(ack);const conflict=await run(request('premium','prepare',{...body,request_id:uuid(61)},withChild),'premium','prepare');expect(conflict.status).toBe(409);expect(conflict.headers.get('Set-Cookie')).toBeNull();expect(after.secondary?.input).toMatchObject({subscription_revision:3,entitlement_revision:2})})
it('the maximum accepted task draft still leaves bounded cookie room for original admission',async()=>{const run=createAccountFinancialHandler(()=>bindings),maximum={...draft,title:'T'.repeat(256),details:'D'.repeat(600),list_id:'L'.repeat(128),verifier_ids:[uuid(6),uuid(65),uuid(66),uuid(67),uuid(68)]};contextRead.mockResolvedValue({...context,task:{...context.task,lists:[{list_id:maximum.list_id,label:'Tasks'}],verifiers:maximum.verifier_ids.map(verifier_id=>({verifier_id,label:'Friend'}))}});const first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:maximum}),'task','prepare');expect(first.status).toBe(200);const ack=await first.json(),stored=cookie(first);await run(request('task','execute',{request_id:requestId,expected_operation_id:ack.operation_id},stored),'task','execute');const admitted=await run(request('task','prepare',{request_id:uuid(9),action:'task.admit',input:{affirmative:true,quote_id:uuid(7),quote_hash:'b'.repeat(64),task_revision:1}},stored),'task','prepare');expect(admitted.status).toBe(200);expect(cookie(admitted).split('=')[1].length).toBeLessThanOrEqual(4096)})

it('oversized original details fail before ACK instead of stranding an admission child',async()=>{const run=createAccountFinancialHandler(()=>bindings),oversized={...draft,title:'T'.repeat(256),details:'D'.repeat(1200),list_id:'L'.repeat(128),verifier_ids:[uuid(6),uuid(65),uuid(66),uuid(67),uuid(68)]};contextRead.mockResolvedValue({...context,task:{...context.task,lists:[{list_id:oversized.list_id,label:'Tasks'}],verifiers:oversized.verifier_ids.map(verifier_id=>({verifier_id,label:'Friend'}))}});const r=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:oversized}),'task','prepare');expect(r.status).toBe(400);expect(r.headers.get('Set-Cookie')).toBeNull();expect(task).not.toHaveBeenCalled()})

// Future nonpaid DTO fixtures exercise the real closed route's ordinary parsing
// and original revision selection, not a provider/SQL acceptance or activation.
it.each(['past_due','unpaid','paused','canceled','cancel_scheduled'])('current %s owner billing projection preserves the independent paid interval without mutation',async state=>{const sub={...originalSubscription,state,cancel_at_period_end:state==='cancel_scheduled'};premium.mockImplementation(async(action:string)=>action==='subscription.list'?premiumEnvelope({subscriptions:[sub],next_cursor:null}):premiumEnvelope(originalEntitlement));const r=await createAccountFinancialHandler(()=>bindings)(request('premium','current'),'premium','current');expect(r.status).toBe(200);const value=await r.json();expect(value.subscriptions.result.subscriptions).toEqual([sub]);expect(value.entitlement.result).toEqual(originalEntitlement);expect(premium.mock.calls.map(([action])=>action)).toEqual(['subscription.list','entitlement.read']);expect(r.headers.get('Set-Cookie')).toBeNull()})
it.each(['unpaid','paused'])('source fixture %s cancellation retains actual current billing/entitlement revisions in original intention',async state=>{const sub={...originalSubscription,state,revision:7};premium.mockImplementation(async(action:string,input:Record<string,unknown>)=>action==='subscription.read'?premiumEnvelope(sub):action==='entitlement.read'?premiumEnvelope(originalEntitlement):premiumEnvelope(sub,String(input.operation_id),'pending'));const run=createAccountFinancialHandler(()=>bindings),first=await run(request('premium','prepare',{request_id:requestId,action:'premium.cancel',input:{subscription_id:sub.subscription_id}}),'premium','prepare');expect(first.status).toBe(200);const ack=await first.json(),stored=cookie(first);expect(decodeFinancialFamily(stored.split('=')[1],key,'premium',ownerId)?.primary.input).toEqual({subscription_id:sub.subscription_id,subscription_revision:7,entitlement_revision:2,action:'cancel_at_period_end'});expect(contextRead).not.toHaveBeenCalled();const r=await run(request('premium','execute',{request_id:requestId,expected_operation_id:ack.operation_id},stored),'premium','execute');expect(r.status).toBe(200);expect(premium).toHaveBeenLastCalledWith('subscription.manage',{subscription_id:sub.subscription_id,subscription_revision:7,entitlement_revision:2,action:'cancel_at_period_end',operation_id:ack.operation_id})})

// Exercise actual shared signed-cookie substitution: tab A keeps its displayed
// quote while tab B has replaced the cookie with a different original quote.
async function substitutedQuoteFamily(){const run=createAccountFinancialHandler(()=>bindings),first=await run(request('task','prepare',{request_id:requestId,action:'task.quote',input:draft}),'task','prepare'),a=await first.json(),cookieA=cookie(first);await run(request('task','execute',{request_id:requestId,expected_operation_id:a.operation_id},cookieA),'task','execute');const displayed=(originals[a.operation_id] as {result:Record<string,unknown>}).result,second=await run(request('task','prepare',{request_id:uuid(80),action:'task.quote',input:{...draft,title:'Other tab task'}},cookieA),'task','prepare'),b=await second.json(),cookieB=cookie(second);await run(request('task','execute',{request_id:uuid(80),expected_operation_id:b.operation_id},cookieB),'task','execute');const current=originals[b.operation_id] as {result:Record<string,unknown>;resource_revision:number};current.result={...current.result,quote_id:uuid(81),quote_hash:'d'.repeat(64),task_revision:2,amount_minor:'3000'};current.resource_revision=2;task.mockClear();return {run,cookieB,displayed}}
it('shared quote-cookie replacement cannot borrow an identity-free affirmation from the other view',async()=>{const {run,cookieB}=await substitutedQuoteFamily(),r=await run(request('task','prepare',{request_id:uuid(82),action:'task.admit',input:{affirmative:true}},cookieB),'task','prepare');expect(r.status).toBe(400);expect(r.headers.get('Set-Cookie')).toBeNull();expect(task.mock.calls.every(([action])=>action==='recover')).toBe(true)})
it('the displayed quote cannot select the replacement shared cookie quote for admission',async()=>{const {run,cookieB,displayed}=await substitutedQuoteFamily(),r=await run(request('task','prepare',{request_id:uuid(82),action:'task.admit',input:{affirmative:true,quote_id:displayed.quote_id,quote_hash:displayed.quote_hash,task_revision:displayed.task_revision}},cookieB),'task','prepare');expect(r.status).toBe(409);expect(r.headers.get('Set-Cookie')).toBeNull();expect(task.mock.calls).toEqual([['recover',expect.any(Object)]]);expect(contextRead).toHaveBeenCalledTimes(2)})

// Each selected identity part binds independently; a current original must not
// turn an altered selection into a fresh child or financial mutation.
it.each(['quote_id','quote_hash','task_revision'])('a mismatched displayed %s refuses before admission allocation',async field=>{const {run,cookieB,displayed}=await substitutedQuoteFamily(),selection:Record<string,unknown>={affirmative:true,quote_id:uuid(81),quote_hash:'d'.repeat(64),task_revision:2};selection[field]=displayed[field];const r=await run(request('task','prepare',{request_id:uuid(83),action:'task.admit',input:selection},cookieB),'task','prepare');expect(r.status).toBe(409);expect(r.headers.get('Set-Cookie')).toBeNull();expect(task.mock.calls.map(([action])=>action)).toEqual(['recover'])})
it('matching original quote selection retains original financial fields and exact lost-ACK replay',async()=>{const {run,cookieB}=await substitutedQuoteFamily(),selected={affirmative:true,quote_id:uuid(81),quote_hash:'d'.repeat(64),task_revision:2},body={request_id:uuid(84),action:'task.admit',input:selected},first=await run(request('task','prepare',body,cookieB),'task','prepare');expect(first.status).toBe(200);const ack=await first.json(),stored=cookie(first),before=decodeFinancialFamily(cookieB.split('=')[1],key,'task',ownerId)!,after=decodeFinancialFamily(stored.split('=')[1],key,'task',ownerId)!;expect(after.primary).toEqual(before.primary);expect(after.secondary?.input).toEqual({...selected,eligibility_revision:1});task.mockClear();contextRead.mockClear();const retry=await run(request('task','prepare',body,stored),'task','prepare');expect(await retry.json()).toEqual(ack);expect(task).not.toHaveBeenCalled();expect(contextRead).not.toHaveBeenCalled();const changed=await run(request('task','prepare',{...body,input:{...selected,quote_hash:'e'.repeat(64)}},stored),'task','prepare');expect(changed.status).toBe(409);expect(changed.headers.get('Set-Cookie')).toBeNull();expect(task).not.toHaveBeenCalled();await run(request('task','execute',{request_id:body.request_id,expected_operation_id:ack.operation_id},stored),'task','execute');expect(task).toHaveBeenCalledOnce();expect(task).toHaveBeenCalledWith('admit',{...after.secondary!.input,operation_id:ack.operation_id});expect(task.mock.calls[0][1]).not.toHaveProperty('amount_minor')})
it.each([{quote_id:'arbitrary'},{quote_id:uuid(7).toUpperCase()+'X'},{quote_hash:'g'.repeat(64)},{quote_hash:'b'.repeat(63)},{task_revision:0},{task_revision:2147483648},{task_revision:1.5},{amount_minor:'1'},{eligibility_revision:7}])('malformed or authority-bearing admission selection denies before owner admission: %j',async extra=>{const admissions=gate.admit.mock.calls.length,identities=gate.identity.mock.calls.length,r=await createAccountFinancialHandler(()=>bindings)(request('task','prepare',{request_id:uuid(85),action:'task.admit',input:{affirmative:true,quote_id:uuid(7),quote_hash:'b'.repeat(64),task_revision:1,...extra}}),'task','prepare');expect(r.status).toBe(400);expect(r.headers.get('Set-Cookie')).toBeNull();expect(gate.admit.mock.calls).toHaveLength(admissions);expect(gate.identity.mock.calls).toHaveLength(identities);expect(task).not.toHaveBeenCalled()})
