// Exercise actual private route orchestration and the pinned B1 transport;
// only visitor, SSR identity and external Auth/RPC networks are doubled.
import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest,NextResponse} from 'next/server'
vi.mock('server-only',()=>({}))
const state=vi.hoisted(()=>({identity:vi.fn(),admit:vi.fn(),rpc:vi.fn()}))
vi.mock('../lib/server/profile-photo-session',()=>({verifyProfilePhotoSession:state.identity}))
vi.mock('../lib/server/callback-admission',()=>({admitAccountVisitor:state.admit}))
import {createAccountCardPaymentHandler} from '../lib/server/account-card-payments'
import {composePaymentWebsite,configuredPaymentWebsite} from '../lib/server/payment-bridge'
import {createPaymentSupabase} from '../lib/payments/bridge-v1/supabase/functions/_shared/webPaymentOwnerSupabase'
import {guardedTransport,type Provisioning} from '../lib/payments/bridge-v1/supabase/functions/_shared/webPaymentProviderClient'
import {decodePaymentIntent,PAYMENT_INTENT_COOKIE,PAYMENT_RETURN_COOKIE,paymentBrowserDigest} from '../lib/server/payment-cookies'
const owner='11111111-1111-4111-8111-111111111111',customer='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333',key=Buffer.alloc(32,7)
const request=(path:string,method='POST',body:unknown={},cookie?:string)=>new NextRequest('https://ante.test/api/account/payments/browser/'+path,{method,headers:{host:'ante.test',...(method==='GET'?{}:{origin:'https://ante.test','content-type':'application/json'}),...(cookie?{cookie}:{})},...(method==='GET'?{}:{body:typeof body==='string'?body:JSON.stringify(body)})})
function bound(){const services=createPaymentSupabase({projectUrl:'https://example.supabase.co',publicKey:'sb_publishable_'+'a'.repeat(20),enabled:true,transportAccepted:true,acceptedB0AuthoritySha256:'6799e95ac25d0fa3c2a6a2f89dd0113d25f2bdcc3cb06c1b4a766c551b978f89',gatewayCredential:'g'.repeat(43),fetcher:async(url,init)=>String(url).includes('/auth/')?Response.json({id:owner}):state.rpc(String(url),JSON.parse(String(init?.body)))});return composePaymentWebsite({services,provider:{provision:{} as Provisioning,credential:()=>{throw new Error('unexpected SDK')},transport:guardedTransport(()=>{throw new Error('unexpected SDK')})},loadReturnKey:async()=>null},key,'pk_test_'+ 'a'.repeat(20))}
const cookie=(response:NextResponse)=>response.cookies.get(PAYMENT_INTENT_COOKIE)!.value
beforeEach(()=>{process.env.NEXT_PUBLIC_SUPABASE_URL='https://yxilmwxptfnebnjsikwo.supabase.co';process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='sb_publishable_testvalue';process.env.NEXT_PUBLIC_ANTE_SITE_ORIGIN='https://ante.test';delete process.env.ANTE_WEB_PAYMENTS_MODE;state.admit.mockReset().mockResolvedValue(null);state.identity.mockReset().mockResolvedValue({kind:'verified',session:{ownerId:owner,token:'owner.real.signature',provisional:new NextResponse(null)}});state.rpc.mockReset()})
it('closed source bindings perform no visitor/Auth/RPC work',async()=>{delete process.env.NEXT_PUBLIC_SUPABASE_URL;const response=await createAccountCardPaymentHandler() (request('execute'),'execute');expect(response.status).toBe(503);expect(configuredPaymentWebsite()).toBeNull();expect(state.admit).not.toHaveBeenCalled();expect(state.identity).not.toHaveBeenCalled();expect(state.rpc).not.toHaveBeenCalled()})
it('unsafe origin, mutation query and duplicate JSON refuse before admission/Auth',async()=>{const handler=createAccountCardPaymentHandler(bound);for(const input of [request('execute?client_secret=untrusted'),request('prepare','POST','{"action":"customer.ensure","action":"card.remove","input":{},"request_id":"'+requestId+'"}'),new NextRequest('https://evil.test/api/account/payments/browser/execute',{method:'POST',headers:{host:'evil.test',origin:'https://evil.test','content-type':'application/json'},body:'{}'})])expect((await handler(input,input.nextUrl.pathname.endsWith('prepare')?'prepare':'execute')).status).toBeGreaterThanOrEqual(400);expect(state.admit).not.toHaveBeenCalled();expect(state.identity).not.toHaveBeenCalled()})
it('prepare retry preserves original server operation/admission/nonce/expiry without RPC',async()=>{const handler=createAccountCardPaymentHandler(bound),body={request_id:requestId,action:'customer.ensure',input:{customer_revision:0}},first=await handler(request('prepare','POST',body),'prepare'),original=decodePaymentIntent(cookie(first),key,owner)!,again=await handler(request('prepare','POST',body,PAYMENT_INTENT_COOKIE+'='+cookie(first)),'prepare'),retained=decodePaymentIntent(cookie(again),key,owner)!;expect(first.status).toBe(200);expect(retained).toEqual(original);expect(original.operationId).not.toBe(requestId);expect(await first.json()).toEqual({operation_id:original.operationId,action:'customer.ensure'});expect(state.rpc).not.toHaveBeenCalled()})
it('execute application ACK loss retains the exact original immutable request on retry',async()=>{const handler=createAccountCardPaymentHandler(bound),prepared=await handler(request('prepare','POST',{request_id:requestId,action:'customer.ensure',input:{customer_revision:0}}),'prepare'),header=PAYMENT_INTENT_COOKIE+'='+cookie(prepared),intent=decodePaymentIntent(cookie(prepared),key,owner)!;state.rpc.mockRejectedValueOnce(new Error('lost application ACK')).mockImplementationOnce(async(_url,args)=>Response.json({contract_version:1,operation_id:args.p_operation_id,operation_revision:1,status:'pending',resource_revision:1,result:{customer_id:customer,revision:1,state:'reserved',operation:{operation_id:args.p_operation_id,operation_revision:1,action:'customer.ensure',resource_id:customer,resource_revision:1,status:'pending',recovery:'await_policy',continuation_token:null,action_expires_at:null}},error_code:null,retry_after_seconds:null}));expect((await handler(request('execute','POST',{request_id:requestId,expected_operation_id:intent.operationId},header),'execute')).status).toBe(503);const reply=await handler(request('execute','POST',{request_id:requestId,expected_operation_id:intent.operationId},header),'execute');expect(reply.status).toBe(200);expect((await reply.json()).operation_id).toBe(intent.operationId);expect(state.rpc.mock.calls[0][1]).toEqual(state.rpc.mock.calls[1][1]);expect(state.rpc.mock.calls[1][1]).toEqual({p_operation_id:intent.operationId,p_customer_revision:0})})
it('owner switch and duplicate private cookie names cannot reuse a prepared intention',async()=>{const handler=createAccountCardPaymentHandler(bound),prepared=await handler(request('prepare','POST',{request_id:requestId,action:'customer.ensure',input:{customer_revision:0}}),'prepare'),header=PAYMENT_INTENT_COOKIE+'='+cookie(prepared),intent=decodePaymentIntent(cookie(prepared),key,owner)!,body={request_id:requestId,expected_operation_id:intent.operationId};expect((await handler(request('execute','POST',body,header+'; '+header),'execute')).status).toBe(409);state.identity.mockResolvedValueOnce({kind:'verified',session:{ownerId:customer,token:'other.real.signature',provisional:new NextResponse(null)}});expect((await handler(request('execute','POST',body,header),'execute')).status).toBe(409);expect(state.rpc).not.toHaveBeenCalled()})
it('caller operation overrides and execute payload fields never reach SQL',async()=>{const handler=createAccountCardPaymentHandler(bound);expect((await handler(request('prepare','POST',{request_id:requestId,action:'customer.ensure',input:{operation_id:owner,customer_revision:0}}),'prepare')).status).toBe(400);expect((await handler(request('execute','POST',{owner_id:owner}),'execute')).status).toBe(400);expect(state.rpc).not.toHaveBeenCalled()})

it('actual B1 allocation/bind ACK recovery installs one original protected return cookie without DTO secret',async()=>{
 const {RETURN_CAPSULE_FIELDS,createReturnCapsule}=await import('../lib/payments/bridge-v1/scripts/backend/web-payment-browser-return-capsule.mjs');let metadata:Record<string,unknown>={},stateDigest:string|null=null,created=0,boundCalls=0,sdk=0;
 const envelope=(result:unknown)=>({browser_contract_version:1,status:'completed',result,error_code:null,retry_after_seconds:null}),issuable=()=>envelope({state:'issuable',metadata,metadata_hash:createReturnCapsule(metadata,new Uint8Array(32).fill(9)).metadata_hash,state_digest:stateDigest});
 const services=createPaymentSupabase({projectUrl:'https://example.supabase.co',publicKey:'sb_publishable_'+'a'.repeat(20),enabled:true,transportAccepted:true,acceptedB0AuthoritySha256:'6799e95ac25d0fa3c2a6a2f89dd0113d25f2bdcc3cb06c1b4a766c551b978f89',gatewayCredential:'g'.repeat(43),capsuleBindCredential:'b'.repeat(43),capsuleBindBearer:'Bearer service.binder.signature',fetcher:async(url,init)=>{
  if(String(url).includes('/auth/'))return Response.json({id:owner});const args=JSON.parse(String(init?.body)),path=String(url);
  if(path.endsWith('http_read_my_payment_browser_operation_v1')){const receipt={provider_contract_version:1,operation_id:metadata.begin_operation_id,operation_revision:1,status:'pending',result:{setup_id:customer,revision:1,state:'pending',card:null},error_code:null,retry_after_seconds:null};return Response.json(envelope({summary:{operation_id:metadata.begin_operation_id,action:'card.setup.begin',operation_revision:1,resource_id:customer,resource_revision:1,status:'pending',recovery:'customer_action',support_available:false},original_contract:'provider_v1',original_receipt:receipt,current_contract:'provider_v1',current_receipt:receipt}))}
  if(path.endsWith('http_create_my_payment_setup_return_state_v1')){created++;expect(args.p_request.request.return_admission_id).toBe(metadata.return_admission_id);expect(args.p_request.browser_digest).toBe(metadata.browser_digest);if(created===1)throw new Error('discarded allocation application ACK');return Response.json(issuable())}
  if(path.endsWith('http_bind_payment_setup_return_capsule_v1')){boundCalls++;stateDigest=args.p_request.state_digest;if(boundCalls===1)throw new Error('discarded binding application ACK');return Response.json(envelope({state:'bound',family_id:metadata.family_id,metadata_hash:args.p_request.metadata_hash}))}
  return Response.json(issuable())
 }});
 const ports=composePaymentWebsite({services,provider:{provision:{} as Provisioning,credential:()=>{sdk++;throw new Error('unexpected SDK')},transport:guardedTransport(()=>{sdk++;throw new Error('unexpected SDK')})},loadReturnKey:async()=>new Uint8Array(32).fill(9)},key,'pk_test_'+'a'.repeat(20)),handler=createAccountCardPaymentHandler(()=>ports),prepared=await handler(request('prepare','POST',{request_id:requestId,action:'card.setup.begin',input:{customer_revision:1,consent_id:owner}}),'prepare'),intent=decodePaymentIntent(cookie(prepared),key,owner)!;
 for(const [index,field]of RETURN_CAPSULE_FIELDS.entries())metadata[field]=field.endsWith('_id')?'00000000-0000-0000-0000-'+String(index+10).padStart(12,'0'):field.endsWith('_revision')?1:field.endsWith('_hash')||field==='browser_digest'?'c'.repeat(64):undefined;
 metadata={...metadata,owner_id:owner,begin_operation_id:intent.operationId,setup_id:customer,return_admission_id:intent.admissionId,browser_digest:paymentBrowserDigest(intent),nonce_base64url:Buffer.alloc(32,7).toString('base64url'),original_namespace:'provider_v1',original_action:'card.setup.begin',created_at_unix_microseconds:String(BigInt(Date.now())*1000n),expires_at_unix_microseconds:String(BigInt(Date.now()+240000)*1000n)};
 const expected=createReturnCapsule(metadata,new Uint8Array(32).fill(9));for(let n=0;n<2;n++){const response=await handler(request('setup/return','POST',{},PAYMENT_INTENT_COOKIE+'='+cookie(prepared)),'setup/return');expect(response.status).toBe(200);expect(response.headers.get('set-cookie')).toContain(PAYMENT_RETURN_COOKIE+'='+expected.token);expect(response.headers.get('set-cookie')).toContain('HttpOnly');const body=await response.text();expect(body).not.toContain('apr1');expect(body).not.toContain('metadata');expect(body).not.toContain(String(metadata.completion_operation_id))}expect(created).toBe(2);expect(boundCalls).toBe(2);expect(sdk).toBe(0)
});
it('a concurrent cookie replacement cannot execute another prepared operation',async()=>{const handler=createAccountCardPaymentHandler(bound),prepared=await handler(request('prepare','POST',{request_id:requestId,action:'customer.ensure',input:{customer_revision:0}}),'prepare');const response=await handler(request('execute','POST',{request_id:requestId,expected_operation_id:customer},PAYMENT_INTENT_COOKIE+'='+cookie(prepared)),'execute');expect(response.status).toBe(409);expect(state.rpc).not.toHaveBeenCalled()});
