// Actual Next owner handler/cookie responses use bounded local SQL/Auth doubles.
// No provider, Auth server, hosted database or financial mutation is exercised.
import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest,NextResponse} from 'next/server'
vi.mock('server-only',()=>({}))
const gates=vi.hoisted(()=>({identity:vi.fn(),admit:vi.fn(async()=>null)}))
vi.mock('../lib/supabase/config',()=>({accountConfig:()=>({siteOrigin:'https://antedotal.com'})}))
vi.mock('../lib/server/profile-photo-session',()=>({verifyProfilePhotoSession:gates.identity}))
vi.mock('../lib/server/callback-admission',()=>({admitAccountVisitor:gates.admit}))
import {createLongCollectionHandler,type LongCollectionBindings} from '../lib/server/account-long-collection'
import {decodeCollectionAdmission} from '../lib/server/collection-cookies'
const owner='11111111-1111-4111-8111-111111111111',commitment='22222222-2222-4222-8222-222222222222',collectionOperation='33333333-3333-4333-8333-333333333333',key=Buffer.alloc(32,3)
let collection:ReturnType<typeof vi.fn>,fresh:ReturnType<typeof vi.fn>,bindings:LongCollectionBindings
const req=(path:string,input:unknown={},cookie?:string,expectedOwner=owner)=>new NextRequest('https://antedotal.com/api/account/collections/'+path,{method:'POST',headers:{host:'antedotal.com',origin:'https://antedotal.com','content-type':'application/json','X-Ante-Payment-Owner':expectedOwner,...(cookie?{cookie}:{})},body:JSON.stringify(input)})
const cookie=(r:Response)=>r.headers.get('set-cookie')!.split(';')[0]
beforeEach(()=>{gates.identity.mockReset().mockResolvedValue({kind:'verified',session:{ownerId:owner,token:'a.b.c',provisional:new NextResponse(null)}});gates.admit.mockClear();fresh=vi.fn(async()=>{});collection=vi.fn(async()=>({error_code:null,result:{collection_contract_version:1,commitment_id:commitment,commitment_revision:1,task:{},collection_state:'requires_action',original_intent_known:true,continuation_available:true,collection_operation_id:collectionOperation}}));bindings={key,bindings:{enabled:true,services:{owner:async()=>({ownerId:owner,fresh,collection})}}} as unknown as LongCollectionBindings})
it('closed purpose denies before Auth, SQL or admission',async()=>{const r=await createLongCollectionHandler(()=>null)(req('prepare',{commitment_id:commitment,commitment_revision:1}),'prepare');expect(r.status).toBe(503);expect(gates.identity).not.toHaveBeenCalled();expect(collection).not.toHaveBeenCalled()})
it('original owned commitment prepare ACK stores only read lineage and exact replay retains it',async()=>{const run=createLongCollectionHandler(()=>bindings),input={commitment_id:commitment,commitment_revision:1},first=await run(req('prepare',input),'prepare');expect(first.status).toBe(200);const stored=cookie(first),decoded=decodeCollectionAdmission(stored.split('=')[1],key,owner)!;expect(decoded.commitmentId).toBe(commitment);expect(decoded).not.toHaveProperty('operationId');const again=await run(req('prepare',input,stored),'prepare');expect(decodeCollectionAdmission(cookie(again).split('=')[1],key,owner)).toEqual(decoded);expect(await first.json()).toEqual({collection_state:'requires_action',continuation_available:true,original_intent_known:true});expect(first.headers.get('cache-control')).toContain('no-store')})
it('foreign owner and provider selectors cannot reach fixed SQL',async()=>{const run=createLongCollectionHandler(()=>bindings),input={commitment_id:commitment,commitment_revision:1};expect((await run(req('prepare',input,undefined,commitment),'prepare')).status).toBe(409);expect(collection).not.toHaveBeenCalled();expect((await run(req('prepare',{...input,provider_intent_id:'pi_foreign'}),'prepare')).status).toBe(400);expect(collection).not.toHaveBeenCalled()})
it('final owner change suppresses progress ACK and read cookie installation',async()=>{fresh.mockRejectedValue(new Error('not_authenticated'));const r=await createLongCollectionHandler(()=>bindings)(req('prepare',{commitment_id:commitment,commitment_revision:1}),'prepare');expect(r.status).toBe(401);expect(r.headers.get('set-cookie')).toBeNull()})
it('actual bounded SQL read quota maps 429 and Retry-After',async()=>{collection.mockResolvedValue({error_code:'rate_limited',retry_after_seconds:17});const r=await createLongCollectionHandler(()=>bindings)(req('prepare',{commitment_id:commitment,commitment_revision:1}),'prepare');expect(r.status).toBe(429);expect(r.headers.get('retry-after')).toBe('17');expect(r.headers.get('set-cookie')).toBeNull()})
it('foreign/stale commitment projection and unexpected secret fields refuse ordinary response',async()=>{for(const delta of [{commitment_id:collectionOperation},{client_secret:'pi_secret'}]){collection.mockResolvedValue({error_code:null,result:{collection_contract_version:1,commitment_id:commitment,commitment_revision:1,task:{},collection_state:'requires_action',original_intent_known:true,continuation_available:true,collection_operation_id:collectionOperation,...delta}});const r=await createLongCollectionHandler(()=>bindings)(req('prepare',{commitment_id:commitment,commitment_revision:1}),'prepare');expect(r.status).not.toBe(200);expect(JSON.stringify(await r.json())).not.toContain('pi_secret')}})
