// Actual owner handler/AEAD tests use ledger doubles, with no hosted/provider work.
import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest,NextResponse} from 'next/server'
vi.mock('server-only',()=>({}))
const gate=vi.hoisted(()=>({admit:vi.fn(async()=>null),identity:vi.fn()}))
vi.mock('../lib/supabase/config',()=>({accountConfig:()=>({siteOrigin:'https://antedotal.com'})}))
vi.mock('../lib/server/callback-admission',()=>({admitAccountVisitor:gate.admit}))
vi.mock('../lib/server/profile-photo-session',()=>({verifyProfilePhotoSession:gate.identity}))
import {createPaymentReviewHandler} from '../lib/server/account-payment-review'
import {newReviewReadAdmission,reviewReadCookie} from '../lib/server/review-read-admission'
import {decodePaymentIntent,encodePaymentIntent} from '../lib/server/payment-cookies'
import type {FinancialWebsiteBindings} from '../lib/server/financial-bridge'
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,owner=id(1),taskId=id(2),commitment=id(3),key=Buffer.alloc(32,3),reviewKey=Buffer.alloc(32,4)
let review:ReturnType<typeof vi.fn>,binding:{financial:FinancialWebsiteBindings;key:Buffer},current:Record<string,unknown>,taskCookie:string
const envelope=(operation:string|null,result:unknown,status='completed',error:string|null=null,retry:number|null=null)=>({commitment_contract_version:1,operation_id:operation,operation_revision:operation?1:null,status,result,error_code:error,retry_after_seconds:retry})
function request(path:string,input?:unknown,cookies=taskCookie,expectedOwner=owner){return new NextRequest('https://antedotal.com/api/account/payment-review/'+path,{method:input===undefined?'GET':'POST',headers:{host:'antedotal.com',origin:'https://antedotal.com','X-Ante-Payment-Owner':expectedOwner,...(input===undefined?{}:{'content-type':'application/json'}),...(cookies?{cookie:cookies}:{})},...(input===undefined?{}:{body:JSON.stringify(input)})})}
const body={request_id:id(4),action:'appeal',reason:'Review original evidence',asset_ids:[]}
function cookie(r:Response){return r.headers.get('set-cookie')!.split(';')[0]}
beforeEach(()=>{vi.clearAllMocks();current={authority_kind:'financial-commitment-view-v1',commitment_id:commitment,task_id:taskId,revision:1,amount_minor:'100',currency:'AUD',started_at:'2026-10-08T00:00:00.000000Z',funding_state:'unknown',outcome:{authority_kind:'financial-ledger-binding-v1',outcome_id:id(5),outcome_revision:1,outcome_hash:'a'.repeat(64),outcome:'failed',proof_resolution_id:id(6),proof_resolution_revision:1,proof_resolution_hash:'b'.repeat(64)},cases:[],finality:null};taskCookie=reviewReadCookie+'='+encodePaymentIntent(newReviewReadAdmission(owner,commitment,1),reviewKey);review=vi.fn(async(action:string,input:Record<string,unknown>)=>action==='read'?envelope(null,current):action==='list'?{review_projection_version:1,items:[{commitment_id:commitment,task_id:taskId,revision:1,amount_minor:'100',currency:'AUD',started_at:'2026-10-08T00:00:00.000000Z'}],next_cursor:null}:action==='assets'?{review_projection_version:1,commitment_id:commitment,items:[{asset_id:id(23),created_at:'2026-10-08T00:00:00.000000Z'}],next_cursor:null}:action==='history'?{commitment_contract_version:1,authority_kind:'financial-history-v1',items:[]}:envelope(String(input.operation_id),null,'unknown'));const task=vi.fn(async()=>({financial_task_contract_version:1,operation_id:null,operation_revision:null,resource_revision:1,status:'completed',result:{task_id:taskId,task_revision:1,state:'active',commitment_id:commitment,commitment_revision:1,amount_minor:'100',currency:'AUD',quote_id:id(9),quote_hash:'c'.repeat(64),funding_state:'active_unsecured',started_at:'2026-10-08T00:00:00.000Z'},error_code:null,retry_after_seconds:null}));binding={key:reviewKey,financial:{enabled:true,cookieKeys:{task:key,premium:key},services:{owner:async()=>({ownerId:owner,task,review})}} as unknown as FinancialWebsiteBindings};gate.identity.mockResolvedValue({kind:'verified',session:{ownerId:owner,token:'a.b.c',provisional:new NextResponse(null)}})})
it('closed and malformed inputs deny before identity and admission',async()=>{expect((await createPaymentReviewHandler(()=>null)(request('progress'),'progress')).status).toBe(503);expect((await createPaymentReviewHandler(()=>binding)(request('prepare',{...body,outcome_id:id(99)}),'prepare')).status).toBe(400);expect(gate.admit).not.toHaveBeenCalled();expect(gate.identity).not.toHaveBeenCalled()})
it('prepare freezes original outcome and lost ACK retry preserves exact operation',async()=>{const run=createPaymentReviewHandler(()=>binding),first=await run(request('prepare',body),'prepare');expect(first.status).toBe(200);const ack=await first.json(),stored=cookie(first),intent=decodePaymentIntent(stored.split('=')[1],reviewKey,owner)!;expect(intent.input).toMatchObject({commitment_id:commitment,commitment_revision:1,outcome_id:id(5),outcome_hash:'a'.repeat(64)});current={...current,revision:2};const second=await run(request('prepare',body,taskCookie+'; '+stored),'prepare');expect(await second.json()).toEqual(ack);expect(review.mock.calls.filter(c=>c[0]==='appeal')).toHaveLength(0);const execute=await run(request('execute',{request_id:ack.request_id,operation_id:ack.operation_id},stored),'execute');expect(execute.status).toBe(200);expect(review).toHaveBeenLastCalledWith('appeal',{...intent.input,operation_id:ack.operation_id})})
it('prepare-only unknown original blocks replacement; forged execute and changed owner cannot write',async()=>{const run=createPaymentReviewHandler(()=>binding),first=await run(request('prepare',body),'prepare'),ack=await first.json(),stored=cookie(first);expect((await run(request('prepare',{...body,request_id:id(44)},taskCookie+'; '+stored),'prepare')).status).toBe(409);expect((await run(request('execute',{...ack,operation_id:id(44)},stored),'execute')).status).toBe(400);expect((await run(request('intent',undefined,stored,id(99)),'intent')).status).toBe(409);expect(review.mock.calls.filter(c=>c[0]==='appeal')).toHaveLength(0)})
it('recovery needs only original cookie and preserves original quota Retry-After',async()=>{const run=createPaymentReviewHandler(()=>binding),first=await run(request('prepare',body),'prepare'),ack=await first.json(),stored=cookie(first);review.mockResolvedValue(envelope(ack.operation_id,null,'denied','rate_limited',17));const recovered=await run(request('recover',{},stored),'recover');expect(recovered.status).toBe(429);expect(recovered.headers.get('retry-after')).toBe('17');expect(recovered.headers.get('cache-control')).toContain('no-store')})
it('finality blocks appeal prepare and an existing case cannot be resubmitted',async()=>{const run=createPaymentReviewHandler(()=>binding);current={...current,finality:{finality_id:id(11),action:'collect',financial_dispatch:false}};expect((await run(request('prepare',body),'prepare')).status).toBe(409);current={...current,finality:null,cases:[{case_id:id(12),kind:'appeal',state:'reviewer_pending'}]};expect((await run(request('prepare',body),'prepare')).status).toBe(409)})

it('returning-owner discovery and fresh read selection need no task/funding/effect cookie',async()=>{const run=createPaymentReviewHandler(()=>binding),listed=await run(request('commitments',{after:null},''),'commitments');expect(listed.status).toBe(200);expect(await listed.json()).toMatchObject({items:[{commitment_id:commitment}]});const selected=await run(request('select',{commitment_id:commitment},''),'select');expect(selected.status).toBe(200);const read=cookie(selected);expect(read).toMatch(new RegExp('^'+reviewReadCookie+'='));expect(selected.headers.get('set-cookie')).not.toContain('__Host-ante-financial-task');expect(selected.headers.get('set-cookie')).not.toContain('__Host-ante-payment-review=');const progress=await run(request('progress',undefined,read),'progress');expect(progress.status).toBe(200);const prepared=await run(request('prepare',{...body,asset_ids:[id(23)]},read),'prepare');expect(prepared.status).toBe(200);const frozen=decodePaymentIntent(cookie(prepared).split('=')[1],reviewKey,owner)!;expect(frozen.input.asset_ids).toEqual([id(23)]);expect(review.mock.calls.filter(c=>['appeal','dispute'].includes(c[0]))).toHaveLength(0)})
it('cross-owner and cross-commitment projections cannot create a read admission',async()=>{const run=createPaymentReviewHandler(()=>binding);expect((await run(request('select',{commitment_id:commitment},'',id(99)),'select')).status).toBe(409);review.mockResolvedValue(envelope(null,{...current,commitment_id:id(88)}));const forged=await run(request('select',{commitment_id:commitment},''),'select');expect(forged.status).toBe(503);expect(forged.headers.get('set-cookie')).toBeNull()})
it('expired read admission can be replaced without replacing pending report or original task admission',async()=>{const run=createPaymentReviewHandler(()=>binding),first=await run(request('prepare',body),'prepare'),ack=await first.json(),report=cookie(first);const time=Date.now();const clock=vi.spyOn(Date,'now').mockReturnValue(time+1800001);expect((await run(request('progress',undefined,taskCookie),'progress')).status).toBe(409);const selected=await run(request('select',{commitment_id:commitment},''),'select');expect(selected.status).toBe(200);expect(selected.headers.get('set-cookie')).toContain(reviewReadCookie);clock.mockRestore();const recovered=await run(request('recover',{},report),'recover');expect(recovered.status).toBe(200);expect(review).toHaveBeenLastCalledWith('recover',{operation_id:ack.operation_id})})
it('malformed pagination/evidence requests deny before owner work; bounded quota is retained',async()=>{const run=createPaymentReviewHandler(()=>binding);expect((await run(request('commitments',{after:null,limit:100},''),'commitments')).status).toBe(400);expect((await run(request('evidence',{after:'provider_secret'},taskCookie),'evidence')).status).toBe(400);review.mockResolvedValue(envelope(null,null,'denied','rate_limited',29));const response=await run(request('commitments',{after:null},''),'commitments');expect(response.status).toBe(429);expect(response.headers.get('retry-after')).toBe('29')})
it('fixed evidence view exposes only same-commitment pre-existing asset IDs',async()=>{const run=createPaymentReviewHandler(()=>binding),response=await run(request('evidence',{after:null},taskCookie),'evidence');expect(response.status).toBe(200);expect(await response.json()).toEqual({review_projection_version:1,items:[{asset_id:id(23),created_at:'2026-10-08T00:00:00.000000Z'}],next_cursor:null,commitment_id:commitment});review.mockResolvedValue({review_projection_version:1,commitment_id:id(99),items:[],next_cursor:null});expect((await run(request('evidence',{after:null},taskCookie),'evidence')).status).toBe(503)})
