// Render actual financial UI with a dependency-aware local hook host. All
// responses are fixed authoritative DTO fixtures, never real owner/provider work.
import {beforeEach,expect,it,vi} from 'vitest'
const hooks=vi.hoisted(()=>({states:[] as unknown[],cursor:0,effects:[] as (()=>unknown)[],deps:[] as unknown[][]}))
vi.mock('react',()=>({useState:(v:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]=v;return [hooks.states[i],(next:unknown)=>{hooks.states[i]=typeof next==='function'?(next as (old:unknown)=>unknown)(hooks.states[i]):next}]},useRef:(v:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]={current:v};return hooks.states[i]},useCallback:(fn:unknown)=>{hooks.cursor++;return fn},useEffect:(fn:()=>unknown,deps:unknown[])=>{const i=hooks.cursor++;if(!hooks.deps[i]||deps.some((d,n)=>typeof d!=='function'&&d!==hooks.deps[i][n])){hooks.deps[i]=deps;hooks.effects.push(fn)}}}))
import AccountFinancial from '../components/account/AccountFinancial'
import HoldAuthentication from '../components/account/HoldAuthentication'
import AccountPayments from '../components/account/AccountPayments'
type Element={type:unknown;props:Record<string,unknown>}
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,owner=id(1),selection={configuration_id:id(2),configuration_revision:1,card_id:id(3),card_revision:1,consent_id:id(4),consent_revision:1,settings_hash:'a'.repeat(64),eligibility_revision:1},premiumSelection={customer_revision:1,entitlement_revision:0,configuration_id:id(2),configuration_revision:1,consent_id:id(4),consent_revision:1}
const context={policies:[],task:{available:true,selections:[{funding_mode:'short_authorization',cutoff_seconds:172800,processing_buffer_seconds:3600,selection},{funding_mode:'long_unsecured',cutoff_seconds:null,processing_buffer_seconds:null,selection:{...selection,configuration_id:id(9)}}],lists:[{list_id:'web-tasks-v1',label:'Tasks'}],verifiers:[{verifier_id:id(5),label:'Friend'}]},premium:{available:true,plans:[{plan_key:'monthly',amount_minor:'1000',currency:'AUD',selection:premiumSelection},{plan_key:'annual',amount_minor:'10000',currency:'AUD',selection:premiumSelection}]}}
const quote={quote_id:id(6),quote_hash:'b'.repeat(64),task_id:id(7),task_revision:1,amount_minor:'1250',currency:'AUD',expires_at:'2030-01-01T00:00:00.000Z',eligibility_revision:1,snapshot_hash:'c'.repeat(64)},progress={task_id:id(7),task_revision:1,state:'draft',commitment_id:null,commitment_revision:null,amount_minor:'1250',currency:'AUD',quote_id:id(6),quote_hash:'b'.repeat(64),funding_state:null,started_at:null}
const primary={request_id:id(10),operation_id:id(11),action:'task.quote'},secondary={request_id:id(12),operation_id:id(13),action:'task.admit'}
const envelope=(result:unknown,operation:string|null=null,subscription=false)=>({[subscription?'subscription_contract_version':'financial_task_contract_version']:1,operation_id:operation,operation_revision:operation?1:null,resource_revision:result&&typeof result==='object'&&'task_revision'in result?(result as {task_revision:number}).task_revision:result&&typeof result==='object'&&'revision'in result?(result as {revision:number}).revision:null,status:result===null?'unknown':'completed',result,error_code:null,retry_after_seconds:null})
let purpose:'task'|'premium',fetcher:ReturnType<typeof vi.fn>,task:Record<string,unknown>,restored:{primary:unknown;secondary:unknown},entitlement:Record<string,unknown>,subscriptions:unknown[],frameCount:number
function elements(value:unknown):Element[]{if(!value)return [];if(Array.isArray(value))return value.flatMap(elements);if(typeof value!=='object'||!('props'in value))return [];const e=value as Element;return [e,...elements(e.props.children)]}
function text(value:unknown):string{if(Array.isArray(value))return value.map(text).join(' ').replace(/\s+/g,' ');if(typeof value==='string'||typeof value==='number')return String(value);if(value&&typeof value==='object'&&'props'in value)return text((value as Element).props.children);return ''}
function render(enabled=true,ownerId=owner){hooks.cursor=0;return AccountFinancial({enabled,ownerId,purpose,publishableKey:'pk_test_fixture'})}
function button(tree:unknown,label:string){return elements(tree).find(e=>e.type==='button'&&text(e.props.children)===label)!}
async function settle(){await new Promise(resolve=>setTimeout(resolve,0));await new Promise(resolve=>setTimeout(resolve,0))}
async function start(){render();for(const effect of hooks.effects.splice(0))effect();await settle();return render()}
beforeEach(()=>{hooks.states=[];hooks.deps=[];hooks.effects=[];purpose='task';task={...progress};restored={primary,secondary:null};entitlement={revision:0,tier:'free',provider_verified:false,effective_until:null,cap_configuration_id:null,cap_configuration_revision:null};subscriptions=[];frameCount=0;fetcher=vi.fn(async(path:unknown,_init?:RequestInit)=>{void _init;const url=String(path);if(url.endsWith('/context'))return Response.json(context);if(url.endsWith('/intent'))return Response.json(restored);if(url.endsWith('/review'))return Response.json({task_id:progress.task_id,title:'Original task',details:null,due_date:'2030-01-01T00:00:00.000Z',difficulty_preset:'easy',list_id:'web-tasks-v1',verifier_ids:[id(5)],funding_mode:'short_authorization'});if(url.endsWith('/settings'))return Response.json(envelope({settings:{easy_cents:1000,medium_cents:2000,hard_cents:3000,updated_at:'2026-01-01T00:00:00.000Z'},settings_hash:'a'.repeat(64)}));if(url.endsWith('/original'))return Response.json({primary:envelope(quote,primary.operation_id),secondary:restored.secondary?envelope(null,secondary.operation_id):null});if(url.endsWith('/current'))return purpose==='task'?Response.json(envelope(task)):Response.json({subscriptions:envelope({subscriptions,next_cursor:null},null,true),entitlement:envelope(entitlement,null,true)});if(url.endsWith('/hold'))return Response.json({result:{short_hold_contract_version:1,commitment_id:task.commitment_id,commitment_revision:task.commitment_revision,task:null,backing_state:'requires_action',capture_before:null,original_intent_known:true,continuation_available:true},error_code:null});if(url.endsWith('/return/issue'))return Response.json({state:'ready'});if(url.endsWith('/return/continue'))return Response.json({purpose:'task.short_hold.continue',commitment_id:task.commitment_id,commitment_revision:task.commitment_revision,provider_intent_id:'pi_original',client_secret:'pi_original_secret_'+(++frameCount),expires_at:'2030-01-01T00:00:00.000Z',return_route_key:'account_payments'});if(url.endsWith('/prepare'))return Response.json({request_id:id(20),operation_id:id(21),action:JSON.parse(String(_init?.body)).action});return Response.json({})});vi.stubGlobal('fetch',fetcher)})
it('reload reviews exact original quote and affirmative confirmation cannot choose money or operation',async()=>{let tree=await start();expect(text(tree)).toContain('Quoted amount: $12.50');expect(button(tree,'Confirm quoted amount and start').props.disabled).toBe(true);const checkbox=elements(tree).find(e=>e.type==='input'&&e.props.type==='checkbox'&&text(tree).includes('I confirm'))!;const quoteCheck=elements(tree).filter(e=>e.type==='input'&&e.props.type==='checkbox').at(-1)!;void checkbox;(quoteCheck.props.onChange as (e:unknown)=>void)({target:{checked:true}});tree=render();expect(button(tree,'Confirm quoted amount and start').props.disabled).toBe(false);(button(tree,'Confirm quoted amount and start').props.onClick as ()=>void)();await settle();const prepare=fetcher.mock.calls.find(([path])=>String(path).endsWith('/prepare'))!;expect(JSON.parse(String(prepare[1]?.body))).toMatchObject({action:'task.admit',input:{affirmative:true,quote_id:quote.quote_id,quote_hash:quote.quote_hash,task_revision:quote.task_revision}});expect(JSON.stringify(prepare[1]?.body)).not.toContain('1250');expect(text(render())).not.toContain('revision')})
it('started amount stays fixed while current defaults and both approved funding modes render separately',async()=>{task={...progress,state:'active',task_revision:2,commitment_id:id(30),commitment_revision:2,funding_state:'authorized',started_at:'2026-10-08T00:00:00.000Z'};restored.secondary=secondary;const tree=await start();expect(text(tree)).toContain('Started amount (fixed) : $12.50');expect(text(tree)).toContain('Easy $10.00');expect(text(tree)).toContain('Started with a verified hold');expect(text(tree)).toContain('Short task authorization hold');expect(text(tree)).toContain('Long task without reserved funds');expect(button(tree,'Confirm quoted amount and start').props.disabled).toBe(true)})
it('actual original customer-action frame remains pending and stale callbacks cannot affect replacement or disabled view',async()=>{task={...progress,state:'payment_pending',commitment_id:id(30),commitment_revision:1};restored.secondary=secondary;const tree=await start();expect(text(tree)).toContain('Waiting for verified backing');(button(tree,'Continue original authentication').props.onClick as ()=>void)();await settle();const old=elements(render()).find(e=>e.type===HoldAuthentication)!;expect(old.props.ticket).toMatchObject({client_secret:'pi_original_secret_1'});(button(render(),'Check current progress').props.onClick as ()=>void)();await settle();(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle();const next=elements(render()).find(e=>e.type===HoldAuthentication)!;expect(next.props.ticket).not.toBe(old.props.ticket);const count=fetcher.mock.calls.length;(old.props.onExpired as ()=>void)();await(old.props.onConfirmed as ()=>Promise<void>)();expect(fetcher.mock.calls).toHaveLength(count);expect(elements(render()).find(e=>e.type===HoldAuthentication)?.props.ticket).toBe(next.props.ticket);expect(elements(render(false)).some(e=>e.type===HoldAuthentication)).toBe(false);expect(text(render())).not.toContain('Started with a verified hold')})
it('Premium monthly/annual exact offers are separate from current paid access and cancellation survives unavailable plans',async()=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[{subscription_id:id(40),revision:2,plan_key:'monthly',state:'active',paid_through:'2030-01-01T00:00:00.000Z',cancel_at_period_end:false,checkout_url:null}];let tree=await start();expect(text(tree)).toContain('Monthly · $10.00');expect(text(tree)).toContain('Annual · $100.00');expect(text(tree)).not.toContain('Premium access verified until');expect(button(tree,'Cancel renewal at period end').props.disabled).toBe(false);const view=hooks.states.find(v=>v&&typeof v==='object'&&'subscriptions'in v) as {context:typeof context};view.context={...context,premium:{available:false,plans:[]}};tree=render();expect(button(tree,'Cancel renewal at period end').props.disabled).toBe(false);(button(tree,'Cancel renewal at period end').props.onClick as ()=>void)();await settle();expect(JSON.parse(String(fetcher.mock.calls.find(([path])=>String(path).endsWith('/prepare'))![1]?.body))).toMatchObject({action:'premium.cancel',input:{subscription_id:id(40)}})})
it('only provider-verified current paid interval displays Premium access and passes approved legal descriptors separately',async()=>{purpose='premium';restored={primary:null,secondary:null};entitlement={revision:1,tier:'premium',provider_verified:true,effective_until:'2030-01-01T00:00:00.000Z',cap_configuration_id:id(50),cap_configuration_revision:1};const tree=await start();expect(text(tree)).toContain('Premium access verified until');const consent=elements(tree).find(e=>e.type===AccountPayments)!;expect(consent.props.consentOnlyPurpose).toBe('premium');expect(consent.props.financialPolicies).toEqual([])})
it('reload shows original task details alongside amount rather than the mutable new-task form',async()=>{const old=fetcher.getMockImplementation()!;fetcher.mockImplementation((path:unknown,init?:RequestInit)=>String(path).endsWith('/review')?Promise.resolve(Response.json({task_id:progress.task_id,title:'Frozen original task',details:'Original details',due_date:'2030-01-01T00:00:00.000Z',difficulty_preset:'easy',list_id:'web-tasks-v1',verifier_ids:[id(5)],funding_mode:'short_authorization'})):old(path,init));const tree=await start();expect(text(tree)).toContain('Frozen original task');expect(text(tree)).toContain('Original details');expect(text(tree)).toContain('Quoted amount: $12.50')})
it('unavailable original details cannot enable quote confirmation after reload',async()=>{const old=fetcher.getMockImplementation()!;fetcher.mockImplementation((path:unknown,init?:RequestInit)=>String(path).endsWith('/review')?Promise.resolve(Response.json({error_code:'unavailable'},{status:503})):old(path,init));const tree=await start();const check=elements(tree).filter(e=>e.type==='input'&&e.props.type==='checkbox').at(-1)!;(check.props.onChange as (e:unknown)=>void)({target:{checked:true}});expect(button(render(),'Confirm quoted amount and start').props.disabled).toBe(true)})
it('disabled render synchronously fences callbacks from the previous mounted financial frame before effects',async()=>{task={...progress,state:'payment_pending',commitment_id:id(30),commitment_revision:1};restored.secondary=secondary;await start();(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle();const old=elements(render()).find(e=>e.type===HoldAuthentication)!;render(false);const before=fetcher.mock.calls.length;await(old.props.onConfirmed as ()=>Promise<void>)();(old.props.onExpired as ()=>void)();expect(fetcher.mock.calls).toHaveLength(before)})
// Continue retries only the read-purpose issue/consume pair. Neither expiry nor
// an unsuccessful delivery can choose new financial IDs or prepare a new task.
it.each(['expired','unsuccessful'])('Continue stays tied to original pending task after %s customer-action attempt',async mode=>{
 task={...progress,state:'payment_pending',commitment_id:id(30),commitment_revision:1};restored.secondary=secondary;await start()
 if(mode==='unsuccessful')fetcher.mockImplementationOnce(async()=>Response.json({state:'ready'})).mockImplementationOnce(async()=>Response.json({error_code:'operation_pending'},{status:409}))
 ;(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle()
 if(mode==='expired'){const frame=elements(render()).find(e=>e.type===HoldAuthentication)!;(frame.props.onExpired as ()=>void)();expect(elements(render()).some(e=>e.type===HoldAuthentication)).toBe(false)}
 expect(button(render(),'Continue original authentication').props.disabled).toBe(false);(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle()
 expect(elements(render()).find(e=>e.type===HoldAuthentication)?.props.ticket).toMatchObject({client_secret:'pi_original_secret_'+(mode==='expired'?2:1)});expect(task.state).toBe('payment_pending');expect(restored.secondary).toBe(secondary)
 const calls=fetcher.mock.calls.filter(([path])=>String(path).includes('/return/'));expect(calls).toHaveLength(4);expect(calls.map(([path])=>String(path).split('/').at(-1))).toEqual(['issue','continue','issue','continue']);for(const [,init]of calls)expect(JSON.parse(String(init?.body))).toEqual({});expect(fetcher.mock.calls.some(([path])=>String(path).endsWith('/prepare'))).toBe(false)
})

// Future nonpaid projections are synthetic source fixtures; independent earned
// entitlement is retained while billing recovery remains an explicit owner read.
const billingSub=(state:string,cancel=false)=>({subscription_id:id(70),revision:4,plan_key:'monthly',state,paid_through:'2030-01-01T00:00:00.000Z',cancel_at_period_end:cancel,checkout_url:null})
it.each([['past_due','Payment overdue'],['unpaid','Subscription unpaid'],['paused','Subscription paused'],['canceled','Canceled'],['cancel_scheduled','Renewal cancellation scheduled'],['active','Renewal cancellation scheduled']])('truthful %s billing status preserves independently earned access without clearing obligations',async(state,label)=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub(state,state==='cancel_scheduled'||state==='active')];entitlement={revision:2,tier:'premium',provider_verified:true,effective_until:'2030-01-01T00:00:00.000Z',cap_configuration_id:id(80),cap_configuration_revision:1};const tree=await start();expect(text(tree)).toContain(label);expect(text(tree)).toContain('Premium access verified until');expect(text(tree)).toContain('Paid through');expect(text(tree)).toContain('does not confirm that all payment obligations are cleared');expect(fetcher.mock.calls.every(([,init])=>init?.method==='GET')).toBe(true);if(['past_due','unpaid','paused'].includes(state)){expect(elements(tree).find(e=>e.type==='a'&&e.props.href==='/account/payments')).toBeDefined();expect(text(tree)).toContain('Updating a card does not authorize a new charge.')}})
it.each(['checkout_pending','unknown','canceled','cancel_scheduled'])('unconfirmed or already ended/scheduled %s subscription cannot request renewal cancellation',async state=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub(state,state==='cancel_scheduled')];const tree=await start();expect(button(tree,'Cancel renewal at period end').props.disabled).toBe(true)})
it('explicit current billing read shares the action lock and pending feedback with cancellation',async()=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub('past_due')];const tree=await start(),oldCancel=button(tree,'Cancel renewal at period end');let release!:(response:Response)=>void;fetcher.mockImplementationOnce(()=>new Promise<Response>(resolve=>{release=resolve}));(button(tree,'Check current progress').props.onClick as ()=>void)();const pending=render();expect(pending.props['aria-busy']).toBe(true);expect(button(pending,'Check current progress').props.disabled).toBe(true);expect(button(pending,'Cancel renewal at period end').props.disabled).toBe(true);expect(text(pending)).toContain('Checking current billing progress');(oldCancel.props.onClick as ()=>void)();expect(fetcher.mock.calls.some(([path])=>String(path).endsWith('/prepare'))).toBe(false);release(Response.json(context));await settle();expect(render().props['aria-busy']).toBe(false)})
it('old billing revision and disabled/owner/purpose callbacks cannot issue new cancellation reads',async()=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub('past_due')];const tree=await start(),old=button(tree,'Cancel renewal at period end');subscriptions=[{...billingSub('past_due'),revision:5}];(button(tree,'Check current progress').props.onClick as ()=>void)();await settle();render();let count=fetcher.mock.calls.length;(old.props.onClick as ()=>void)();expect(fetcher.mock.calls).toHaveLength(count);const current=button(render(),'Cancel renewal at period end');render(false);count=fetcher.mock.calls.length;(current.props.onClick as ()=>void)();expect(fetcher.mock.calls).toHaveLength(count);render(true,id(99));(current.props.onClick as ()=>void)();expect(fetcher.mock.calls).toHaveLength(count);purpose='task';const changed=render();expect(text(changed)).not.toContain('Payment overdue');(current.props.onClick as ()=>void)();expect(fetcher.mock.calls).toHaveLength(count)})

it('late nonpaid read after a replacement owner render cannot paint earned access or issue old-frame recovery',async()=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub('past_due')];const tree=await start(),oldCheck=button(tree,'Check current progress');let release!:(response:Response)=>void;fetcher.mockImplementationOnce(()=>new Promise<Response>(resolve=>{release=resolve}));(oldCheck.props.onClick as ()=>void)();const before=fetcher.mock.calls.length;render(true,id(99));(oldCheck.props.onClick as ()=>void)();expect(fetcher.mock.calls).toHaveLength(before);release(Response.json(context));await settle();const replacement=render(true,id(99));expect(text(replacement)).not.toContain('Payment overdue');expect(text(replacement)).not.toContain('Premium access verified until')})

it('reenabled billing controls await a new owned read rather than borrowing retired progress',async()=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub('past_due')];await start();render(false);const tree=render(true);expect(button(tree,'Cancel renewal at period end').props.disabled).toBe(true);expect(button(tree,'Purchase monthly Premium').props.disabled).toBe(true)})
it('paginated current billing retains usable controls while retiring callbacks from the earlier read generation',async()=>{purpose='premium';restored={primary:null,secondary:null};subscriptions=[billingSub('past_due')];const base=fetcher.getMockImplementation()!;fetcher.mockImplementation(async(path:unknown,init?:RequestInit)=>String(path).endsWith('/current')?Response.json({subscriptions:envelope({subscriptions,next_cursor:'a'.repeat(32)},null,true),entitlement:envelope(entitlement,null,true)}):String(path).endsWith('/subscriptions')?Response.json(envelope({subscriptions:[{...billingSub('paused'),subscription_id:id(71)}],next_cursor:null},null,true)):base(path,init));const tree=await start(),old=button(tree,'Cancel renewal at period end');(button(tree,'Load more subscriptions').props.onClick as ()=>void)();await settle();const current=button(render(),'Cancel renewal at period end');expect(current.props.disabled).toBe(false);(old.props.onClick as ()=>void)();expect(fetcher.mock.calls.some(([path])=>String(path).endsWith('/prepare'))).toBe(false);(current.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls.filter(([path])=>String(path).endsWith('/prepare'))).toHaveLength(1)})

// Confirmation is an interaction with the exact currently reviewed original
// quote. Retained React callbacks must never authorize a replacement cookie quote.
function quoteCheckbox(tree:unknown){return elements(tree).filter(e=>e.type==='input'&&e.props.type==='checkbox').at(-1)!}
function affirm(tree:unknown,checked=true){(quoteCheckbox(tree).props.onChange as (event:unknown)=>void)({target:{checked}})}
it('retained confirmed quote cannot admit the replacement original quote after a current read',async()=>{
 let tree=await start();affirm(tree);tree=render();const oldConfirm=button(tree,'Confirm quoted amount and start'),replacement={...quote,quote_id:id(60),quote_hash:'d'.repeat(64),task_id:id(61),amount_minor:'3000'},replacementOperation={...primary,request_id:id(62),operation_id:id(63)},base=fetcher.getMockImplementation()!;
 restored={primary:replacementOperation,secondary:null};task={...progress,task_id:replacement.task_id,quote_id:replacement.quote_id,quote_hash:replacement.quote_hash,amount_minor:replacement.amount_minor};
 fetcher.mockImplementation((path:unknown,init?:RequestInit)=>String(path).endsWith('/original')?Promise.resolve(Response.json({primary:envelope(replacement,replacementOperation.operation_id),secondary:null})):String(path).endsWith('/review')?Promise.resolve(Response.json({task_id:replacement.task_id,title:'Replacement original task',details:null,due_date:'2030-01-01T00:00:00.000Z',difficulty_preset:'easy',list_id:'web-tasks-v1',verifier_ids:[id(5)],funding_mode:'short_authorization'})):base(path,init));
 (button(tree,'Check current progress').props.onClick as ()=>void)();await settle();expect(text(render())).toContain('Quoted amount: $30.00');const calls=fetcher.mock.calls.length;(oldConfirm.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls).toHaveLength(calls);
})
it('unchecking current quote synchronously retires an already rendered affirmative callback',async()=>{let tree=await start();affirm(tree);tree=render();const confirmed=button(tree,'Confirm quoted amount and start');expect(confirmed.props.disabled).toBe(false);affirm(tree,false);const calls=fetcher.mock.calls.length;(confirmed.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls).toHaveLength(calls);expect(button(render(),'Confirm quoted amount and start').props.disabled).toBe(true)})
it('a new read of the same original amount requires fresh affirmation and rejects an older checkbox',async()=>{let tree=await start();affirm(tree);tree=render();const oldCheckbox=quoteCheckbox(tree),oldConfirm=button(tree,'Confirm quoted amount and start');(button(tree,'Check current progress').props.onClick as ()=>void)();await settle();tree=render();expect(quoteCheckbox(tree).props.checked).toBe(false);expect(button(tree,'Confirm quoted amount and start').props.disabled).toBe(true);(oldCheckbox.props.onChange as (event:unknown)=>void)({target:{checked:true}});expect(quoteCheckbox(render()).props.checked).toBe(false);const calls=fetcher.mock.calls.length;(oldConfirm.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls).toHaveLength(calls)})
it('a quote that expires after rendering cannot dispatch its retained confirmation callback',async()=>{let tree=await start();affirm(tree);tree=render();const confirm=button(tree,'Confirm quoted amount and start'),calls=fetcher.mock.calls.length,clock=vi.spyOn(Date,'now').mockReturnValue(Date.parse(quote.expires_at)+1);try{(confirm.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls).toHaveLength(calls);expect(button(render(),'Confirm quoted amount and start').props.disabled).toBe(true)}finally{clock.mockRestore()}(confirm.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls).toHaveLength(calls);expect(quoteCheckbox(render()).props.checked).toBe(false)})

// These render transitions precede passive effect cleanup, so retained task
// callbacks must use the existing synchronous boundary rather than stale state.
it.each(['disabled','owner','purpose'])('a %s render synchronously retires the previously confirmed task quote',async boundary=>{let tree=await start();affirm(tree);tree=render();const confirm=button(tree,'Confirm quoted amount and start'),check=quoteCheckbox(tree);if(boundary==='disabled')render(false);else if(boundary==='owner')render(true,id(99));else{purpose='premium';render()}const calls=fetcher.mock.calls.length;(check.props.onChange as (event:unknown)=>void)({target:{checked:true}});(confirm.props.onClick as ()=>void)();await settle();expect(fetcher.mock.calls).toHaveLength(calls)})

// The transport must retain the explicit original-card mode and reject aliases,
// unknown fields or a secret for another intent before exposing a live frame.
it('short original-card ticket retains exactly the verified confirmation mode',async()=>{
 task={...progress,state:'payment_pending',commitment_id:id(30),commitment_revision:1};restored.secondary=secondary;const base=fetcher.getMockImplementation()!;
 fetcher.mockImplementation((path:unknown,init?:RequestInit)=>String(path).endsWith('/return/continue')?Promise.resolve(Response.json({purpose:'task.short_hold.continue',commitment_id:id(30),commitment_revision:1,provider_intent_id:'pi_original',client_secret:'pi_original_secret_TRANSIENT',expires_at:'2030-01-01T00:00:00.000Z',return_route_key:'account_payments',action_mode:'confirm_original_card',method_id:'pm_original'})):base(path,init));
 await start();(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle();expect(elements(render()).find(e=>e.type===HoldAuthentication)?.props.ticket).toMatchObject({action_mode:'confirm_original_card',method_id:'pm_original',provider_intent_id:'pi_original'});
})
it.each([{extra:true},{client_secret:'pi_foreign_secret_TRANSIENT'},{provider_intent_id:null},{expires_at:'invalid'},{action_mode:'confirm_original_card'},{action_mode:'confirm_original_card',method_id:'card_foreign'},{action_mode:'other',method_id:'pm_original'}])('short malformed continuation cannot mount %#',async delta=>{
 task={...progress,state:'payment_pending',commitment_id:id(30),commitment_revision:1};restored.secondary=secondary;const base=fetcher.getMockImplementation()!;
 fetcher.mockImplementation((path:unknown,init?:RequestInit)=>String(path).endsWith('/return/continue')?Promise.resolve(Response.json({purpose:'task.short_hold.continue',commitment_id:id(30),commitment_revision:1,provider_intent_id:'pi_original',client_secret:'pi_original_secret_TRANSIENT',expires_at:'2030-01-01T00:00:00.000Z',return_route_key:'account_payments',...delta})):base(path,init));
 await start();(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle();expect(elements(render()).some(e=>e.type===HoldAuthentication)).toBe(false);
})

// Exercise the actual confirmation callback and canonical reread. The SDK frame
// must disappear while the owned backing result remains a persistent live status.
it('canonical short-hold reread announces pending after the transient confirmation frame is removed',async()=>{
 task={...progress,state:'payment_pending',commitment_id:id(30),commitment_revision:1};restored.secondary=secondary;
 let backing='requires_action';const original=fetcher.getMockImplementation()!;
 fetcher.mockImplementation((path:unknown,init?:RequestInit)=>String(path).endsWith('/hold')?Promise.resolve(Response.json({result:{short_hold_contract_version:1,commitment_id:id(30),commitment_revision:1,task:null,backing_state:backing,capture_before:null,original_intent_known:true,continuation_available:backing==='requires_action'},error_code:null})):original(path,init));
 await start();(button(render(),'Continue original authentication').props.onClick as ()=>void)();await settle();
 const frame=elements(render()).find(e=>e.type===HoldAuthentication)!;expect(frame).toBeDefined();const calls=fetcher.mock.calls.length;backing='payment_pending';
 await(frame.props.onConfirmed as ()=>Promise<void>)();await settle();const tree=render();
 expect(elements(tree).some(e=>e.type===HoldAuthentication)).toBe(false);
 const status=elements(tree).find(e=>e.type==='p'&&text(e.props.children)==='Authorization outcome pending')!;
 expect(status.props).toMatchObject({role:'status','aria-live':'polite','aria-atomic':'true'});
 expect(button(tree,'Continue original authentication').props.disabled).toBe(true);
 expect(text(tree)).toContain('Waiting for verified backing');expect(text(tree)).not.toContain('Started with a verified hold');
 const canonical=fetcher.mock.calls.slice(calls);expect(canonical.length).toBeGreaterThan(0);expect(canonical.every(([,init])=>(init?.method??'GET')==='GET')).toBe(true);
 expect(canonical.some(([path])=>String(path).endsWith('/hold'))).toBe(true);expect(canonical.some(([path])=>String(path).endsWith('/current'))).toBe(true);
 expect(canonical.some(([path])=>/prepare|execute|return/.test(String(path)))).toBe(false);
})
