// Behavior requirements separate server quotes/current backing from browser
// confirmation and preserve immutable original operation receipts during recovery.
import { expect, it } from 'vitest'
import { audCents, financialProgressLabel, FinancialOperation, financialReceipt, currentPremium, safeCheckoutUrl } from '../lib/payments/financial-ui-model'
it('parses independent whole cents without rounding floating input',()=>{expect(audCents('1.00')).toBe(100);expect(audCents('50')).toBe(5000);for(const v of ['0.99','50.01','1.001','1e1','-1','NaN',''])expect(audCents(v)).toBeNull()})
it('customer action cannot imply task start or backing',()=>{expect(financialProgressLabel({state:'payment_pending',funding_state:null})).toBe('Waiting for verified backing');expect(financialProgressLabel({state:'active',funding_state:'active_unsecured'})).toBe('Started without reserved funds');expect(financialProgressLabel({state:'active',funding_state:'authorized'})).toBe('Started with a verified hold')})
it('preserves the original receipt while current resource advances and refuses changed originals',()=>{const original={operation_id:'original',status:'pending',result:{state:'payment_pending'}};const operation=new FinancialOperation('original','task.admit');operation.record(original);operation.record({...original});expect(operation.original).toEqual(original);expect(()=>operation.record({...original,status:'completed'})).toThrow();expect(()=>operation.record({...original,operation_id:'replacement'})).toThrow()})
it('entitlement expires and never follows active subscription/browser return alone',()=>{const entitlement={tier:'premium',provider_verified:true,effective_until:'2030-01-01T00:00:00.000Z',cap_configuration_id:'original',cap_configuration_revision:1,revision:1};expect(currentPremium(entitlement,0)).toBe(true);expect(currentPremium({...entitlement,provider_verified:false},0)).toBe(false);expect(currentPremium(entitlement,Date.parse(entitlement.effective_until))).toBe(false);expect(currentPremium({tier:'active'},0)).toBe(false)})
it('Checkout transport rejects invented external URLs and query secrets',()=>{expect(safeCheckoutUrl('https://checkout.stripe.com/c/pay/cs_test_original#fid')).toBe(true);for(const url of ['https://evil.example/c/pay/cs_x','https://checkout.stripe.com.evil/c/pay/cs_x','http://checkout.stripe.com/c/pay/cs_x','https://checkout.stripe.com/c/pay/cs_x?client_secret=x','https://user@checkout.stripe.com/c/pay/cs_x'])expect(safeCheckoutUrl(url)).toBe(false)})

// Read-only status vocabulary cannot mint paid intervals, provider facts or new
// mutation selectors. The same exact original receipt guards remain exercised.
it.each(['past_due','unpaid','paused','canceled','cancel_scheduled'])('ordinary %s projection retains exact paid history and rejects provider/inventory hints',state=>{const sub={subscription_id:'00000000-0000-0000-0000-000000000070',revision:4,plan_key:'monthly',state,paid_through:'2030-01-01T00:00:00.000Z',cancel_at_period_end:state==='cancel_scheduled',checkout_url:null},receipt={subscription_contract_version:1,operation_id:null,operation_revision:null,resource_revision:4,status:'completed',result:sub,error_code:null,retry_after_seconds:null};expect(financialReceipt('premium.read',receipt).result).toEqual(sub);expect(currentPremium(sub)).toBe(false);for(const field of ['method_inventory_complete','remaining_dependency','provider_verified','customer_id'])expect(()=>financialReceipt('premium.read',{...receipt,result:{...sub,[field]:true}})).toThrow();expect(()=>financialReceipt('premium.read',{...receipt,resource_revision:3})).toThrow()})
