// Execute the actual owner-keyed component with a dependency-aware hook host.
// Fixed response fixtures exercise stale callbacks without network/provider work.
import {beforeEach,expect,it,vi} from 'vitest'
const hooks=vi.hoisted(()=>({states:[] as unknown[],cursor:0,effects:[] as (()=>unknown)[],deps:[] as unknown[][]}))
vi.mock('react',()=>({useState:(v:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]=v;return [hooks.states[i],(n:unknown)=>{hooks.states[i]=typeof n==='function'?(n as (previous:unknown)=>unknown)(hooks.states[i]):n}]},useRef:(v:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]={current:v};return hooks.states[i]},useCallback:(fn:unknown)=>{hooks.cursor++;return fn},useEffect:(fn:()=>unknown,deps:unknown[])=>{const i=hooks.cursor++;if(!hooks.deps[i]||deps.some((v,n)=>typeof v!=='function'&&v!==hooks.deps[i][n])){hooks.deps[i]=deps;hooks.effects.push(fn)}}}))
import LongCollectionRecovery from '../components/account/LongCollectionRecovery'
import HoldAuthentication from '../components/account/HoldAuthentication'
type Element={type:unknown;props:Record<string,unknown>}
const owner='11111111-1111-4111-8111-111111111111',commitment='22222222-2222-4222-8222-222222222222'
let fetcher:ReturnType<typeof vi.fn>
function elements(v:unknown):Element[]{if(Array.isArray(v))return v.flatMap(elements);if(!v||typeof v!=='object'||!('props'in v))return [];const e=v as Element;return [e,...elements(e.props.children)]}
function text(v:unknown):string{if(Array.isArray(v))return v.map(text).join(' ');if(typeof v==='string')return v;if(v&&typeof v==='object'&&'props'in v)return text((v as Element).props.children);return ''}
function render(enabled=true,id=owner,selected=commitment){hooks.cursor=0;return LongCollectionRecovery({enabled,ownerId:id,commitmentId:selected,commitmentRevision:1,publishableKey:'pk_test_fixture'})}
async function settle(){for(let i=0;i<5;i++)await new Promise(r=>setTimeout(r,0))}
const click=(tree:unknown,label:string)=>{const b=elements(tree).find(e=>e.type==='button'&&text(e.props.children)===label)!;(b.props.onClick as ()=>void)()}
beforeEach(()=>{hooks.states=[];hooks.deps=[];hooks.effects=[];fetcher=vi.fn(async(path:string)=>Response.json(path.endsWith('/return/continue')?{purpose:'task.long_collection.continue',commitment_id:commitment,commitment_revision:1,provider_intent_id:'pi_original',client_secret:'pi_original_secret_TRANSIENT',expires_at:new Date(Date.now()+30000).toISOString(),return_route_key:'account_payments'}:path.endsWith('/progress')?{collection_state:'requires_action',continuation_available:true,original_intent_known:true}:{state:'ready'}));vi.stubGlobal('fetch',fetcher)})
async function ready(){let tree=render();for(const f of hooks.effects.splice(0))f();click(tree,'Check original payment');await settle();tree=render();click(tree,'Resume authentication');await settle();return render()}
it('closed UI exposes truthful unavailable copy and does no request',()=>{expect(text(render(false))).toContain('Payment recovery is currently unavailable.');expect(fetcher).not.toHaveBeenCalled()})
it('actual original collection frame uses shared next-action controller and human payment labels',async()=>{const tree=await ready(),frame=elements(tree).find(e=>e.type===HoldAuthentication)!;expect(frame.props.kind).toBe('collection');expect(frame.props.ticket).toMatchObject({client_secret:'pi_original_secret_TRANSIENT'});expect(text(tree)).not.toContain(commitment);expect(fetcher.mock.calls.map(([p])=>p)).toEqual(['prepare','progress','prepare','progress','return/issue','return/continue'].map(path=>'/api/account/collections/by-commitment/'+commitment+'/1/'+path))})
it('synchronous owner/enable changes remove old ticket and fence retained old callbacks',async()=>{const tree=await ready(),old=elements(tree).find(e=>e.type===HoldAuthentication)!;expect(elements(render(true,commitment)).some(e=>e.type===HoldAuthentication)).toBe(false);const count=fetcher.mock.calls.length;await(old.props.onConfirmed as ()=>Promise<void>)();(old.props.onExpired as ()=>void)();expect(fetcher.mock.calls).toHaveLength(count);expect(elements(render(false)).some(e=>e.type===HoldAuthentication)).toBe(false)})
it('old challenge callbacks cannot clear a newer original read ticket',async()=>{const old=elements(await ready()).find(e=>e.type===HoldAuthentication)!;click(render(),'Resume authentication');await settle();const current=elements(render()).find(e=>e.type===HoldAuthentication)!,count=fetcher.mock.calls.length;(old.props.onExpired as ()=>void)();await(old.props.onConfirmed as ()=>Promise<void>)();expect(fetcher.mock.calls).toHaveLength(count);expect(elements(render()).find(e=>e.type===HoldAuthentication)?.props.ticket).toBe(current.props.ticket)})

it('independent retained callback after terminal expiry cannot perform recovery read',async()=>{const old=elements(await ready()).find(e=>e.type===HoldAuthentication)!;const count=fetcher.mock.calls.length;(old.props.onExpired as ()=>void)();expect(text(render())).toContain('Authentication expired.');await(old.props.onConfirmed as ()=>Promise<void>)();expect(fetcher.mock.calls).toHaveLength(count)})

// A terminal frame can remain referenced by external async work; retiring its
// exact object must also fence the reply of an already-started progress read.
it('expiry during confirmed progress prevents late state installation',async()=>{const old=elements(await ready()).find(e=>e.type===HoldAuthentication)!;let release!:(v:Response)=>void;fetcher.mockImplementationOnce(()=>new Promise<Response>(resolve=>{release=resolve}));const pending=(old.props.onConfirmed as ()=>Promise<void>)();(old.props.onExpired as ()=>void)();release(Response.json({collection_state:'settled',continuation_available:false,original_intent_known:true}));await pending;expect(text(render())).toContain('Authentication expired.');expect(text(render())).not.toContain('Payment verified')})
it('successful confirmation refreshes verified progress once and retires duplicate callbacks',async()=>{const old=elements(await ready()).find(e=>e.type===HoldAuthentication)!;fetcher.mockImplementationOnce(async()=>Response.json({collection_state:'settled',continuation_available:false,original_intent_known:true}));await(old.props.onConfirmed as ()=>Promise<void>)();expect(text(render())).toContain('Payment verified');expect(elements(render()).some(e=>e.type===HoldAuthentication)).toBe(false);const count=fetcher.mock.calls.length;await(old.props.onConfirmed as ()=>Promise<void>)();(old.props.onExpired as ()=>void)();expect(fetcher.mock.calls).toHaveLength(count);expect(text(render())).toContain('Payment verified')})
it('expiry permits explicit recovery and an old callback cannot retire the resumed ticket',async()=>{const old=elements(await ready()).find(e=>e.type===HoldAuthentication)!;(old.props.onExpired as ()=>void)();click(render(),'Resume authentication');await settle();const resumed=elements(render()).find(e=>e.type===HoldAuthentication)!;expect(resumed).toBeTruthy();const count=fetcher.mock.calls.length;(old.props.onExpired as ()=>void)();await(old.props.onConfirmed as ()=>Promise<void>)();expect(fetcher.mock.calls).toHaveLength(count);expect(elements(render()).find(e=>e.type===HoldAuthentication)?.props.ticket).toBe(resumed.props.ticket)})

it('retained old selection action and challenge callbacks do not dispatch into a new commitment',async()=>{const old=await ready(),frame=elements(old).find(e=>e.type===HoldAuthentication)!,prior=fetcher.mock.calls.length,next='33333333-3333-4333-8333-333333333333';let current=render(true,owner,next);expect(elements(current).some(e=>e.type===HoldAuthentication)).toBe(false);click(old,'Check original payment');await (frame.props.onConfirmed as ()=>Promise<void>)();expect(fetcher).toHaveBeenCalledTimes(prior);for(const effect of hooks.effects.splice(0))effect();click(current,'Check original payment');await settle();current=render(true,owner,next);expect(fetcher.mock.calls.slice(prior).map(([path])=>path)).toEqual(['prepare','progress'].map(path=>'/api/account/collections/by-commitment/'+next+'/1/'+path))})

// Pending feedback follows the mounted selection; the same locked action cannot
// be submitted again while its original read or provider-confirmation read runs.
it('pending original progress disables both controls and announces the read',async()=>{await ready();let release!:(v:Response)=>void;fetcher.mockImplementationOnce(()=>new Promise<Response>(resolve=>{release=resolve}));click(render(),'Check original payment');const pending=render(),controls=elements(pending).filter(e=>e.type==='button');expect(controls.every(e=>e.props.disabled===true)).toBe(true);expect(pending.props['aria-busy']).toBe(true);expect(text(pending)).toContain('Checking original payment…');const count=fetcher.mock.calls.length;click(pending,'Resume authentication');expect(fetcher).toHaveBeenCalledTimes(count);release(Response.json({state:'ready'}));await settle();expect(render().props['aria-busy']).toBe(false);expect(elements(render()).filter(e=>e.type==='button').every(e=>e.props.disabled===false)).toBe(true)})
it('pending confirmation prevents competing actions and expiry releases the visible lock',async()=>{const frame=elements(await ready()).find(e=>e.type===HoldAuthentication)!;let release!:(v:Response)=>void;fetcher.mockImplementationOnce(()=>new Promise<Response>(resolve=>{release=resolve}));const pending=(frame.props.onConfirmed as ()=>Promise<void>)();const tree=render();expect(tree.props['aria-busy']).toBe(true);expect(elements(tree).filter(e=>e.type==='button').every(e=>e.props.disabled===true)).toBe(true);const count=fetcher.mock.calls.length;click(tree,'Check original payment');expect(fetcher).toHaveBeenCalledTimes(count);(frame.props.onExpired as ()=>void)();expect(render().props['aria-busy']).toBe(false);release(Response.json({collection_state:'settled',continuation_available:false,original_intent_known:true}));await pending;expect(text(render())).toContain('Authentication expired.');expect(text(render())).not.toContain('Payment verified')})
it('new owner or commitment hides the previous verified status and continuation before effects',async()=>{const frame=elements(await ready()).find(e=>e.type===HoldAuthentication)!;fetcher.mockImplementationOnce(async()=>Response.json({collection_state:'settled',continuation_available:false,original_intent_known:true}));await(frame.props.onConfirmed as ()=>Promise<void>)();expect(text(render())).toContain('Payment verified');for(const tree of [render(true,commitment),render(true,owner,'33333333-3333-4333-8333-333333333333')]){expect(text(tree)).not.toContain('Payment verified');expect(text(tree)).toContain('Check the original payment progress.');expect(elements(tree).some(e=>e.type==='button'&&text(e.props.children)==='Resume authentication')).toBe(false)}})
