// Execute the real challenge component with bounded in-memory Stripe ports and
// dependency-aware React hooks. No provider, browser or money effects occur.
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
const hooks=vi.hoisted(()=>({states:[] as unknown[],cursor:0,deps:[] as unknown[][],effects:[] as (()=>unknown)[],cleanups:[] as (()=>unknown)[]}))
const sdk=vi.hoisted(()=>({load:vi.fn(),next:vi.fn(),confirm:vi.fn()}))
vi.mock('../lib/payments/stripe-elements',()=>({loadPaymentStripe:sdk.load}))
vi.mock('react',()=>({useState:(v:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]=v;return [hooks.states[i],(n:unknown)=>{hooks.states[i]=typeof n==='function'?(n as (old:unknown)=>unknown)(hooks.states[i]):n}]},useRef:(v:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]={current:v};return hooks.states[i]},useEffect:(fn:()=>unknown,deps:unknown[])=>{const i=hooks.cursor++;if(!hooks.deps[i]||deps.some((v,n)=>v!==hooks.deps[i][n])){hooks.deps[i]=deps;hooks.effects.push(()=>{hooks.cleanups[i]?.();const c=fn();hooks.cleanups[i]=typeof c==='function'?c as ()=>unknown:()=>{}})}}}))
import HoldAuthentication from '../components/account/HoldAuthentication'
type Element={type:unknown;props:Record<string,unknown>}
function elements(v:unknown):Element[]{if(Array.isArray(v))return v.flatMap(elements);if(!v||typeof v!=='object'||!('props'in v))return [];const e=v as Element;return [e,...elements(e.props.children)]}
function text(v:unknown):string{if(Array.isArray(v))return v.map(text).join(' ');if(typeof v==='string')return v;if(v&&typeof v==='object'&&'props'in v)return text((v as Element).props.children);return ''}
const base={purpose:'task.short_hold.continue' as const,commitment_id:'11111111-1111-4111-8111-111111111111',commitment_revision:1,provider_intent_id:'pi_original',client_secret:'pi_original_secret_TRANSIENT',expires_at:new Date(Date.now()+60000).toISOString(),return_route_key:'account_payments' as const},explicit={...base,action_mode:'confirm_original_card' as const,method_id:'pm_original'}
let ticket:typeof base|typeof explicit,confirmed:ReturnType<typeof vi.fn>,expired:ReturnType<typeof vi.fn>,ownerCurrent:boolean,kind:'hold'|'collection'
const isCurrent=()=>ownerCurrent
function render(){hooks.cursor=0;return HoldAuthentication({ticket,publishableKey:'pk_test_fixture',onConfirmed:confirmed,onExpired:expired,kind,isCurrent})}
async function ready(){render();for(const f of hooks.effects.splice(0))f();await Promise.resolve();await Promise.resolve();return render()}
function submit(tree:unknown){return ((tree as Element).props.onSubmit as (event:unknown)=>Promise<void>)({preventDefault(){}})}
function check(tree:unknown,checked=true){const c=elements(tree).find(e=>e.type==='input'&&e.props.type==='checkbox');expect(c).toBeDefined();(c!.props.onChange as (event:unknown)=>void)({target:{checked}})}
const button=(tree:unknown)=>elements(tree).find(e=>e.type==='button')!
beforeEach(()=>{hooks.states=[];hooks.cursor=0;hooks.deps=[];hooks.effects=[];hooks.cleanups=[];ticket=explicit;kind='hold';ownerCurrent=true;confirmed=vi.fn(async()=>{});expired=vi.fn();sdk.next.mockReset().mockResolvedValue({paymentIntent:{status:'requires_capture'}});sdk.confirm.mockReset().mockResolvedValue({paymentIntent:{status:'requires_capture'}});sdk.load.mockReset().mockResolvedValue({handleNextAction:sdk.next,confirmCardPayment:sdk.confirm})})
afterEach(()=>{for(const c of hooks.cleanups)c?.();vi.restoreAllMocks()})
it.each(['hold','collection'] as const)('explicit %s confirmation requires current affirmation and never runs on load',async purpose=>{kind=purpose;let tree=await ready();expect(sdk.confirm).not.toHaveBeenCalled();expect(sdk.next).not.toHaveBeenCalled();expect(button(tree).props.disabled).toBe(true);await submit(tree);expect(sdk.confirm).not.toHaveBeenCalled();expect(text(tree)).toContain('original task card');check(tree);tree=render();expect(button(tree).props.disabled).toBe(false);await submit(tree);expect(sdk.confirm.mock.calls).toEqual([[explicit.client_secret,{payment_method:'pm_original'}]]);expect(sdk.next).not.toHaveBeenCalled();expect(confirmed).toHaveBeenCalledTimes(1);expect(text(render())).not.toContain('Payment verified')})
it('old seven-field next-action path requires a click and retains exact SDK arguments',async()=>{ticket=base;const tree=await ready();expect(elements(tree).some(e=>e.type==='input')).toBe(false);expect(sdk.next).not.toHaveBeenCalled();await submit(tree);expect(sdk.next.mock.calls).toEqual([[{clientSecret:base.client_secret}]]);expect(sdk.confirm).not.toHaveBeenCalled();expect(confirmed).toHaveBeenCalledTimes(1)})
it('unchecking current affirmation retires a retained affirmative submit callback',async()=>{let tree=await ready();check(tree);tree=render();check(tree,false);await submit(tree);expect(sdk.confirm).not.toHaveBeenCalled()})
it.each(['success','error','throw'] as const)('ticket permits one synchronous attempt even after %s or duplicate retained submits',async outcome=>{if(outcome==='error')sdk.confirm.mockResolvedValue({error:{message:'RAW_PRIVATE_ERROR'}});if(outcome==='throw')sdk.confirm.mockRejectedValue(new Error('RAW_PRIVATE_ERROR'));let tree=await ready();check(tree);tree=render();await Promise.all([submit(tree),submit(tree)]);await submit(render());expect(sdk.confirm).toHaveBeenCalledTimes(1);expect(text(render())).not.toContain('RAW_PRIVATE_ERROR');expect(confirmed).toHaveBeenCalledTimes(outcome==='success'?1:0)})
it.each(['owner','replacement','expiry','cleanup'] as const)('late SDK result after %s cannot invoke canonical recovery',async change=>{let release!:(v:unknown)=>void;sdk.confirm.mockImplementation(()=>new Promise(resolve=>{release=resolve}));let tree=await ready();check(tree);tree=render();const pending=submit(tree);if(change==='owner')ownerCurrent=false;else if(change==='replacement'){ticket={...explicit,client_secret:'pi_original_secret_NEW'};render()}else if(change==='expiry')vi.spyOn(Date,'now').mockReturnValue(Date.parse(base.expires_at));else for(const c of hooks.cleanups)c?.();release({paymentIntent:{status:'succeeded'}});await pending;expect(confirmed).not.toHaveBeenCalled();expect(text(render())).not.toContain('Payment verified')})
it('replacement ticket before effect cleanup blocks old submit and old affirmation',async()=>{let tree=await ready();check(tree);tree=render();const old=tree;ticket={...explicit,client_secret:'pi_original_secret_NEW'};render();check(old);await submit(old);expect(sdk.confirm).not.toHaveBeenCalled();tree=await ready();expect(button(tree).props.disabled).toBe(true);check(tree);await submit(render());expect(sdk.confirm.mock.calls).toEqual([['pi_original_secret_NEW',{payment_method:'pm_original'}]])})
it('owner change and expiry before submit withhold provider work',async()=>{let tree=await ready();check(tree);tree=render();ownerCurrent=false;await submit(tree);ownerCurrent=true;vi.spyOn(Date,'now').mockReturnValue(Date.parse(base.expires_at));await submit(tree);expect(sdk.confirm).not.toHaveBeenCalled()})

it('rerunning effects for the same consumed ticket cannot grant another provider attempt',async()=>{let tree=await ready();check(tree);await submit(render());expired=vi.fn();tree=await ready();check(tree);await submit(render());expect(sdk.confirm).toHaveBeenCalledTimes(1)})
