// Verify selection hashes and the real installed SDK serializer through the
// selected website executor. Synthetic owned responses grant no provider authority.
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {expect,it,vi} from 'vitest'
import selection from '../lib/payments/owned-card-joint-selection.json'
import {fixture,provision} from './fixtures/original-card-permit'
import {paymentRequestHash,type Permit} from '../lib/payments/owned-card-joint/supabase/functions/_shared/webPaymentProviderContractJoint'
import {executeProviderJoint} from '../lib/payments/owned-card-joint/supabase/functions/_shared/webPaymentProviderJoint'
import {guardedTransportJoint} from '../lib/payments/owned-card-joint/supabase/functions/_shared/webPaymentProviderClientJoint'
it('selected complete runtime matches final backend pins and leaves financial activation closed',()=>{expect(selection.runtime).toHaveLength(30);expect(selection.backendFreezeSha256).toBe('8fdb2ee78fe66a70d2705b2aa7e29ca91b397cb2f8c4f25415573c5de846aa0a');expect(selection.activation).toBe(false);for(const pin of selection.runtime){const source=readFileSync('lib/payments/owned-card-joint/'+pin.path);expect(createHash('sha256').update(source).digest('hex')).toBe(pin.websiteSha256)}expect(readFileSync('lib/payments/website-source-gate.ts','utf8')).toMatch(/false/);})
// Capture uses an immutable original permit and charge. The same recording
// transport verifies exact full amount, omitted optional flag and one POST.
it('actual selected executor serializes one original full capture without optional final_capture',async()=>{
 const p=fixture('setup.create') as Permit,now=Date.now();p.kind='authorization.capture';p.parent_action='task.collect';p.purpose='task.failure_collection';p.object_kind='payment_intent';p.object_id='pi_original';p.provider_key=`ante:provider-v1:${p.subaction_id}:${p.kind}`;
 p.collection_configuration={configuration_id:crypto.randomUUID(),revision:1,provider_configuration_id:p.configuration_id,task_configuration_id:crypto.randomUUID(),approval_id:crypto.randomUUID(),approval_hash:'a'.repeat(64),terms_hash:'b'.repeat(64),country:'AU',currency:'aud',processing_buffer_seconds:60,collection_enabled:true,collection_policy:'definitive_failure_original_commitment',expired_policy:'unsecured_no_reauthorize',effective_at:new Date(now-1000).toISOString(),expires_at:new Date(now+3600000).toISOString(),quote_hash:'c'.repeat(64),start_id:crypto.randomUUID(),finality_id:crypto.randomUUID(),work_id:p.operation_id,eligibility_hash:'d'.repeat(64),original_operation_id:crypto.randomUUID(),original_subaction_id:crypto.randomUUID(),continuation_adapter_version:null};p.parameters={customer:'cus_fixture',method_id:'pm_fixture',amount_minor:'1000',currency:'aud',quote_hash:'c'.repeat(64),payment_intent_id:'pi_original',metadata:{ante_operation:p.collection_configuration.original_operation_id,ante_commitment:p.subject_id}};p.parameter_hash=paymentRequestHash(p.parameters);
 const intent=(succeeded:boolean)=>({object:'payment_intent',id:'pi_original',customer:'cus_fixture',payment_method:'pm_fixture',livemode:false,amount:1000,amount_capturable:succeeded?0:1000,amount_received:succeeded?1000:0,currency:'aud',capture_method:'manual',confirmation_method:'automatic',metadata:p.parameters.metadata,allowed_payment_method_types:['card'],payment_method_types:['card'],payment_method_configuration_details:null,status:succeeded?'succeeded':'requires_capture',client_secret:'pi_original_secret_TRANSIENT',latest_charge:{object:'charge',id:'ch_original',payment_intent:'pi_original',customer:'cus_fixture',payment_method:'pm_fixture',amount:1000,currency:'aud',livemode:false,captured:succeeded,amount_captured:succeeded?1000:0,refunded:false,amount_refunded:0,paid:true,status:'succeeded',payment_method_details:{type:'card',card:{capture_before:Math.floor(now/1000)+3600}}}});
 const wire=vi.fn(async(_input:unknown,init?:RequestInit)=>Response.json(intent(init?.method==='POST'))),transport=guardedTransportJoint(wire);const result=await executeProviderJoint(p,provision(p),()=> 'synthetic-sdk-key',transport);await transport.quiescence();expect(result.outcome).toBe('verified');expect(wire).toHaveBeenCalledTimes(2);expect(wire.mock.calls[0][1]?.method).toBe('GET');expect(wire.mock.calls[1][1]?.method).toBe('POST');const body=new URLSearchParams(String(wire.mock.calls[1][1]?.body));expect(body.get('amount_to_capture')).toBe('1000');expect(body.has('final_capture')).toBe(false);expect(new Headers(wire.mock.calls[1][1]?.headers).get('idempotency-key')).toBe(p.provider_key);
})
