// Exercise the real website capsule adapter, selected repository, installed
// Stripe SDK and guarded GET transport with synthetic immutable owner evidence.
// These local responses grant no hosted, database or provider acceptance.
import {expect,it,vi} from 'vitest'
vi.mock('server-only',()=>({}))
import {continueFinancialReturn,type FinancialReturnOptions} from '../lib/server/financial-return'
import {fixture,provision} from './fixtures/original-card-permit'
import {paymentRequestHash,type Permit} from '../lib/payments/owned-card-joint/supabase/functions/_shared/webPaymentProviderContractJoint'
import {guardedTransportJoint} from '../lib/payments/owned-card-joint/supabase/functions/_shared/webPaymentProviderClientJoint'
import {SHORT_HOLD_CAPSULE_FIELDS,createShortHoldCapsule} from '../lib/payments/bridge-v3/scripts/backend/web-payment-short-hold-return-capsule.mjs'
import {LONG_COLLECTION_CAPSULE_FIELDS,createLongCollectionCapsule} from '../lib/payments/collection-v4/scripts/backend/web-payment-long-collection-return-capsule.mjs'
import type {FinancialOwner} from '../lib/server/financial-transport'
function setup(kind:'hold'|'collection',patch:Record<string,unknown>={},ack=true){
 const p=fixture('setup.create') as Permit,now=Date.now(),hold=kind==='hold';p.kind=hold?'authorization.create':'collection.create';p.parent_action=hold?'task.admit':'task.collect';p.purpose=hold?'task.short_hold':'task.failure_collection';p.object_kind='payment_intent';p.plan='retrieve';p.object_id='pi_original';p.provider_key=`ante:provider-v1:${p.subaction_id}:${p.kind}`;p.parameters={customer:'cus_fixture',method_id:'pm_original',amount_minor:'1000',currency:'aud',...(hold?{capture_method:'manual'}:{}),quote_hash:'a'.repeat(64),metadata:{ante_operation:p.operation_id,ante_commitment:p.subject_id}};p.parameter_hash=paymentRequestHash(p.parameters)
 const cfg={configuration_id:crypto.randomUUID(),revision:1,provider_configuration_id:p.configuration_id,task_configuration_id:crypto.randomUUID(),approval_id:crypto.randomUUID(),approval_hash:'a'.repeat(64),terms_hash:'b'.repeat(64),country:'AU' as const,currency:'aud' as const,processing_buffer_seconds:60,effective_at:new Date(now-1000).toISOString(),expires_at:new Date(now+3600000).toISOString(),quote_hash:'a'.repeat(64),expired_policy:'unsecured_no_reauthorize' as const}
 if(hold)p.hold_configuration={...cfg,cutoff_seconds:7200,authorization_enabled:true,release_policy:'definitive_success_original_intent',task_created_at:new Date(now).toISOString(),original_due_at:new Date(now+3600000).toISOString(),authorization_operation_id:p.operation_id,authorization_subaction_id:p.subaction_id,continuation_adapter_version:'short_hold_return_v1'}
 else p.collection_configuration={...cfg,collection_enabled:true,collection_policy:'definitive_failure_original_commitment',start_id:crypto.randomUUID(),finality_id:crypto.randomUUID(),work_id:p.operation_id,eligibility_hash:'b'.repeat(64),original_operation_id:p.operation_id,original_subaction_id:p.subaction_id,continuation_adapter_version:'long_collection_return_v1'}
 const ticket={ticket_id:crypto.randomUUID(),owner_id:p.owner_id,commitment_id:p.subject_id,commitment_revision:p.subject_revision,subaction_id:p.subaction_id,operation_revision:p.operation_revision,observation_id:crypto.randomUUID(),lease_generation:p.lease_generation,provider_intent_id:p.object_id,transport_approval_id:crypto.randomUUID(),created_at:new Date(now-100).toISOString(),expires_at:p.lease_expires_at},m:Record<string,unknown>={}
 for(const field of hold?SHORT_HOLD_CAPSULE_FIELDS:LONG_COLLECTION_CAPSULE_FIELDS)m[field]=field.endsWith('_id')?crypto.randomUUID():field.endsWith('_revision')?1:field.endsWith('_hash')||field==='browser_digest'?'a'.repeat(64):null
 Object.assign(m,{nonce_base64url:Buffer.alloc(32,7).toString('base64url'),owner_id:p.owner_id,original_namespace:hold?'hold_v1':'collection_v1',original_action:hold?'task.short_hold.continue':'task.long_collection.continue',begin_operation_id:p.operation_id,begin_operation_revision:p.operation_revision,commitment_id:p.subject_id,commitment_revision:p.subject_revision,provider_intent_id:p.object_id,customer_id:p.customer_id,customer_provider_revision:p.customer_revision,consent_id:p.consent_id,provider_configuration_id:p.configuration_id,provider_configuration_revision:p.configuration.revision,provider_configuration_hash:p.configuration_hash,[hold?'hold_configuration_id':'collection_configuration_id']:cfg.configuration_id,[hold?'hold_configuration_revision':'collection_configuration_revision']:1,[hold?'hold_configuration_hash':'collection_configuration_hash']:paymentRequestHash(hold?p.hold_configuration:p.collection_configuration),created_at_unix_microseconds:String(BigInt(now-100)*1000n),expires_at_unix_microseconds:String(BigInt(Date.parse(ticket.expires_at))*1000n)})
 const key=new Uint8Array(32).fill(9),capsule=(hold?createShortHoldCapsule:createLongCollectionCapsule)(m,key),lineage={ownerId:p.owner_id,operationId:p.operation_id,browserDigest:String(m.browser_digest),returnAdmissionId:String(m.return_admission_id),capsule:capsule.token,install(){throw Error('unexpected install')}}
 const read=vi.fn(async()=>({metadata:m,capability_digest:'b'.repeat(64),original_return_admission_id:m.return_admission_id})),consume=vi.fn(async()=>ack),fresh=vi.fn(async()=>{}),wire=vi.fn(async()=>Response.json({object:'payment_intent',id:'pi_original',customer:'cus_fixture',livemode:false,amount:1000,amount_received:0,amount_capturable:0,currency:'aud',capture_method:hold?'manual':'automatic',confirmation_method:'automatic',metadata:p.parameters.metadata,allowed_payment_method_types:['card'],payment_method_types:['card'],payment_method_configuration_details:null,status:'requires_payment_method',payment_method:null,latest_charge:null,client_secret:'pi_original_secret_TRANSIENT',last_payment_error:{type:'card_error',code:'authentication_required',payment_method:{id:'pm_original',object:'payment_method',customer:'cus_fixture',livemode:false,type:'card'}},...patch})),transport=guardedTransportJoint(wire)
 const options={provider:{provision:provision(p),credential:()=> 'synthetic-sdk-key',transport},loadKey:async()=>key,services:{secret:()=>({read:async()=>({permit:p,ticket})})}} as unknown as FinancialReturnOptions,owner={read,consume,fresh} as unknown as FinancialOwner
 return {p,ticket,m,lineage,options,owner,wire,consume,fresh}
}
it.each(['hold','collection'] as const)('actual website %s return emits only the new verified nine-field action',async kind=>{const x=setup(kind),out=await continueFinancialReturn(x.options,x.owner,kind,x.lineage,()=>{});expect(out).toEqual({purpose:kind==='hold'?'task.short_hold.continue':'task.long_collection.continue',commitment_id:x.p.subject_id,commitment_revision:1,provider_intent_id:'pi_original',client_secret:'pi_original_secret_TRANSIENT',expires_at:x.ticket.expires_at,return_route_key:'account_payments',action_mode:'confirm_original_card',method_id:'pm_original'});expect(x.wire).toHaveBeenCalledTimes(1);expect(x.wire.mock.calls[0]).toBeDefined();expect(x.consume).toHaveBeenCalledTimes(1)})
it.each(['hold','collection'] as const)('actual website %s preserves exact seven-field requires_action delivery',async kind=>{const x=setup(kind,{status:'requires_action',payment_method:'pm_original',last_payment_error:null}),out=await continueFinancialReturn(x.options,x.owner,kind,x.lineage,()=>{});expect(Object.keys(out!).sort()).toEqual(['purpose','commitment_id','commitment_revision','provider_intent_id','client_secret','expires_at','return_route_key'].sort());expect(x.consume).toHaveBeenCalledTimes(1)})
it.each(['hold','collection'] as const)('actual website %s withholds secret after lost final owner ACK',async kind=>{const x=setup(kind,{},false);await expect(continueFinancialReturn(x.options,x.owner,kind,x.lineage,()=>{})).rejects.toThrow();expect(x.consume).toHaveBeenCalledTimes(1)})
it.each(['hold','collection'] as const)('actual website %s refuses money, foreign original-card/error, missing card and mismatched secret',async kind=>{for(const patch of [{amount_received:1},{amount_capturable:1},{payment_method:'pm_foreign'},{last_payment_error:null},{last_payment_error:{type:'card_error',code:'authentication_required'}},{last_payment_error:{type:'card_error',code:'authentication_required',payment_method:{id:'pm_foreign',object:'payment_method',customer:'cus_fixture',livemode:false,type:'card'}}},{client_secret:'pi_foreign_secret_TRANSIENT'},{payment_method_configuration_details:{id:'pmc_fixture'}}]){const x=setup(kind,patch);await expect(continueFinancialReturn(x.options,x.owner,kind,x.lineage,()=>{})).rejects.toThrow();expect(x.consume).not.toHaveBeenCalled()}})
it.each(['hold','collection'] as const)('actual website %s original capsule refuses a refreshed foreign/revised capability before SDK',async kind=>{for(const alter of [(p:Permit)=>{p.owner_id=crypto.randomUUID()},(p:Permit)=>{p.subject_revision++},(p:Permit)=>{p.customer_revision++},(p:Permit)=>{p.configuration.revision++;p.configuration_hash=paymentRequestHash(p.configuration)}]){const x=setup(kind);alter(x.p);await expect(continueFinancialReturn(x.options,x.owner,kind,x.lineage,()=>{})).rejects.toThrow();expect(x.wire).not.toHaveBeenCalled()}})
