// Bundle the real server entry imports to prove that reachable continuations,
// transports and dormant card work use only the selected Joint provider engine.
// External dependencies remain external and no server/config/provider is run.
import {createRequire} from 'node:module'
import {resolve} from 'node:path'
import {expect,it,vi} from 'vitest'
vi.mock('server-only',()=>({}))
import {fixture,provision} from './fixtures/original-card-permit'
import {runPaymentProviderWork} from '../lib/payments/bridge-v1/supabase/functions/_shared/webPaymentProviderRunner'
import {guardedTransportJoint} from '../lib/payments/owned-card-joint/supabase/functions/_shared/webPaymentProviderClientJoint'
import type {PaymentSupabase} from '../lib/payments/bridge-v1/supabase/functions/_shared/webPaymentBrowserRepository'
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler')),bundler=wranglerRequire('esbuild')
it('real local provider imports select Joint and leave every historical engine unreachable',async()=>{const built=await bundler.build({entryPoints:[resolve('lib/server/payment-bridge.ts'),resolve('lib/server/financial-bridge.ts'),resolve('lib/server/financial-return.ts')],outdir:'/private/tmp/ante-owned-card-unused-bundle',bundle:true,write:false,format:'esm',platform:'node',packages:'external',metafile:true});const inputs=Object.keys(built.metafile.inputs);expect(inputs.some(p=>p.endsWith('/webPaymentProviderJoint.ts'))).toBe(true);expect(inputs.filter(p=>/\/webPaymentProvider(?:V[23456])?\.ts$/.test(p))).toEqual([]);expect(inputs.filter(p=>/\/webPaymentProviderClient(?:V[23456])?\.ts$/.test(p))).toEqual([]);expect(inputs.filter(p=>/\/webPaymentProviderRepository(?:V[23456])?\.ts$/.test(p))).toEqual([])})
it('dormant card worker preserves fixed gateway tuple and uses supported card-only SDK schema',async()=>{const p=fixture('setup.create'),identity=crypto.randomUUID(),claim=vi.fn(async()=>({principal_id:identity,permits:[p]})),dispatch=vi.fn(async()=>true),observation=vi.fn(async()=>({status:'recorded'})),services={service:()=>({claim,dispatch,observation})} as unknown as PaymentSupabase,wire=vi.fn(async(_input,init)=>{const body=new URLSearchParams(String(init?.body??''));return Response.json(body.has('payment_method_configuration')?{error:{type:'invalid_request_error',param:'payment_method_configuration'}}:{object:'setup_intent',id:'seti_fixture',customer:'cus_fixture',livemode:false,usage:'off_session',payment_method:null,status:'requires_payment_method',allowed_payment_method_types:['card'],payment_method_types:['card'],payment_method_configuration_details:null,metadata:p.parameters.metadata},{status:body.has('payment_method_configuration')?400:200})}),transport=guardedTransportJoint(wire);const result=await runPaymentProviderWork(services,identity,1,provision(p),()=> 'synthetic-sdk-key',transport,()=>{});expect(result.claimed).toBe(1);expect(dispatch.mock.calls).toEqual([[{subaction_id:p.subaction_id,generation:p.lease_generation,operation_revision:p.operation_revision,plan:p.plan,object_id:null}]]);expect(observation).toHaveBeenCalledWith(expect.objectContaining({observation:expect.objectContaining({outcome:'pending',method_configuration:null})}));expect(wire).toHaveBeenCalledTimes(1);const body=new URLSearchParams(String(wire.mock.calls[0][1]?.body));expect(body.get('allowed_payment_method_types[0]')).toBe('card');expect(body.has('payment_method_configuration')).toBe(false)})
it('dormant card gateway refuses a noncard claim before dispatch, credentials or network',async()=>{const p={...fixture(),kind:'collection.create' as const},identity=crypto.randomUUID(),dispatch=vi.fn(),observation=vi.fn(),services={service:()=>({claim:async()=>({principal_id:identity,permits:[p]}),dispatch,observation})} as unknown as PaymentSupabase,key=vi.fn(()=> 'synthetic-sdk-key'),wire=vi.fn(),transport=guardedTransportJoint(wire);await expect(runPaymentProviderWork(services,identity,1,provision(p),key,transport,()=>{})).rejects.toThrow();expect(dispatch).not.toHaveBeenCalled();expect(key).not.toHaveBeenCalled();expect(wire).not.toHaveBeenCalled()})
