// Actual owner component regressions fence private rows across owner transitions
// and keep original recovery visible when the current task view cannot be read.
import {beforeEach,expect,it,vi} from 'vitest'
const hooks=vi.hoisted(()=>({states:[] as unknown[],cursor:0,effects:[] as (()=>unknown)[],deps:[] as unknown[][]}))
vi.mock('react',()=>({useState:(value:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]=value;return [hooks.states[i],(next:unknown)=>{hooks.states[i]=typeof next==='function'?(next as (old:unknown)=>unknown)(hooks.states[i]):next}]},useRef:(value:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]={current:value};return hooks.states[i]},useCallback:(fn:unknown)=>{hooks.cursor++;return fn},useEffect:(fn:()=>unknown,deps:unknown[])=>{const i=hooks.cursor++;if(!hooks.deps[i]||deps.some((d,n)=>typeof d!=='function'&&d!==hooks.deps[i][n])){hooks.deps[i]=deps;hooks.effects.push(fn)}}}))
import AccountPaymentReview from '../components/account/AccountPaymentReview'
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`
function text(v:unknown):string{if(Array.isArray(v))return v.map(text).join(' ').replace(/\s+/g,' ');if(typeof v==='string'||typeof v==='number')return String(v);if(v&&typeof v==='object'&&'props'in v)return text((v as {props:{children:unknown}}).props.children);return ''}
function render(owner=id(1),enabled=true){hooks.cursor=0;return AccountPaymentReview({enabled,ownerId:owner})}
async function flush(){for(const effect of hooks.effects.splice(0))effect();await new Promise(resolve=>setTimeout(resolve,0))}
beforeEach(()=>{hooks.states=[];hooks.deps=[];hooks.effects=[];hooks.cursor=0;vi.stubGlobal('fetch',vi.fn(async(input:string)=>input.endsWith('/intent')?{ok:true,json:async()=>({request_id:id(2),operation_id:id(3),action:'appeal'})}:{ok:false,status:409}))})
it('original recovery remains visible when task progress cannot be confirmed',async()=>{render();await flush();const output=text(render());expect(output).toContain('Original appeal');expect(output).toContain('Check original response');expect(output).toContain('Some information could not be confirmed');expect(output).not.toContain('Collection decision recorded')})
it('a new owner or disabled render hides previous private originals synchronously',async()=>{render();await flush();expect(text(render())).toContain('Original appeal');expect(text(render(id(99)))).not.toContain('Original appeal');expect(text(render(id(1),false))).toContain('currently unavailable');expect(text(render(id(1),false))).not.toContain('Original appeal')})
// Exercise actual choice/form callbacks with returning-owner projections. The
// browser selects evidence IDs only; server reconstructs original outcome IDs.
it('returning-owner choice displays existing proof selectors and submits selected original asset IDs',async()=>{
 let selected=false;const commitment=id(11),asset=id(12),calls:{path:string;body:Record<string,unknown>|null}[]=[],current={authority_kind:'financial-commitment-view-v1',commitment_id:commitment,task_id:id(13),revision:1,amount_minor:'100',currency:'AUD',started_at:'2026-10-08T00:00:00.000000Z',funding_state:'unknown',outcome:{authority_kind:'financial-ledger-binding-v1',outcome_id:id(14),outcome_revision:1,outcome_hash:'a'.repeat(64),outcome:'failed',proof_resolution_id:id(15),proof_resolution_revision:1,proof_resolution_hash:'b'.repeat(64)},cases:[],finality:null}
 vi.stubGlobal('fetch',vi.fn(async(path:string,options:{body?:string})=>{const body=options.body?JSON.parse(options.body):null;calls.push({path,body});let value:unknown;if(path.endsWith('/select')){selected=true;value=current}else if(path.endsWith('/commitments'))value={review_projection_version:1,items:[{commitment_id:commitment,task_id:id(13),revision:1,amount_minor:'100',currency:'AUD',started_at:current.started_at}],next_cursor:null};else if(path.endsWith('/intent'))value=null;else if(path.endsWith('/progress')){if(!selected)return {ok:false,status:409};value=current}else if(path.endsWith('/evidence'))value={review_projection_version:1,commitment_id:commitment,items:[{asset_id:asset,created_at:current.started_at}],next_cursor:null};else if(path.endsWith('/history'))value={items:[]};else if(path.endsWith('/prepare'))value={request_id:id(20),operation_id:id(21),action:'appeal'};else value={};return {ok:true,json:async()=>value}}))
 type Element={type:unknown;props:Record<string,unknown>}
 function elements(v:unknown):Element[]{if(Array.isArray(v))return v.flatMap(elements);if(!v||typeof v!=='object'||!('props'in v))return [];const e=v as Element;return [e,...elements(e.props.children)]}
 render();await flush();let tree=render();expect(text(tree)).toContain('Choose a recorded commitment');const choose=elements(tree).find(e=>e.type==='button'&&text(e)==='View commitment')!;(choose.props.onClick as ()=>void)();await flush();tree=render();expect(text(tree)).toContain('Attach existing proof evidence');const checkbox=elements(tree).find(e=>e.type==='input'&&e.props.type==='checkbox')!;(checkbox.props.onChange as (e:unknown)=>void)({target:{checked:true}});const reason=elements(tree).find(e=>e.type==='textarea')!;(reason.props.onChange as (e:unknown)=>void)({target:{value:'Please review this original proof'}});tree=render();const form=elements(tree).find(e=>e.type==='form')!;(form.props.onSubmit as (e:unknown)=>void)({preventDefault(){}});await flush();const prepared=calls.find(c=>c.path.endsWith('/prepare'));expect(prepared?.body).toMatchObject({reason:'Please review this original proof',asset_ids:[asset]});expect(prepared?.body).not.toHaveProperty('outcome_id');expect(calls.filter(c=>c.path.includes('upload'))).toHaveLength(0)
})
