// Actual notice callbacks fence late private replies and retained old actions.
import {beforeEach,it,expect,vi} from 'vitest'
const hooks=vi.hoisted(()=>({states:[] as unknown[],cursor:0,effects:[] as (()=>unknown)[],deps:[] as unknown[][]}))
vi.mock('react',()=>({useState:(value:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]=value;return [hooks.states[i],(next:unknown)=>{hooks.states[i]=typeof next==='function'?(next as (old:unknown)=>unknown)(hooks.states[i]):next}]},useRef:(value:unknown)=>{const i=hooks.cursor++;if(!(i in hooks.states))hooks.states[i]={current:value};return hooks.states[i]},useEffect:(fn:()=>unknown,deps:unknown[])=>{const i=hooks.cursor++;if(!hooks.deps[i]||deps.some((d,n)=>d!==hooks.deps[i][n])){hooks.deps[i]=deps;hooks.effects.push(fn)}}}))
import AccountPaymentNotices from '../components/account/AccountPaymentNotices'
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002'
function render(ownerId=a,enabled=true){hooks.cursor=0;return AccountPaymentNotices({ownerId,enabled})}
function text(v:unknown):string{if(Array.isArray(v))return v.map(text).join(' ');if(typeof v==='string')return v;if(v&&typeof v==='object'&&'props'in v)return text((v as {props:{children:unknown}}).props.children);return ''}
type Element={type:unknown;props:Record<string,unknown>}
function elements(v:unknown):Element[]{if(Array.isArray(v))return v.flatMap(elements);if(!v||typeof v!=='object'||!('props'in v))return [];const e=v as Element;return [e,...elements(e.props.children)]}
const button=(v:unknown)=>elements(v).find(e=>e.type==='button')!.props.onClick as ()=>void
async function flush(){for(const effect of hooks.effects.splice(0))effect();await new Promise(resolve=>setTimeout(resolve,0))}
beforeEach(()=>{hooks.states=[];hooks.deps=[];hooks.effects=[];hooks.cursor=0})
it('late A notice reply and retained A action cannot paint or fetch in B selection',async()=>{let finish:(v:unknown)=>void=()=>{};const fetcher=vi.fn(()=>new Promise(resolve=>{finish=resolve}));vi.stubGlobal('fetch',fetcher);const first=render();await flush();const old=button(first);old();render(b);expect(text(render(b))).not.toContain('pending');const count=fetcher.mock.calls.length;old();expect(fetcher).toHaveBeenCalledTimes(count);finish({ok:true,json:async()=>({notice_projection_version:1,items:[{notice_id:b,kind:'refund',status:'pending',recorded_at:'2026-10-08T00:00:00.000000Z'}],next_cursor:null})});await flush();expect(text(render(b))).not.toMatch(/Refund\s*:/)})
it('closed gate sends no read and ordinary pending notice remains truthful',async()=>{const fetcher=vi.fn(async()=>({ok:true,json:async()=>({notice_projection_version:1,items:[{notice_id:b,kind:'refund',status:'pending',recorded_at:'2026-10-08T00:00:00.000000Z'}],next_cursor:null})}));vi.stubGlobal('fetch',fetcher);const tree=render();await flush();const old=button(tree);render(a,false);old();expect(fetcher).not.toHaveBeenCalled();expect(text(render(a,false))).toContain('currently unavailable');render();button(render())();await flush();expect(text(render())).toMatch(/Refund\s*:/);expect(text(render())).toContain('pending');expect(text(render())).not.toContain('settled')})
