// Actual DTO regressions reject capability injection and preserve truthful state.
import {expect,it} from 'vitest'
import {ownerReview,ownerHistory,reviewStatus,reviewCommitments,reviewEvidence} from '../lib/payments/owner-review-model'
const id='00000000-0000-0000-0000-000000000001',time='2026-10-08T00:00:00.000000Z'
const view={authority_kind:'financial-commitment-view-v1',commitment_id:id,task_id:id,revision:1,amount_minor:'100',currency:'AUD',started_at:time,funding_state:'unknown',outcome:null,cases:[],finality:null}
it('unknown and silence never become settlement or collection authority',()=>{expect(reviewStatus(ownerReview(view,id))).toContain('do not authorize collection');expect(()=>ownerReview({...view,client_secret:'pi_secret'},id)).toThrow();expect(()=>ownerReview({...view,commitment_id:'00000000-0000-0000-0000-000000000002'},id)).toThrow();expect(()=>ownerReview({...view,amount_minor:'1.25'},id)).toThrow()})
it('a recorded finality is explicitly separate from completed settlement',()=>{const current=ownerReview({...view,finality:{finality_id:id,action:'collect',financial_dispatch:false}},id);expect(reviewStatus(current)).toContain('progress must be confirmed separately');expect(()=>ownerReview({...view,finality:{finality_id:id,action:'collect',financial_dispatch:true}},id)).toThrow()})
it('history is exact, ordered and bounded and cannot admit provider notice objects',()=>{const entry={identity:id,kind:'delivered_notice',occurred_at:time},history={commitment_contract_version:1,authority_kind:'financial-history-v1',items:[entry]};expect(ownerHistory(history,null)).toEqual([entry]);expect(()=>ownerHistory(history,id)).toThrow();expect(()=>ownerHistory({...history,items:[entry,entry]},null)).toThrow();expect(()=>ownerHistory({...history,items:Array(26).fill(entry)},null)).toThrow();expect(()=>ownerHistory({...history,items:[{...entry,provider_id:'dp_other'}]},null)).toThrow()})

it('returning-owner pages reject malformed/over-limit cursors, identity ordering and provider fields',()=>{const item={commitment_id:id,task_id:id,revision:1,amount_minor:'100',currency:'AUD',started_at:time},projection={review_projection_version:1,items:[item],next_cursor:null};expect(reviewCommitments(projection,null).items).toEqual([item]);expect(()=>reviewCommitments({...projection,next_cursor:id},null)).toThrow();expect(()=>reviewCommitments({...projection,items:[{...item,customer_id:'cus_other'}]},null)).toThrow();expect(()=>reviewCommitments({...projection,items:[item,item]},null)).toThrow();expect(()=>reviewCommitments({...projection,items:Array(26).fill(item)},null)).toThrow();const evidence={review_projection_version:1,commitment_id:id,items:[{asset_id:id,created_at:time}],next_cursor:null};expect(reviewEvidence(evidence,id,null).items).toHaveLength(1);expect(()=>reviewEvidence({...evidence,commitment_id:'00000000-0000-0000-0000-000000000009'},id,null)).toThrow();expect(()=>reviewEvidence({...evidence,items:[{asset_id:id,created_at:time,object_key:'private/file'}]},id,null)).toThrow()})
