// Cryptographic tampering/lineage and late-result tests prove independent
// security behavior rather than restating individual implementation branches.
import {expect,it,vi} from 'vitest'
import {NextResponse} from 'next/server'
vi.mock('server-only',()=>({}))
import {newPaymentIntent,encodePaymentIntent,decodePaymentIntent,preparePaymentIntent,installPaymentReturn,PAYMENT_RETURN_COOKIE} from '../lib/server/payment-cookies'
import {PaymentGeneration,separateOperation,type Operation} from '../lib/payments/card-ui-model'
const owner='11111111-1111-4111-8111-111111111111',key=Buffer.alloc(32,7)
it('encrypted intention refuses tampering, cross-owner use and elapsed expiry',()=>{const intent=newPaymentIntent(owner,owner,'customer.ensure',{customer_revision:0}),token=encodePaymentIntent(intent,key);expect(decodePaymentIntent(token,key,owner)).toEqual(intent);expect(()=>decodePaymentIntent(token.slice(0,-2)+'xx',key,owner)).toThrow();expect(()=>decodePaymentIntent(token,key,'other')).toThrow();expect(()=>decodePaymentIntent(token,key,owner,intent.expiresAt)).toThrow();expect(()=>preparePaymentIntent(intent,owner,owner,'customer.ensure',{customer_revision:1})).toThrow()})
it('original apr1 return token and expiry are retained and every cookie is protected',()=>{const response=NextResponse.json({}),token='apr1.'+'a'.repeat(43)+'.'+'b'.repeat(43),expiry=String(BigInt(Date.now()+240000)*1000n);installPaymentReturn(response,token,expiry);const saved=response.cookies.get(PAYMENT_RETURN_COOKIE)!;expect(saved.value).toBe(token);expect(new Date(saved.expires!).getTime()).toBe(Number(BigInt(expiry)/1000n));const header=response.headers.get('set-cookie')!;for(const flag of ['HttpOnly','Secure','SameSite=strict','Path=/'])expect(header).toContain(flag);expect(()=>installPaymentReturn(response,token,String(BigInt(Date.now()+600000)*1000n))).toThrow()})
it('late generations cannot replace newer state and original receipts never change',()=>{const generation=new PaymentGeneration(),old=generation.next();generation.next();expect(generation.current(old)).toBe(false);const previous={summary:{operation_id:owner},original_receipt:{status:'pending'}} as Operation;expect(()=>separateOperation(previous,{...previous,original_receipt:{status:'completed',result:null}})).toThrow();const current={...previous,current_receipt:{status:'completed',result:{state:'ready'}}};expect(separateOperation(previous,current).original_receipt).toBe(previous.original_receipt)})
