// Exercise the actual HTTP/cookie installers with a shared browser-like jar.
// Protocol delegates are finite synthetic lineage doubles; canonical SDK tests
// separately exercise the unchanged capsule/core. No SQL/provider is contacted.
import {beforeEach,it,expect,vi} from 'vitest'
import {NextRequest,NextResponse} from 'next/server'
import type {FinancialReturnLineage} from '../lib/server/financial-return'
vi.mock('server-only',()=>({}))
const fixture=vi.hoisted(()=>({stage:'',late:'',wait:Promise.resolve(),tokens:new Map<string,{commitment:string;operation:string;admission:string;digest:string}>(),serial:0,expired:false,calls:[] as string[]}))
vi.mock('../lib/supabase/config',()=>({accountConfig:()=>({siteOrigin:'https://antedotal.com'})}))
vi.mock('../lib/server/callback-admission',()=>({admitAccountVisitor:async()=>null}))
vi.mock('../lib/server/profile-photo-session',()=>({verifyProfilePhotoSession:async()=>({kind:'verified',session:{ownerId:'00000000-0000-0000-0000-000000000001',token:'a.b.c',provisional:new NextResponse(null)}})}))
vi.mock('../lib/server/financial-return',()=>({issueFinancialReturn:async(_binding:unknown,_owner:unknown,_purpose:unknown,input:{commitment_id:string},lineage:FinancialReturnLineage)=>{fixture.calls.push('issue:'+input.commitment_id);if(fixture.stage==='return/issue'&&fixture.late===input.commitment_id)await fixture.wait;const token='alc1.'+String(++fixture.serial).padStart(43,'A')+'.'+'B'.repeat(43);fixture.tokens.set(token,{commitment:input.commitment_id,operation:lineage.operationId,admission:lineage.returnAdmissionId,digest:lineage.browserDigest});lineage.install(token,String(BigInt(Date.now()+60000)*1000n));return {state:'ready'}},continueFinancialReturn:async(_binding:unknown,_owner:unknown,_purpose:unknown,lineage:FinancialReturnLineage)=>{const row=fixture.tokens.get(lineage.capsule??'');if(!row||row.operation!==lineage.operationId||row.admission!==lineage.returnAdmissionId||row.digest!==lineage.browserDigest)throw Error('browser_lineage_required');fixture.calls.push('continue:'+row.commitment);if(fixture.stage==='return/continue'&&fixture.late===row.commitment)await fixture.wait;return {purpose:'task.long_collection.continue',commitment_id:row.commitment,commitment_revision:1,provider_intent_id:'pi_fixture_'+row.commitment,client_secret:'pi_fixture_secret_'+row.commitment,expires_at:new Date(Date.now()+(fixture.expired?-1:60000)).toISOString(),return_route_key:'account_payments'}}}))
import {createLongCollectionHandler,type LongCollectionBindings} from '../lib/server/account-long-collection'
import {collectionAdmissionCookie,decodeCollectionAdmission} from '../lib/server/collection-cookies'
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,owner=id(1),a=id(2),b=id(3),key=Buffer.alloc(32,3),route=(commitment:string,action:string)=>'by-commitment/'+commitment+'/1/'+action
// Host-only HTTPS jar implements cookie path matching and replaces only exact
// name/host/path triples. It does not manually attach another task's cookies.
class Jar {rows=new Map<string,{name:string;value:string;path:string;expires:number}>();apply(response:NextResponse){for(const header of response.headers.getSetCookie()){const [pair,...attributes]=header.split(';').map(s=>s.trim()),split=pair.indexOf('='),name=pair.slice(0,split),value=pair.slice(split+1),path=attributes.find(s=>s.startsWith('Path='))!.slice(5),expiry=attributes.find(s=>s.startsWith('Expires='));expect(attributes.some(s=>s.toLowerCase()==='secure')).toBe(true);expect(attributes.some(s=>s.toLowerCase()==='httponly')).toBe(true);expect(attributes.some(s=>s.toLowerCase()==='samesite=strict')).toBe(true);expect(attributes.some(s=>s.toLowerCase().startsWith('domain='))).toBe(false);if(name.startsWith('__Host-'))expect(path).toBe('/');else expect(name).toMatch(/^__Secure-ante-long-collection-(read|return)-v2$/);this.rows.set(name+'@antedotal.com'+path,{name,value,path,expires:expiry?Date.parse(expiry.slice(8)):Infinity})}}header(path:string){return [...this.rows.values()].filter(r=>r.expires>Date.now()&&(path===r.path||path.startsWith(r.path)&&(r.path.endsWith('/')||path[r.path.length]==='/'))).sort((x,y)=>y.path.length-x.path.length).map(r=>r.name+'='+r.value).join('; ')}request(path:string,body:unknown={}){const raw='/api/account/collections/'+path;return new NextRequest('https://antedotal.com'+raw,{method:'POST',headers:{host:'antedotal.com',origin:'https://antedotal.com','X-Ante-Payment-Owner':owner,'content-type':'application/json',cookie:this.header(raw)},body:JSON.stringify(body)})}}
let run:ReturnType<typeof createLongCollectionHandler>
beforeEach(()=>{fixture.stage='';fixture.late='';fixture.wait=Promise.resolve();fixture.tokens.clear();fixture.serial=0;fixture.expired=false;fixture.calls=[];const bindings={key,bindings:{enabled:true,services:{owner:async()=>({ownerId:owner,fresh:async()=>{},collection:async(input:{commitment_id:string})=>{fixture.calls.push('read:'+input.commitment_id);if(fixture.stage==='prepare'&&fixture.late===input.commitment_id)await fixture.wait;return {error_code:null,result:{collection_contract_version:1,commitment_id:input.commitment_id,commitment_revision:1,task:{},collection_state:'requires_action',original_intent_known:true,continuation_available:true,collection_operation_id:input.commitment_id===a?id(12):id(13)}}}})}}} as unknown as LongCollectionBindings;run=createLongCollectionHandler(()=>bindings)})
it.each(['prepare','return/issue','return/continue'].flatMap(stage=>[a,b].map(late=>({stage,late}))))('shared jar $stage delayed $late preserves both original task roots/capsules',async({stage,late})=>{const jar=new Jar();for(const action of ['prepare','return/issue','return/continue']){fixture.stage=action===stage?stage:'';fixture.late=late;let release=()=>{};fixture.wait=new Promise<void>(resolve=>{release=resolve});const other=late===a?b:a,body=(task:string)=>action==='prepare'?{commitment_id:task,commitment_revision:1}:{};const slow=run(jar.request(route(late,action),body(late)),route(late,action)),fast=await run(jar.request(route(other,action),body(other)),route(other,action));expect(fast.status).toBe(200);jar.apply(fast);release();const delayed=await slow;expect(delayed.status).toBe(200);jar.apply(delayed);if(action==='return/continue'){expect((await fast.json()).commitment_id).toBe(other);expect((await delayed.json()).commitment_id).toBe(late)}for(const task of [a,b]){const header=jar.header('/api/account/collections/'+route(task,'progress'));const read=header.split('; ').find(s=>s.startsWith('__Secure-ante-long-collection-read-v2='))!;expect(decodeCollectionAdmission(read.slice(read.indexOf('=')+1),key,owner)?.commitmentId).toBe(task);if(action!=='prepare'){const capsule=header.split('; ').find(s=>s.startsWith('__Secure-ante-long-collection-return-v2='))!;expect(fixture.tokens.get(capsule.slice(capsule.indexOf('=')+1))?.commitment).toBe(task)}}}fixture.stage='';for(const task of [a,b]){const response=await run(jar.request(route(task,'return/continue')),route(task,'return/continue'));expect(response.status).toBe(200);expect((await response.json()).commitment_id).toBe(task)}})
it('matching legacy migration retains exact root/capsule recovery and expired return sends no secret',async()=>{const jar=new Jar(),legacy=await run(jar.request('prepare',{commitment_id:a,commitment_revision:1}),'prepare');jar.apply(legacy);const before=[...jar.rows.values()].find(r=>r.name===collectionAdmissionCookie)!;jar.apply(await run(jar.request('return/issue'),'return/issue'));const root=decodeCollectionAdmission(before.value,key,owner);const migrated=await run(jar.request(route(a,'prepare'),{commitment_id:a,commitment_revision:1}),route(a,'prepare'));expect(migrated.status).toBe(200);jar.apply(migrated);const read=[...jar.rows.values()].find(r=>r.name==='__Secure-ante-long-collection-read-v2')!;expect(decodeCollectionAdmission(read.value,key,owner)).toEqual(root);const prepareB=await run(jar.request(route(b,'prepare'),{commitment_id:b,commitment_revision:1}),route(b,'prepare'));expect(prepareB.status).toBe(200);jar.apply(prepareB);const issueB=await run(jar.request(route(b,'return/issue')),route(b,'return/issue'));expect(issueB.status).toBe(200);jar.apply(issueB);for(const path of [route(a,'return/continue'),'return/continue',route(b,'return/continue')]){const recovered=await run(jar.request(path),path);expect(recovered.status).toBe(200);expect((await recovered.json()).commitment_id).toBe(path===route(b,'return/continue')?b:a);}fixture.expired=true;const expired=await run(jar.request(route(a,'return/continue')),route(a,'return/continue'));expect(expired.status).toBe(409);expect(JSON.stringify(await expired.json())).not.toContain('client_secret');expect(expired.headers.get('set-cookie')).toBeNull();expect([...jar.rows.values()].find(r=>r.name===collectionAdmissionCookie)?.value).toBe(before.value)})
