// Actual owner HTTP routes reproduce a live A read root blocking legacy B
// selection, then require safe independent path-scoped browsing without clearing A.
import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest,NextResponse} from 'next/server'
vi.mock('server-only',()=>({}))
const gate=vi.hoisted(()=>({identity:vi.fn()}))
vi.mock('../lib/supabase/config',()=>({accountConfig:()=>({siteOrigin:'https://antedotal.com'})}))
vi.mock('../lib/server/callback-admission',()=>({admitAccountVisitor:async()=>null}))
vi.mock('../lib/server/profile-photo-session',()=>({verifyProfilePhotoSession:gate.identity}))
import {createLongCollectionHandler,type LongCollectionBindings} from '../lib/server/account-long-collection'
import {decodeCollectionAdmission,collectionAdmissionCookie} from '../lib/server/collection-cookies'
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,owner=id(1),a=id(2),b=id(3),key=Buffer.alloc(32,3)
const req=(path:string,body:unknown={},cookie='')=>new NextRequest('https://antedotal.com/api/account/collections/'+path,{method:'POST',headers:{host:'antedotal.com',origin:'https://antedotal.com','X-Ante-Payment-Owner':owner,'content-type':'application/json',cookie},body:JSON.stringify(body)})
const scoped=(commitment:string,action:string)=>'by-commitment/'+commitment+'/1/'+action
const firstCookie=(r:Response)=>r.headers.get('set-cookie')!.split(';')[0]
let bindings:LongCollectionBindings
beforeEach(()=>{gate.identity.mockResolvedValue({kind:'verified',session:{ownerId:owner,token:'a.b.c',provisional:new NextResponse(null)}});bindings={key,bindings:{enabled:true,services:{owner:async()=>({ownerId:owner,fresh:async()=>{},collection:async(input:{commitment_id:string})=>({error_code:null,result:{collection_contract_version:1,commitment_id:input.commitment_id,commitment_revision:1,task:{},collection_state:'requires_action',original_intent_known:true,continuation_available:true,collection_operation_id:id(9)}})})}}} as unknown as LongCollectionBindings})
it('a second commitment can be scoped while the first original admission remains recoverable',async()=>{const run=createLongCollectionHandler(()=>bindings),first=await run(req('prepare',{commitment_id:a,commitment_revision:1}),'prepare');expect(first.status).toBe(200);const original=firstCookie(first),decoded=decodeCollectionAdmission(original.split('=')[1],key,owner)!;expect(original).toContain(collectionAdmissionCookie);const blocked=await run(req('prepare',{commitment_id:b,commitment_revision:1},original),'prepare');expect(blocked.status).toBe(409);const next=await run(req(scoped(b,'prepare'),{commitment_id:b,commitment_revision:1},original),scoped(b,'prepare'));expect(next.status).toBe(200);expect(next.headers.get('set-cookie')).not.toContain(collectionAdmissionCookie+'=');const recovered=await run(req('progress',{},original),'progress');expect(recovered.status).toBe(200);expect(decodeCollectionAdmission(original.split('=')[1],key,owner)).toEqual(decoded)})
it('scoped route has host-only Secure cookie attributes and retains matching legacy root bytes',async()=>{const run=createLongCollectionHandler(()=>bindings),first=await run(req('prepare',{commitment_id:a,commitment_revision:1}),'prepare'),legacy=firstCookie(first),selected=await run(req(scoped(a,'prepare'),{commitment_id:a,commitment_revision:1},legacy),scoped(a,'prepare'));expect(selected.status).toBe(200);const header=selected.headers.get('set-cookie')!;expect(header).toContain('__Secure-ante-long-collection-read-v2=');expect(header).toContain('Path=/api/account/collections/'+scoped(a,''));expect(header).toMatch(/; Secure/i);expect(header).toMatch(/; HttpOnly/i);expect(header).toMatch(/; SameSite=strict/i);expect(header).not.toMatch(/Domain=/i);const selectedBytes=firstCookie(selected).split('=')[1];expect(decodeCollectionAdmission(selectedBytes,key,owner)).toEqual(decodeCollectionAdmission(legacy.split('=')[1],key,owner))})
it('late A prepare response remains on A path after B response and cannot install B lineage',async()=>{let release:()=>void=()=>{};const waiting=new Promise<void>(resolve=>{release=resolve}),base=await bindings.bindings.services.owner(new Request('https://antedotal.com',{headers:{authorization:'Bearer a.b.c'}}),()=>{}),ownerFn=vi.fn(async()=>({...base,collection:async(input:{commitment_id:string;commitment_revision:number})=>{if(input.commitment_id===a)await waiting;return base.collection(input)}}));bindings={...bindings,bindings:{...bindings.bindings,services:{...bindings.bindings.services,owner:ownerFn}}};const run=createLongCollectionHandler(()=>bindings),slow=run(req(scoped(a,'prepare'),{commitment_id:a,commitment_revision:1}),scoped(a,'prepare')),fast=await run(req(scoped(b,'prepare'),{commitment_id:b,commitment_revision:1}),scoped(b,'prepare'));expect(fast.status).toBe(200);release();const late=await slow;expect(late.status).toBe(200);expect(late.headers.get('set-cookie')).toContain('Path=/api/account/collections/'+scoped(a,''));expect(fast.headers.get('set-cookie')).toContain('Path=/api/account/collections/'+scoped(b,''));expect(late.headers.get('set-cookie')).not.toContain(scoped(b,''));const cookieB=firstCookie(fast),progressB=await run(req(scoped(b,'progress'),{},cookieB),scoped(b,'progress'));expect(progressB.status).toBe(200);expect(decodeCollectionAdmission(cookieB.split('=')[1],key,owner)?.commitmentId).toBe(b)})
it('noncanonical path, mismatched body and swapped read cookie deny before owner service',async()=>{const service=vi.fn(bindings.bindings.services.owner);bindings={...bindings,bindings:{...bindings.bindings,services:{...bindings.bindings.services,owner:service}}};const run=createLongCollectionHandler(()=>bindings);for(const path of ['by-commitment/'+a+'/01/prepare','by-commitment/not-an-id/1/prepare','by-commitment/'+a+'/2147483648/prepare'])expect((await run(req(path,{commitment_id:a,commitment_revision:1}),path)).status).toBe(400);expect((await run(req(scoped(a,'prepare'),{commitment_id:b,commitment_revision:1}),scoped(a,'prepare'))).status).toBe(409);expect(service).not.toHaveBeenCalled();const first=await run(req(scoped(a,'prepare'),{commitment_id:a,commitment_revision:1}),scoped(a,'prepare')),stored=firstCookie(first);service.mockClear();expect((await run(req(scoped(b,'progress'),{},stored),scoped(b,'progress'))).status).toBe(409);expect(service).not.toHaveBeenCalled()})
// A selected read namespace also scopes the unchanged capsule format; legacy
// original A recovery remains available without ever borrowing it for B.
it('capsule selection and installation preserve original A and isolate B return lineage',async()=>{const {collectionScope,selectedCollectionCapsule,installSelectedCollectionCapsule}=await import('../lib/server/collection-selection');const run=createLongCollectionHandler(()=>bindings),first=await run(req('prepare',{commitment_id:a,commitment_revision:1}),'prepare'),legacy=firstCookie(first),token='alc1.'+'A'.repeat(43)+'.'+'B'.repeat(43),tokenB='alc1.'+'C'.repeat(43)+'.'+'D'.repeat(43),global=legacy+'; __Host-ante-long-collection-return='+token,scopeA=collectionScope(scoped(a,'return/continue'))!,scopeB=collectionScope(scoped(b,'return/continue'))!;expect(selectedCollectionCapsule(req(scoped(a,'return/continue'),{},global),key,owner,scopeA)).toBe(token);expect(selectedCollectionCapsule(req(scoped(b,'return/continue'),{},global),key,owner,scopeB)).toBeNull();const response=NextResponse.json({});installSelectedCollectionCapsule(response,tokenB,String(BigInt(Date.now()+60000)*1000n),scopeB);const header=response.headers.get('set-cookie')!;expect(header).toContain('__Secure-ante-long-collection-return-v2='+tokenB);expect(header).toContain('Path='+scopeB.path);expect(header).toMatch(/; Secure/i);expect(header).toMatch(/; HttpOnly/i);expect(header).toMatch(/; SameSite=strict/i);expect(header).not.toMatch(/Domain=|__Host-/i);expect(selectedCollectionCapsule(req(scoped(b,'return/continue'),{},global+'; '+firstCookie(response)),key,owner,scopeB)).toBe(tokenB);expect(selectedCollectionCapsule(req('return/continue',{},global),key,owner,null)).toBe(token);expect(()=>selectedCollectionCapsule(req(scoped(b,'return/continue'),{},firstCookie(response)+'; '+firstCookie(response)),key,owner,scopeB)).toThrow()})

// Independent-review failures retain their exact positive legacy setup.
it('rejects empty scoped cookie instead of borrowing legacy original',async()=>{const run=createLongCollectionHandler(()=>bindings),first=await run(req('prepare',{commitment_id:a,commitment_revision:1}),'prepare');const legacy=firstCookie(first);const result=await run(req(scoped(a,'progress'),{},legacy+'; __Secure-ante-long-collection-read-v2='),scoped(a,'progress'));expect(result.status).toBe(409)})
it('rejects encoded separator before owner service',async()=>{const run=createLongCollectionHandler(()=>bindings),path=scoped(a,'prepare');const encoded=path.replace('/1/','%2F1%2F');const result=await run(req(encoded,{commitment_id:a,commitment_revision:1}),path);expect(result.status).toBe(400)})
it('rejects empty scoped return cookie rather than borrowing global capsule',async()=>{const {collectionScope,selectedCollectionCapsule}=await import('../lib/server/collection-selection');const run=createLongCollectionHandler(()=>bindings),first=await run(req('prepare',{commitment_id:a,commitment_revision:1}),'prepare'),legacy=firstCookie(first),token='alc1.'+'A'.repeat(43)+'.'+'B'.repeat(43);expect(()=>selectedCollectionCapsule(req(scoped(a,'return/continue'),{},legacy+'; __Host-ante-long-collection-return='+token+'; __Secure-ante-long-collection-return-v2='),key,owner,collectionScope(scoped(a,'return/continue')))).toThrow()})
// Raw aliases and noncanonical logical selectors must stop before Auth/config
// service resolution, while unchanged legacy and canonical routes stay valid.
it('raw route/query/action aliases reject before any identity or service admission',async()=>{const resolver=vi.fn(()=>bindings),run=createLongCollectionHandler(resolver),alpha='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';gate.identity.mockClear();const pairs=[{raw:scoped(a,'prepare').replace('/1/','%2F1%2F'),logical:scoped(a,'prepare')},{raw:scoped(a,'prepare').replace('by-commitment','%62y-commitment'),logical:scoped(a,'prepare')},{raw:scoped(a,'prepare')+'?after=x',logical:scoped(a,'prepare')},{raw:scoped(a,'prepare')+'/',logical:scoped(a,'prepare')},{raw:'by-commitment/'+alpha.toUpperCase()+'/1/prepare',logical:'by-commitment/'+alpha.toUpperCase()+'/1/prepare'},...['01','+1','1.0','1e0','0','2147483648'].map(revision=>({raw:'by-commitment/'+a+'/'+revision+'/prepare',logical:'by-commitment/'+a+'/'+revision+'/prepare'})),{raw:scoped(a,'prepare/other'),logical:scoped(a,'prepare/other')},{raw:'return/issue/extra',logical:'return/issue/extra'}];for(const {raw,logical}of pairs)expect((await run(req(raw,{commitment_id:a,commitment_revision:1}),logical)).status).toBe(400);expect(gate.identity).not.toHaveBeenCalled();const first=await run(req('prepare',{commitment_id:a,commitment_revision:1}),'prepare');expect(first.status).toBe(200);expect((await run(req(scoped(a,'prepare'),{commitment_id:a,commitment_revision:1},firstCookie(first)),scoped(a,'prepare'))).status).toBe(200)})
