// GENERATED exact accepted intake event catalog; edit the finite builder.
export const noticeEvents:Readonly<Record<string,readonly [string,string]>>=Object.freeze({
    "payment_intent.succeeded": ["payment_intent", "pi_"],
    "payment_intent.payment_failed": ["payment_intent", "pi_"],
    "payment_intent.canceled": ["payment_intent", "pi_"],
    "payment_intent.amount_capturable_updated": ["payment_intent", "pi_"],
    "payment_intent.requires_action": ["payment_intent", "pi_"],
    "setup_intent.succeeded": ["setup_intent", "seti_"],
    "setup_intent.setup_failed": ["setup_intent", "seti_"],
    "setup_intent.canceled": ["setup_intent", "seti_"],
    "checkout.session.completed": ["checkout.session", "cs_"],
    "checkout.session.async_payment_succeeded": ["checkout.session", "cs_"],
    "checkout.session.async_payment_failed": ["checkout.session", "cs_"],
    "checkout.session.expired": ["checkout.session", "cs_"],
    "invoice.paid": ["invoice", "in_"],
    "invoice.payment_failed": ["invoice", "in_"],
    "invoice.finalized": ["invoice", "in_"],
    "invoice.voided": ["invoice", "in_"],
    "invoice.marked_uncollectible": ["invoice", "in_"],
    "customer.subscription.created": ["subscription", "sub_"],
    "customer.subscription.updated": ["subscription", "sub_"],
    "customer.subscription.deleted": ["subscription", "sub_"],
    "charge.refunded": ["charge", "ch_"],
    "charge.dispute.created": ["dispute", "dp_"],
    "charge.dispute.updated": ["dispute", "dp_"],
    "charge.dispute.closed": ["dispute", "dp_"],
    "refund.created": ["refund", "re_"],
    "refund.updated": ["refund", "re_"],
    "refund.failed": ["refund", "re_"],
});
