// GENERATED finite Task12 successor from accepted96b8 V3; edit only the builder.
// GENERATED from accepted V2 by closed-web-payment-short-holds/build.mjs; change only the finite transform.
// GENERATED by closed-web-payment-subscriptions/build.mjs from pinned accepted V1; edit the finite transform.
// Frozen canonical JSON/UUID/provider bounds are reused unchanged.
import {
  exact,
  internalId,
  paymentRequestHash,
  providerActionSupport,
  providerId,
} from "../../../scripts/backend/web-payment-provider-contract.mjs";
import {billingObjectId,uuid,revision} from '../../../scripts/backend/web-payment-subscription-contract.mjs';
import {holdObjectId,validateHoldPermit} from '../../../scripts/backend/web-payment-short-hold-contract.mjs';
import {validateCollectionPermit} from '../../../scripts/backend/web-payment-collection-contract.mjs';
export {holdObjectId};
export { exact, internalId, paymentRequestHash, providerId, billingObjectId };
export const API_VERSION = "2026-09-30.endive" as const;
export const SDK_VERSION = "23.0.0" as const;
export type Kind =
  | "customer.create"
  | "setup.create"
  | "setup.retrieve"
  | "customer.default"
  | "card.detach"
  | "subscription.create"
  | "subscription.cancel"
  | "authorization.create"
  | "authorization.cancel"
  | "authorization.capture"
  | "collection.create";
export type Outcome =
  | "verified"
  | "pending"
  | "requires_action"
  | "declined"
  | "unknown"
  | "denied";
export type Configuration = {
  configuration_id: string;
  revision: number;
  task7_configuration_id: string;
  approval_id: string;
  approval_hash: string;
  provider_account: string;
  environment: "test" | "live";
  sandbox_id: string;
  credential_reference: string;
  provisioning_hash: string;
  api_version: string;
  sdk_version: string;
  adapter_version: string;
  policy_id: string;
  policy_version: string;
  policy_hash: string;
  method_configuration: string;
  dispatch_enabled: boolean;
  fixture_only: boolean;
  default_policy: "invoice" | "internal" | null;
  removal_policy: "block_dependencies" | null;
  allow_default_removal: boolean | null;
  allow_last_card_removal: boolean | null;
  retention_seconds: number;
  lease_seconds: number;
  continuation_seconds: number;
  effective_at: string;
  expires_at: string;
};
// Premium purpose/config sidecar is independent of card.save and must match the original provider provisioning FK.
export type BillingConfiguration = {
 configuration_id:string; revision:number; provider_configuration_id:string; approval_id:string; approval_hash:string;
 policy_id:string; policy_version:string; policy_hash:string; purpose:'premium.subscribe'; country:'AU'; currency:'aud'; billing_enabled:boolean;
 plan_key:'monthly'|'annual'; price_id:string; product_id:string; unit_amount:number; interval:'month'|'year'; interval_count:1;
 tax_behavior:'inclusive'|'exclusive'; tax_policy:'approved_no_automatic_tax'; merchant_policy_hash:string; support_policy_hash:string;
 cap_configuration_id:string; cap_configuration_revision:number; max_financial_commitments:number;
 effective_at:string; expires_at:string; return_adapter_version:null|'premium_return_v1'; event_adapter_version:null|'canonical_notice_v1';
};
// Hold commercial approval and original Task10 context are distinct from billing/card-save purpose and never supplied by an owner request.
export type HoldConfiguration={configuration_id:string;revision:number;provider_configuration_id:string;task_configuration_id:string;approval_id:string;approval_hash:string;terms_hash:string;country:'AU';currency:'aud';cutoff_seconds:number;processing_buffer_seconds:number;authorization_enabled:true;release_policy:'definitive_success_original_intent';expired_policy:'unsecured_no_reauthorize';effective_at:string;expires_at:string;task_created_at:string;original_due_at:string;quote_hash:string;authorization_operation_id:string;authorization_subaction_id:string;continuation_adapter_version:null|'short_hold_return_v1'};
// Collection approval and original finality identity are separate from card enrollment, subscriptions and original hold approval.
export type CollectionConfiguration={configuration_id:string;revision:number;provider_configuration_id:string;task_configuration_id:string;approval_id:string;approval_hash:string;terms_hash:string;country:'AU';currency:'aud';processing_buffer_seconds:number;collection_enabled:true;collection_policy:'definitive_failure_original_commitment';expired_policy:'unsecured_no_reauthorize';effective_at:string;expires_at:string;quote_hash:string;start_id:string;finality_id:string;work_id:string;eligibility_hash:string;original_operation_id:string;original_subaction_id:string;continuation_adapter_version:null|'long_collection_return_v1'};
export type Permit = {
  collection_configuration?:CollectionConfiguration;
  hold_configuration?:HoldConfiguration;
  purpose?:"premium.subscribe"|"task.short_hold"|"task.failure_collection";
  object_kind?:"checkout_session"|"subscription"|"payment_intent";
  billing_configuration?:BillingConfiguration;
  subaction_id: string;
  owner_id: string;
  operation_id: string;
  parent_action: string;
  kind: Kind;
  customer_id: string;
  subject_id: string;
  subject_revision: number;
  customer_revision: number;
  configuration_id: string;
  configuration_hash: string;
  consent_id: string | null;
  request_hash: string;
  parameters: Record<string, unknown>;
  parameter_hash: string;
  provider_key: string;
  created_at: string;
  configuration: Configuration;
  lease_generation: number;
  lease_expires_at: string;
  operation_revision: number;
  plan: "effect" | "retrieve";
  object_id: string | null;
};
export type Observation = {
  amount_received?:string|null;
  payment_state?:string|null;amount_minor?:string|null;amount_capturable?:string|null;currency?:string|null;capture_before?:string|null;charge_id?:string|null;
  purpose?:"premium.subscribe"|"task.short_hold"|"task.failure_collection";
  object_kind?:"checkout_session"|"subscription"|"payment_intent";
  checkout_state?:"open"|"complete"|"expired"|null;
  provider_subscription_id?:string|null;
  subscription_state?:string|null;
  cancel_at_period_end?:boolean|null;
  kind: Kind;
  outcome: Outcome;
  observed_at: string;
  request_id: string | null;
  transport_outcome: "received" | "unknown" | "not_dispatched";
  safe_error_code:
    | "provider_declined"
    | "provider_authentication_required"
    | "provider_unknown"
    | "identity_mismatch"
    | "activation_closed"
    | null;
  object_id: string | null;
  customer_id: string | null;
  method_id: string | null;
  method_type: string | null;
  livemode: boolean | null;
  provider_account: string;
  sandbox_id: string;
  configuration_id: string;
  configuration_hash: string;
  operation_id: string;
  subject_id: string;
  parameter_hash: string;
  usage: string | null;
  method_configuration: string | null;
  setup_state:
    | "pending"
    | "requires_action"
    | "succeeded"
    | "canceled"
    | "failed"
    | null;
  brand: string | null;
  last4: string | null;
  expiry_month: number | null;
  expiry_year: number | null;
  default_method_id: string | null;
};
const permitKeys =
  "subaction_id owner_id operation_id parent_action kind customer_id subject_id subject_revision customer_revision configuration_id configuration_hash consent_id request_hash parameters parameter_hash provider_key created_at configuration lease_generation lease_expires_at operation_revision plan object_id"
    .split(" ");
const configKeys =
  "configuration_id revision task7_configuration_id approval_id approval_hash provider_account environment sandbox_id credential_reference provisioning_hash api_version sdk_version adapter_version policy_id policy_version policy_hash method_configuration dispatch_enabled fixture_only default_policy removal_policy allow_default_removal allow_last_card_removal retention_seconds lease_seconds continuation_seconds effective_at expires_at"
    .split(" ");
// Only the private persisted repository creates this permit; strict decoding precedes credentials/SDK.
export function parsePermitJoint(value: unknown): Permit {
  const billing=!!value&&typeof value==='object'&&['subscription.create','subscription.cancel'].includes(String((value as {kind?:unknown}).kind));
  const hold=!!value&&typeof value==='object'&&['authorization.create','authorization.cancel'].includes(String((value as {kind?:unknown}).kind));
  const collection=!!value&&typeof value==='object'&&['authorization.capture','collection.create'].includes(String((value as {kind?:unknown}).kind));
  if (!exact(value,collection?[...permitKeys,'purpose','object_kind','collection_configuration']:billing?[...permitKeys,'purpose','object_kind','billing_configuration']:hold?[...permitKeys,'purpose','object_kind','hold_configuration']:permitKeys))throw new Error('invalid_permit');
  const p = value as Permit, c = p.configuration;
  if (
    !exact(c, configKeys) ||
    providerActionSupport(p.kind) !== "implemented" && !billing && !hold && !collection ||
    !["effect", "retrieve"].includes(p.plan)
  ) throw new Error("invalid_permit");
  for (
    const k of [
      "subaction_id",
      "owner_id",
      "operation_id",
      "customer_id",
      "subject_id",
      "configuration_id",
    ] as const
  ) if (!internalId(p[k])) throw new Error("invalid_permit");
  for (
    const k of ["configuration_hash", "request_hash", "parameter_hash"] as const
  ) if (!/^[0-9a-f]{64}$/.test(p[k])) throw new Error("invalid_permit");
  if (
    !Number.isSafeInteger(p.lease_generation) || p.lease_generation < 1 ||
    !Number.isSafeInteger(p.operation_revision) || p.operation_revision < 0 ||
    p.configuration_id !== c.configuration_id ||
    p.configuration_hash !== paymentRequestHash(c) ||
    p.parameter_hash !== paymentRequestHash(p.parameters) ||
    p.provider_key !== `ante:provider-v1:${p.subaction_id}:${p.kind}`
  ) throw new Error("invalid_permit");
  if (
    c.api_version !== API_VERSION || c.sdk_version !== SDK_VERSION ||
    c.adapter_version !== "provider-v1" ||
    !["test", "live"].includes(c.environment) || !c.dispatch_enabled ||
    !providerId(c.provider_account) || !providerId(c.sandbox_id) ||
    !providerId(c.credential_reference) ||
    !providerId(c.method_configuration) ||
    !Number.isInteger(c.retention_seconds) || c.retention_seconds < 1 ||
    c.retention_seconds >= 86400
  ) throw new Error("invalid_permit");
  if (
    ![p.created_at, p.lease_expires_at, c.effective_at, c.expires_at].every(
      (v) => typeof v === "string" && Number.isFinite(Date.parse(v)),
    ) || p.kind !== "customer.create" && !internalId(p.consent_id) ||
    !Number.isInteger(c.continuation_seconds) || c.continuation_seconds < 1 ||
    c.continuation_seconds > 300 || !Number.isInteger(p.subject_revision) ||
    p.subject_revision < 1 || !Number.isInteger(p.customer_revision) ||
    p.customer_revision < 1
  ) throw new Error("invalid_permit");
  // Closed billing grammar binds all sidecar commercial authority without accepting a caller-selected provider object.
  if (p.kind === 'subscription.create' || p.kind === 'subscription.cancel') {
    const b=p.billing_configuration;
    const keys='configuration_id revision provider_configuration_id approval_id approval_hash policy_id policy_version policy_hash purpose country currency billing_enabled plan_key price_id product_id unit_amount interval interval_count tax_behavior tax_policy merchant_policy_hash support_policy_hash cap_configuration_id cap_configuration_revision max_financial_commitments effective_at expires_at return_adapter_version event_adapter_version'.split(' ');
    if(!exact(b,keys)||!b||b.purpose!=='premium.subscribe'||b.billing_enabled!==true||p.purpose!==b.purpose||b.provider_configuration_id!==c.configuration_id||!['monthly','annual'].includes(b.plan_key)||b.country!=='AU'||b.currency!=='aud'||b.interval!==(b.plan_key==='monthly'?'month':'year')||b.interval_count!==1||!['inclusive','exclusive'].includes(b.tax_behavior)||b.tax_policy!=='approved_no_automatic_tax'||![null,'premium_return_v1'].includes(b.return_adapter_version)||b.event_adapter_version!==null&&b.event_adapter_version!=='canonical_notice_v1'||!['configuration_id','approval_id','policy_id','cap_configuration_id'].every(k=>uuid(b[k as keyof BillingConfiguration]))||!['approval_hash','policy_hash','merchant_policy_hash','support_policy_hash'].every(k=>typeof b[k as keyof BillingConfiguration]==='string'&&/^[0-9a-f]{64}$/.test(String(b[k as keyof BillingConfiguration])))||!revision(b.revision)||!revision(b.cap_configuration_revision)||!revision(b.unit_amount)||!revision(b.max_financial_commitments)||!billingObjectId('price',b.price_id)||!billingObjectId('product',b.product_id)||![b.effective_at,b.expires_at].every(v=>typeof v==='string'&&Number.isFinite(Date.parse(v)))||Date.parse(b.expires_at)<=Date.parse(b.effective_at)||p.object_kind!==(p.kind==='subscription.create'?'checkout_session':'subscription')||p.parent_action!==(p.kind==='subscription.create'?'subscription.checkout':'subscription.manage')||p.plan==='retrieve'&&!billingObjectId(p.object_kind,p.object_id))throw new Error('invalid_permit');
    if(!exact(p.parameters,p.kind==='subscription.create'?['customer','price','metadata']:['customer','subscription_id','cancel_at_period_end'])||!billingObjectId('customer',p.parameters.customer)||p.kind==='subscription.create'&&(p.parameters.price!==b.price_id||!exact(p.parameters.metadata,['ante_operation','ante_subscription'])||(p.parameters.metadata as Record<string,string>).ante_operation!==p.operation_id||(p.parameters.metadata as Record<string,string>).ante_subscription!==p.subject_id)||p.kind==='subscription.cancel'&&(!billingObjectId('subscription',p.parameters.subscription_id)||p.parameters.cancel_at_period_end!==true||p.object_id!==p.parameters.subscription_id))throw new Error('invalid_permit');
  }
  if(hold)validateHoldPermit(p);
  if(collection)validateCollectionPermit(p);
  return structuredClone(p);
}
// Build a fixed safe observation shape; raw SDK objects/errors/secrets cannot be persisted.
export function observationJoint(
  p: Permit,
  outcome: Outcome,
  now = Date.now(),
): Observation {
  return {
    ...(p.kind==='subscription.create'||p.kind==='subscription.cancel'?{purpose:p.purpose,object_kind:p.object_kind,checkout_state:null,provider_subscription_id:null,subscription_state:null,cancel_at_period_end:null}:{}),
    ...(p.kind==='authorization.create'||p.kind==='authorization.cancel'?{purpose:p.purpose,object_kind:p.object_kind,payment_state:null,amount_minor:null,amount_capturable:null,currency:null,capture_before:null,charge_id:null}:{}),
    ...(p.kind==='authorization.capture'||p.kind==='collection.create'?{purpose:p.purpose,object_kind:p.object_kind,payment_state:null,amount_minor:null,amount_received:null,amount_capturable:null,currency:null,capture_before:null,charge_id:null}:{}),
    kind: p.kind,
    outcome,
    observed_at: new Date(now).toISOString(),
    request_id: null,
    transport_outcome: outcome === "denied" ? "not_dispatched" : "unknown",
    safe_error_code: outcome === "denied"
      ? "activation_closed"
      : outcome === "unknown"
      ? "provider_unknown"
      : null,
    object_id: null,
    customer_id: null,
    method_id: null,
    method_type: null,
    livemode: null,
    provider_account: p.configuration.provider_account,
    sandbox_id: p.configuration.sandbox_id,
    configuration_id: p.configuration_id,
    configuration_hash: p.configuration_hash,
    operation_id: p.operation_id,
    subject_id: p.subject_id,
    parameter_hash: p.parameter_hash,
    usage: null,
    method_configuration: null,
    setup_state: null,
    brand: null,
    last4: null,
    expiry_month: null,
    expiry_year: null,
    default_method_id: null,
  };
}
