import {parseNoticePermit,parseCanonicalNotice,type NoticePermit,type CanonicalNotice} from './webPaymentJointNotice.ts';
// GENERATED finite Task12 successor from accepted96b8 V3; edit only the builder.
// GENERATED from accepted V2 by closed-web-payment-short-holds/build.mjs; change only the finite transform.
// GENERATED by closed-web-payment-subscriptions/build.mjs from pinned accepted V1; edit the finite transform.
import {
  exact,
  internalId,
  type Observation,
  parsePermitJoint,
  type Permit,
} from "./webPaymentProviderContractJoint.ts";
// The transport is a trusted private repository binding, not a user-selected RPC/table proxy.
// This source port has no Data API grants or deployed worker; dedicated job wiring is a later unit.
export type PrivateRpc = (
  name:
    | "claim_v4"
    | "claim_notice"
    | "record_notice_dispatch"
    | "record_notice_observation"
    | "reconcile_notice"
    | "record_dispatch_v4"
    | "record_observation_v4"
    | "reconcile_v4"
    | "continuation"
    | "consume_continuation"
    | "hold_continuation"
    | "consume_hold_continuation"
    | "collection_continuation"
    | "consume_collection_continuation",
  args: Record<string, unknown>,
) => Promise<unknown>;
export type ContinuationContext = {
  permit: Permit;
  ticket: {
    ticket_id: string;
    owner_id: string;
    setup_id: string;
    setup_revision: number;
    subaction_id: string;
    operation_revision: number;
    created_at: string;
    expires_at: string;
  };
};
export type HoldContinuationContext={permit:Permit;ticket:{ticket_id:string;owner_id:string;commitment_id:string;commitment_revision:number;subaction_id:string;operation_revision:number;observation_id:string;lease_generation:number;provider_intent_id:string;transport_approval_id:string;created_at:string;expires_at:string}};
export class ProviderRepositoryJoint {
  constructor(
    private readonly rpc: PrivateRpc,
    private readonly workerIdentity: string,
  ) {}
  // Fixed system-notice ports share the original private repository transport.
  // They accept only persisted signed jobs and never accept an owner selector.
  async claimNotices(limit=20):Promise<NoticePermit[]>{
   if(!Number.isInteger(limit)||limit<1||limit>20)throw Error('invalid_input');
   const value=await this.rpc('claim_notice',{p_limit:limit});
   if(!Array.isArray(value)||value.length>limit)throw Error('repository_unknown');return value.map(v=>parseNoticePermit(v));
  }
  async recordNoticeDispatch(p:NoticePermit):Promise<boolean>{
   parseNoticePermit(p);return await this.rpc('record_notice_dispatch',{p_job:p.retrieval_job_id,p_generation:p.lease_generation,p_revision:p.operation_revision})===true;
  }
  async recordNoticeObservation(p:NoticePermit,o:CanonicalNotice):Promise<unknown>{
   return await this.rpc('record_notice_observation',{p_job:p.retrieval_job_id,p_generation:p.lease_generation,p_revision:p.operation_revision,p_observation:parseCanonicalNotice(p,o)});
  }
  async reconcileNotice(p:NoticePermit):Promise<unknown>{return await this.rpc('reconcile_notice',{p_job:p.retrieval_job_id,p_generation:p.lease_generation});}
  async claim(limit = 20): Promise<Permit[]> {
    if (!Number.isInteger(limit) || limit < 1 || limit > 20) {
      throw new Error("invalid_input");
    }
    const value = await this.rpc("claim_v4", {
      p_limit: limit,
      p_worker: this.workerIdentity,
    });
    if (!Array.isArray(value) || value.length > limit) {
      throw new Error("repository_unknown");
    }
    return value.map(parsePermitJoint);
  }
  // SQL compares the exact claimed plan/object with reconciliation under its owner lock.
  // A changed identity or expired effect horizon denies this claim before SDK construction.
  async recordDispatch(p: Permit): Promise<boolean> {
    parsePermitJoint(p);
    return await this.rpc("record_dispatch_v4", {
      p_subaction: p.subaction_id,
      p_generation: p.lease_generation,
      p_revision: p.operation_revision,
      p_plan: p.plan,
      p_object_id: p.object_id,
    }) === true;
  }
  async recordObservation(p: Permit, o: Observation): Promise<unknown> {
    return await this.rpc("record_observation_v4", {
      p_subaction: p.subaction_id,
      p_generation: p.lease_generation,
      p_revision: p.operation_revision,
      p_observation: o,
    });
  }
  // The private SQL authority derives owner, original intent, immutable quote and one-use ticket; callers supply only commitment identity/revision.
  // The private SQL authority derives owner, original intent, immutable quote and one-use ticket; callers supply only commitment identity/revision.
  async collectionContinuation(commitmentId:string,revision:number):Promise<HoldContinuationContext|null>{
    if(!internalId(commitmentId)||!Number.isInteger(revision)||revision<1)throw new Error('invalid_input');
    const v=await this.rpc('collection_continuation',{p_commitment:commitmentId,p_revision:revision});if(v===null)return null;
    if(!exact(v,['permit','ticket']))throw new Error('repository_unknown');const ctx=v as HoldContinuationContext;ctx.permit=parsePermitJoint(ctx.permit);const p=ctx.permit,t=ctx.ticket;
    if(!exact(t,'ticket_id owner_id commitment_id commitment_revision subaction_id operation_revision observation_id lease_generation provider_intent_id transport_approval_id created_at expires_at'.split(' '))||!internalId(t.ticket_id)||!internalId(t.observation_id)||!internalId(t.transport_approval_id)||t.owner_id!==p.owner_id||t.commitment_id!==commitmentId||t.commitment_id!==p.subject_id||t.commitment_revision!==revision||t.commitment_revision!==p.subject_revision||t.subaction_id!==p.subaction_id||t.operation_revision!==p.operation_revision||t.lease_generation!==p.lease_generation||t.provider_intent_id!==p.object_id||t.expires_at!==p.lease_expires_at||!Number.isFinite(Date.parse(t.created_at))||Date.parse(t.created_at)>Date.now()||Date.parse(t.expires_at)<=Date.now()||p.kind!=='collection.create'||p.plan!=='retrieve'||p.collection_configuration?.continuation_adapter_version!=='long_collection_return_v1')throw new Error('repository_unknown');return ctx;
  }
  // SQL locks and atomically consumes the exact stored ticket only after rechecking current owner/consent/configuration, original observation and shared lease generation.
  async consumeCollectionContinuation(ctx:HoldContinuationContext){return await this.rpc('consume_collection_continuation',{p_ticket:ctx.ticket.ticket_id})===true;}
  async holdContinuation(commitmentId:string,revision:number):Promise<HoldContinuationContext|null>{
    if(!internalId(commitmentId)||!Number.isInteger(revision)||revision<1)throw new Error('invalid_input');
    const v=await this.rpc('hold_continuation',{p_commitment:commitmentId,p_revision:revision});if(v===null)return null;
    if(!exact(v,['permit','ticket']))throw new Error('repository_unknown');const ctx=v as HoldContinuationContext;ctx.permit=parsePermitJoint(ctx.permit);const p=ctx.permit,t=ctx.ticket;
    if(!exact(t,'ticket_id owner_id commitment_id commitment_revision subaction_id operation_revision observation_id lease_generation provider_intent_id transport_approval_id created_at expires_at'.split(' '))||!internalId(t.ticket_id)||!internalId(t.observation_id)||!internalId(t.transport_approval_id)||t.owner_id!==p.owner_id||t.commitment_id!==commitmentId||t.commitment_id!==p.subject_id||t.commitment_revision!==revision||t.commitment_revision!==p.subject_revision||t.subaction_id!==p.subaction_id||t.operation_revision!==p.operation_revision||t.lease_generation!==p.lease_generation||t.provider_intent_id!==p.object_id||t.expires_at!==p.lease_expires_at||!Number.isFinite(Date.parse(t.created_at))||Date.parse(t.created_at)>Date.now()||Date.parse(t.expires_at)<=Date.now()||p.kind!=='authorization.create'||p.plan!=='retrieve'||p.hold_configuration?.continuation_adapter_version!=='short_hold_return_v1')throw new Error('repository_unknown');return ctx;
  }
  // SQL locks and atomically consumes the exact stored ticket only after rechecking current owner/consent/configuration, original observation and shared lease generation.
  async consumeHoldContinuation(ctx:HoldContinuationContext){return await this.rpc('consume_hold_continuation',{p_ticket:ctx.ticket.ticket_id})===true;}
  async continuation(
    setupId: string,
    revision: number,
  ): Promise<ContinuationContext | null> {
    if (!internalId(setupId) || !Number.isInteger(revision) || revision < 1) {
      throw new Error("invalid_input");
    }
    const v = await this.rpc("continuation", {
      p_setup: setupId,
      p_revision: revision,
    });
    if (v === null) return null;
    if (!exact(v, ["permit", "ticket"])) throw new Error("repository_unknown");
    const ctx = v as ContinuationContext;
    ctx.permit = parsePermitJoint(ctx.permit);
    const ticket = ctx.ticket, p = ctx.permit;
    if (
      !exact(
        ticket,
        "ticket_id owner_id setup_id setup_revision subaction_id operation_revision created_at expires_at"
          .split(" "),
      ) || !internalId(ticket.ticket_id) || ticket.owner_id !== p.owner_id ||
      ticket.setup_id !== setupId || ticket.setup_id !== p.subject_id ||
      ticket.setup_revision !== revision ||
      ticket.subaction_id !== p.subaction_id ||
      ticket.operation_revision !== p.operation_revision ||
      ticket.expires_at !== p.lease_expires_at || p.kind !== "setup.create" ||
      p.plan !== "retrieve"
    ) throw new Error("repository_unknown");
    return ctx;
  }
  async consumeContinuation(ctx: ContinuationContext) {
    return await this.rpc("consume_continuation", {
      p_ticket: ctx.ticket.ticket_id,
    }) === true;
  }
  async reconcile(
    p: Permit,
  ): Promise<
    {
      plan: "effect" | "retrieve" | "manual_required";
      object_id: string | null;
    }
  > {
    const value = await this.rpc("reconcile_v4", { p_subaction: p.subaction_id });
    if (
      !exact(value, ["plan", "object_id"]) ||
      !["effect", "retrieve", "manual_required"].includes(
        (value as { plan: string }).plan,
      )
    ) throw new Error("repository_unknown");
    return value as {
      plan: "effect" | "retrieve" | "manual_required";
      object_id: string | null;
    };
  }
}
