import {type NoticePermit,type CanonicalNotice,unknownNotice,parseNoticePermit,validateOriginalRead,type OwnedOriginalSdk} from './webPaymentJointNotice.ts';
import {retrieveCanonicalNotice} from './webPaymentJointRetrieval.ts';
// GENERATED finite Task12 successor from accepted96b8 V3; edit only the builder.
// GENERATED from accepted V2 by closed-web-payment-short-holds/build.mjs; change only the finite transform.
// GENERATED by closed-web-payment-subscriptions/build.mjs from pinned accepted V1; edit the finite transform.
import {
  exact,
  type Observation,
  observationJoint,
  type Permit,
  providerId,
  billingObjectId,
  holdObjectId,
} from "./webPaymentProviderContractJoint.ts";
import {
  createProviderClientJoint,
  type GuardedTransport,
  type Provisioning,
} from "./webPaymentProviderClientJoint.ts";
import type { ProviderRepositoryJoint } from "./webPaymentProviderRepositoryJoint.ts";
import {type PremiumReturnDispatch,approvedPremiumReturnUrls} from './webPaymentPremiumReturnDispatchJoint.ts';
// Explicit card selection is mutually exclusive with payment_method_configuration
// (Stripe 2026-07-29 changelog). Both returned lists must remain exactly card;
// nullable configuration details must be literal null, never a fabricated echo.
function verifyExplicitCardMethodSet(raw:{allowed_payment_method_types?:unknown;payment_method_types?:unknown;payment_method_configuration_details?:unknown}):void{
 if(JSON.stringify(raw.allowed_payment_method_types)!=='["card"]'||JSON.stringify(raw.payment_method_types)!=='["card"]'||raw.payment_method_configuration_details!==null)throw new Error('identity_mismatch');
}
// Only this fixed operation adapter touches the guarded private SDK; no arbitrary SDK proxy is exposed.
export function executeProviderJoint(p:Permit,provision:Provisioning,credential:()=>string,transport:GuardedTransport,returnDispatch?:PremiumReturnDispatch|null):Promise<Observation>;
export function executeProviderJoint(p:NoticePermit,provision:Provisioning,credential:()=>string,transport:GuardedTransport):Promise<CanonicalNotice>;
export async function executeProviderJoint(
  p: Permit | NoticePermit,
  provision: Provisioning,
  credential: () => string,
  transport: GuardedTransport,
  returnDispatch: PremiumReturnDispatch | null = null,
): Promise<Observation | CanonicalNotice> {
  if(p.kind==='webhook.retrieve'){
   try{const captured=parseNoticePermit(p),{sdk}=createProviderClientJoint(captured,provision,credential,transport);return await retrieveCanonicalNotice(captured,sdk,transport,async original=>{const read=validateOriginalRead(captured,original);return await executeOriginalBody(read,provision,credential,{...transport,run:async work=>{validateOriginalRead(captured,read);const result=await transport.run(work);if(!result||typeof result!=='object'||(result as {lastResponse?:{apiVersion?:string}}).lastResponse?.apiVersion!==captured.api_version)throw Error('notice_identity_mismatch');validateOriginalRead(captured,read);return result;}},sdk);});}catch{return unknownNotice(p);}
  }
  return executeOriginalBody(p,provision,credential,transport,undefined,returnDispatch);
}
// Module-private same-engine body. The SDK capability originates only inside
// the notice branch; no caller can choose a stage/method or inject a client.
async function executeOriginalBody(p:Permit,provision:Provisioning,credential:()=>string,transport:GuardedTransport,ownedSdk?:OwnedOriginalSdk,returnDispatch:PremiumReturnDispatch|null=null):Promise<Observation>{
  // Financial dispatch consumes an authoritative finality job already fenced by SQL. Short capture uses the same live manual intent; long create is a single immutable off-session collection keyed by that job.
  if(p.kind==='authorization.capture'||p.kind==='collection.create'){
    const short=p.kind==='authorization.capture',params=p.parameters,c=p.collection_configuration!;let result=observationJoint(p,'unknown');
    try{
      const sdk=ownedSdk??createProviderClientJoint(p,provision,credential,transport).sdk,options={idempotencyKey:p.provider_key,maxNetworkRetries:0};let intent:HoldIntent;
      if(short){
        intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(String(params.payment_intent_id),{expand:['latest_charge']},{maxNetworkRetries:0})));
        if(intent.status==='requires_capture'&&p.plan==='effect'){
          const captureBefore=verifyCollectionCharge(p,intent,false)!;
          if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
          if(captureBefore>Date.now()+c.processing_buffer_seconds*1000){
          // Full original amount only, one final capture via the documented default.
          // Omit optional final_capture on the wire; all internal finality and original-amount gates remain unchanged.
          intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.capture(intent.id,{amount_to_capture:Number(params.amount_minor),expand:['latest_charge']},options)));
          }
          // A known expired/cutoff hold is observed truthfully below without dispatching capture or replacement.
        }
      }else{
        try{intent=verifyOriginalHoldIntent(p,await transport.run(()=>p.plan==='retrieve'?sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0}):sdk.paymentIntents.create({amount:Number(params.amount_minor),currency:String(params.currency),customer:String(params.customer),payment_method:String(params.method_id),capture_method:'automatic',confirm:true,off_session:true,allowed_payment_method_types:['card'],metadata:params.metadata as Record<string,string>,expand:['latest_charge']},options)));}
        catch(error){const rejected=error as {type?:string;payment_intent?:HoldIntent};if(rejected.type!=='StripeCardError'||!rejected.payment_intent)throw error;intent=await resolveOriginalCreateDecline(p,rejected.payment_intent,sdk,transport);}
      }
      if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
      result={...result,transport_outcome:'received',safe_error_code:null,object_id:intent.id,customer_id:String(params.customer),method_id:String(params.method_id),method_type:'card',livemode:intent.livemode,payment_state:intent.status,amount_minor:String(intent.amount),amount_received:String(intent.amount_received),amount_capturable:String(intent.amount_capturable),currency:intent.currency,request_id:providerId(intent.lastResponse?.requestId)?String(intent.lastResponse?.requestId):null};
      if(intent.status==='succeeded'){verifyCollectionCharge(p,intent,true);return {...result,outcome:'verified',charge_id:typeof intent.latest_charge==='object'&&intent.latest_charge?intent.latest_charge.id:null};}
      if(intent.amount_received!==0)throw new Error('identity_mismatch');
      if(intent.status==='requires_capture'&&short){const before=verifyCollectionCharge(p,intent,false)!;return {...result,outcome:'pending',capture_before:new Date(before).toISOString(),charge_id:typeof intent.latest_charge==='object'&&intent.latest_charge?intent.latest_charge.id:null};}
      if(intent.amount_capturable!==0)throw new Error('identity_mismatch');
      if(intent.status==='requires_action')return {...result,outcome:'requires_action'};
      if(intent.status==='requires_payment_method')return {...result,...failedIntentOutcome(intent)};
      if(['processing','requires_confirmation','canceled'].includes(intent.status))return {...result,outcome:'pending'};
      throw new Error('identity_mismatch');
    }catch{return observationJoint(p,'unknown');}
  }
  // A fixed adapter extends the sole shared SDK call catalog. It cannot capture, modify amount, replace a method or construct a second intent after an uncertain result.
  if(p.kind==='authorization.create'||p.kind==='authorization.cancel'){
    const h=p.hold_configuration!,params=p.parameters,creating=p.kind==='authorization.create';let holdResult=observationJoint(p,'unknown');
    try{
      const sdk=ownedSdk??createProviderClientJoint(p,provision,credential,transport).sdk,options={idempotencyKey:p.provider_key,maxNetworkRetries:0};
      // Only fields proved against the original immutable snapshot are retained; the SDK object, next_action and client_secret never enter the journal.
      const verify=(raw:HoldIntent)=>verifyOriginalHoldIntent(p,raw);
      let intent:HoldIntent;
      if(creating){
        try{intent=verify(await transport.run(()=>p.plan==='retrieve'?sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0}):sdk.paymentIntents.create({amount:Number(params.amount_minor),currency:String(params.currency),customer:String(params.customer),payment_method:String(params.method_id),capture_method:'manual',confirm:true,off_session:true,allowed_payment_method_types:['card'],metadata:params.metadata as Record<string,string>,expand:['latest_charge']},options)));}
        catch(error){const rejected=error as {type?:string;payment_intent?:HoldIntent};if(rejected.type!=='StripeCardError'||!rejected.payment_intent)throw error;intent=await resolveOriginalCreateDecline(p,rejected.payment_intent,sdk,transport);}
      }else{
        intent=verify(await transport.run(()=>sdk.paymentIntents.retrieve(String(params.payment_intent_id),{expand:['latest_charge']},{maxNetworkRetries:0})));
        // Original known-hold release is liability-reducing; it does not need new consent or a still-commercially-active creation policy.
        if(intent.status!=='canceled'&&p.plan==='effect'){
          if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
          if(intent.status!=='requires_capture')throw new Error('provider_unknown');
          intent=verify(await transport.run(()=>sdk.paymentIntents.cancel(intent.id,{expand:['latest_charge']},options)));
        }
      }
      if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
      holdResult={...holdResult,transport_outcome:'received',safe_error_code:null,object_id:intent.id,customer_id:String(params.customer),method_id:String(params.method_id),method_type:'card',livemode:intent.livemode,payment_state:intent.status,amount_minor:String(intent.amount),amount_capturable:String(intent.amount_capturable),currency:intent.currency,request_id:providerId(intent.lastResponse?.requestId)?String(intent.lastResponse?.requestId):null};
      if(intent.status==='requires_capture'){
        const charge=intent.latest_charge;
        if(!charge||typeof charge==='string'||charge.object!=='charge'||!/^ch_[A-Za-z0-9_]{1,240}$/.test(charge.id)||charge.payment_intent!==intent.id||charge.customer!==params.customer||charge.payment_method!==params.method_id||charge.amount!==intent.amount||charge.currency!==intent.currency||charge.livemode!==intent.livemode||charge.captured||charge.amount_captured!==0||charge.refunded||charge.amount_refunded!==0||!charge.paid||charge.status!=='succeeded'||charge.payment_method_details?.type!=='card')throw new Error('identity_mismatch');
        const seconds=charge.payment_method_details.card?.capture_before;
        if(!Number.isSafeInteger(seconds)||!seconds||seconds<1||!Number.isFinite(seconds*1000)||intent.amount_capturable!==intent.amount)throw new Error('identity_mismatch');
        const captureBefore=new Date(seconds*1000).toISOString();holdResult={...holdResult,charge_id:charge.id,capture_before:captureBefore,outcome:seconds*1000>Date.parse(h.original_due_at)+h.processing_buffer_seconds*1000&&seconds*1000>Date.now()?'verified':'pending'};
      }else if(intent.status==='canceled'){
        if(intent.amount_capturable!==0||intent.amount_received!==0)throw new Error('identity_mismatch');holdResult={...holdResult,outcome:'verified'};
      }else if(intent.status==='requires_action')holdResult={...holdResult,outcome:'requires_action'};
      else if(intent.status==='requires_payment_method')holdResult={...holdResult,...failedIntentOutcome(intent)};
      else if(intent.status==='requires_confirmation'||intent.status==='processing')holdResult={...holdResult,outcome:'pending'};
      else throw new Error('identity_mismatch');
      // A cancel observation can settle release only for an actually canceled original intent; an attached live hold stays unknown on recovery.
      if(!creating&&intent.status!=='canceled')return {...holdResult,outcome:'unknown',safe_error_code:'provider_unknown'};
      return holdResult;
    }catch{return observationJoint(p,'unknown');}
  }
  // A current accepted B0 subscription-purpose return adapter is required before Checkout credentials or I/O.
  const premiumReturn=p.kind==='subscription.create'&&p.plan==='effect'?await approvedPremiumReturnUrls(p,returnDispatch):null;
  if(p.kind==='subscription.create'&&p.plan==='effect'&&!premiumReturn)return observationJoint(p,'denied');
  if(p.kind==='subscription.create'||p.kind==='subscription.cancel') {
    let billingResult=observationJoint(p,'unknown');
    try {
      const sdk=ownedSdk??createProviderClientJoint(p,provision,credential,transport,Date.now(),premiumReturn).sdk,b=p.billing_configuration!,params=p.parameters;
      if(p.kind==='subscription.create'&&(Date.now()<Date.parse(b.effective_at)||Date.now()>=Date.parse(b.expires_at)))throw new Error('activation_closed');
      // New enrollment verifies the actual recurring SKU. Existing cancellation uses its immutable terms and known customer/subscription, even after commercial expiry or delisting.
      if(p.kind==='subscription.create'){
      const price=await transport.run(()=>sdk.prices.retrieve(b.price_id,undefined,{maxNetworkRetries:0}));
      const product=await transport.run(()=>sdk.products.retrieve(b.product_id,undefined,{maxNetworkRetries:0}));
      if(price.id!==b.price_id||!price.active||price.type!=='recurring'||price.currency!==b.currency||price.unit_amount!==b.unit_amount||price.product!==b.product_id||price.recurring?.interval!==b.interval||price.recurring.interval_count!==1||price.tax_behavior!==b.tax_behavior||price.livemode!==(p.configuration.environment==='live')||product.id!==b.product_id||!product.active||product.deleted||product.livemode!==(p.configuration.environment==='live')||Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
      }
      const options={idempotencyKey:p.provider_key,maxNetworkRetries:0};
      // The original Checkout effect uses only permit-bound protected SQL-approved fixed return URLs; URL delivery remains the accepted one-use owner return path.
      const raw=p.kind==='subscription.create'?await transport.run(()=>p.plan==='retrieve'?sdk.checkout.sessions.retrieve(p.object_id!,undefined,{maxNetworkRetries:0}):sdk.checkout.sessions.create({mode:'subscription',customer:String(params.customer),line_items:[{price:b.price_id,quantity:1}],metadata:params.metadata as Record<string,string>,subscription_data:{metadata:params.metadata as Record<string,string>},automatic_tax:{enabled:false},success_url:premiumReturn!.success_url,cancel_url:premiumReturn!.cancel_url},options)):await transport.run(()=>p.plan==='retrieve'?sdk.subscriptions.retrieve(String(params.subscription_id),undefined,{maxNetworkRetries:0}):sdk.subscriptions.update(String(params.subscription_id),{cancel_at_period_end:true},options));
      if(raw.customer!==params.customer||raw.livemode!==(p.configuration.environment==='live')||!billingObjectId(p.object_kind!,raw.id)||p.object_id&&raw.id!==p.object_id||raw.lastResponse.apiVersion&&raw.lastResponse.apiVersion!==p.configuration.api_version)throw new Error('identity_mismatch');
      billingResult={...billingResult,outcome:'verified',transport_outcome:'received',safe_error_code:null,object_id:raw.id,customer_id:String(params.customer),livemode:raw.livemode,request_id:providerId(raw.lastResponse.requestId)?raw.lastResponse.requestId:null};
      if(p.kind==='subscription.create') {
        const session=raw as import('stripe').Stripe.Checkout.Session;
        if(session.object!=='checkout.session'||session.mode!=='subscription'||session.metadata?.ante_operation!==p.operation_id||session.metadata?.ante_subscription!==p.subject_id||!['open','complete','expired'].includes(String(session.status)))throw new Error('identity_mismatch');
        // Completion is recorded lineage only. It never creates a paid interval or delivers an unaccepted browser URL.
        billingResult={...billingResult,checkout_state:session.status as 'open'|'complete'|'expired',provider_subscription_id:typeof session.subscription==='string'&&billingObjectId('subscription',session.subscription)?session.subscription:null};
      }else {
        const subscription=raw as import('stripe').Stripe.Subscription;
        if(subscription.object!=='subscription'||subscription.id!==params.subscription_id||!subscription.cancel_at_period_end)throw new Error('identity_mismatch');
        billingResult={...billingResult,provider_subscription_id:subscription.id,cancel_at_period_end:true,subscription_state:subscription.status};
      }
      return billingResult;
    }catch{return observationJoint(p,'unknown');}
  }
  let result = observationJoint(p, "unknown");
  try {
    const sdk = ownedSdk??createProviderClientJoint(p, provision, credential, transport).sdk,
      params = p.parameters,
      c = p.configuration;
    const options = { idempotencyKey: p.provider_key, maxNetworkRetries: 0 };
    let raw: unknown;
    if (p.kind === "customer.create") {
      if (!exact(params, ["metadata"])) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        p.plan === "retrieve"
          ? sdk.customers.retrieve(p.object_id!, undefined, {
            maxNetworkRetries: 0,
          })
          : sdk.customers.create({
            metadata: params.metadata as Record<string, string>,
          }, options)
      );
    } else if (p.kind === "setup.create") {
      if (
        !exact(params, [
          "customer",
          "usage",
          "allowed_payment_method_types",
          "payment_method_configuration",
          "metadata",
        ]) || params.usage !== "off_session" ||
        JSON.stringify(params.allowed_payment_method_types) !== '["card"]' ||
        params.payment_method_configuration !== c.method_configuration
      ) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        p.plan === "retrieve"
          ? sdk.setupIntents.retrieve(p.object_id!, undefined, {
            maxNetworkRetries: 0,
          })
          : sdk.setupIntents.create({
            customer: String(params.customer),
            usage: "off_session",
            allowed_payment_method_types: ["card"],
            metadata: params.metadata as Record<string, string>,
          }, options)
      );
    } else if (p.kind === "setup.retrieve") {
      if (
        !exact(params, ["setup_id", "customer", "payment_method_configuration"])
      ) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        sdk.setupIntents.retrieve(String(params.setup_id), undefined, {
          maxNetworkRetries: 0,
        })
      );
    } else if (p.kind === "customer.default") {
      if (
        !exact(params, ["customer", "invoice_settings"]) ||
        c.default_policy !== "invoice"
      ) throw new Error("identity_mismatch");
      const desired = params.invoice_settings as {
        default_payment_method: string;
      };
      if (
        !exact(desired, ["default_payment_method"]) ||
        !providerId(desired.default_payment_method)
      ) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        p.plan === "retrieve"
          ? sdk.customers.retrieve(String(params.customer), undefined, {
            maxNetworkRetries: 0,
          })
          : sdk.customers.update(String(params.customer), {
            invoice_settings: desired,
          }, options)
      );
    } else {
      if (
        !exact(params, ["method_id", "customer"]) ||
        c.removal_policy !== "block_dependencies"
      ) throw new Error("identity_mismatch");
      const original = await transport.run(() =>
        sdk.paymentMethods.retrieve(String(params.method_id), undefined, {
          maxNetworkRetries: 0,
        })
      );
      if (
        original.id !== params.method_id || original.type !== "card" ||
        original.livemode !== (c.environment === "live") ||
        original.customer !== params.customer && original.customer !== null
      ) throw new Error("identity_mismatch");
      // Reconciliation never re-detaches an attached target after an uncertain/expired-key write.
      // The same recorded method can only be observed detached; unresolved attachment stays unknown.
      if (p.plan === "retrieve" && original.customer !== null) {
        throw new Error("provider_unknown");
      }
      raw = original.customer === null
        ? original
        : await transport.run(() =>
          sdk.paymentMethods.detach(String(params.method_id), {}, options)
        );
    }
    if (!raw || typeof raw !== "object") throw new Error("identity_mismatch");
    const object = raw as Record<string, unknown>;
    if (
      !providerId(object.id) || object.deleted ||
      object.livemode !== (c.environment === "live")
    ) throw new Error("identity_mismatch");
    if (p.object_id && object.id !== p.object_id) {
      throw new Error("identity_mismatch");
    }
    result = {
      ...result,
      outcome: "verified",
      transport_outcome: "received",
      safe_error_code: null,
      object_id: String(object.id),
      livemode: Boolean(object.livemode),
    };
    // Header absence cannot establish merchant identity: trusted provisioning was checked before I/O.
    const last = object.lastResponse as {
      requestId?: string;
      apiVersion?: string;
    } | undefined;
    if (last?.apiVersion && last.apiVersion !== c.api_version) {
      throw new Error("identity_mismatch");
    }
    if (providerId(last?.requestId)) result.request_id = last!.requestId!;
    if (p.kind === "customer.create") {
      const metadata = object.metadata as Record<string, string>;
      if (
        object.object !== "customer" ||
        metadata?.ante_operation !== p.operation_id ||
        metadata?.ante_customer !== p.customer_id
      ) throw new Error("identity_mismatch");
    } else if (p.kind === "customer.default") {
      const settings = object.invoice_settings as Record<string, unknown>;
      if (
        object.object !== "customer" || object.id !== params.customer ||
        settings?.default_payment_method !==
          (params.invoice_settings as Record<string, unknown>)
            .default_payment_method
      ) throw new Error("identity_mismatch");
      result.customer_id = String(params.customer);
      result.default_method_id = String(settings.default_payment_method);
    } else if (p.kind === "card.detach") {
      if (
        object.object !== "payment_method" || object.id !== params.method_id ||
        object.type !== "card" || object.customer !== null
      ) throw new Error("identity_mismatch");
      result.method_type = "card";
    } else {
      verifyExplicitCardMethodSet(object);
      if (
        object.object !== "setup_intent" ||
        object.customer !== params.customer || object.usage !== "off_session"
      ) throw new Error("identity_mismatch");
      if (p.kind === "setup.create") {
        const metadata = object.metadata as Record<string, string>;
        if (
          !exact(metadata,['ante_operation','ante_setup']) || metadata?.ante_operation !== p.operation_id ||
          metadata?.ante_setup !== p.subject_id
        ) throw new Error("identity_mismatch");
      }
      result.customer_id = String(params.customer);
      result.usage = "off_session";
      // Preserve the approved internal configuration tuple separately; Stripe did not apply a method configuration to this explicit-card intent.
      result.method_configuration = null;
      switch (object.status) {
        case "succeeded": {
          if (
            p.kind !== "setup.retrieve" || !providerId(object.payment_method)
          ) throw new Error("identity_mismatch");
          const method = await transport.run(() =>
            sdk.paymentMethods.retrieve(
              String(object.payment_method),
              undefined,
              { maxNetworkRetries: 0 },
            )
          );
          if (
            method.id !== object.payment_method || method.type !== "card" ||
            method.customer !== params.customer ||
            method.livemode !== (c.environment === "live") || !method.card ||
            !/^[0-9]{4}$/.test(method.card.last4) ||
            !/^[a-z_]{1,32}$/.test(method.card.brand) ||
            method.card.exp_month < 1 || method.card.exp_month > 12 ||
            method.card.exp_year < 2000 || method.card.exp_year > 2200
          ) throw new Error("identity_mismatch");
          result = {
            ...result,
            setup_state: "succeeded",
            method_id: method.id,
            method_type: "card",
            brand: method.card.brand,
            last4: method.card.last4,
            expiry_month: method.card.exp_month,
            expiry_year: method.card.exp_year,
          };
          break;
        }
        case "requires_action":
          result = {
            ...result,
            outcome: "requires_action",
            setup_state: "requires_action",
          };
          break;
        case "canceled":
          result = { ...result, outcome: "pending", setup_state: "canceled" };
          break;
        case "requires_payment_method":
          if (object.last_setup_error) {
            result = observationJoint(p, "declined");
            result.safe_error_code = "provider_declined";
          } else {result = {
              ...result,
              outcome: "pending",
              setup_state: "pending",
            };}
          break;
        case "requires_confirmation":
        case "processing":
          result = { ...result, outcome: "pending", setup_state: "pending" };
          break;
        default:
          throw new Error("identity_mismatch");
      }
    }
    return result;
  } catch {
    return observationJoint(p, "unknown");
  }
}
// DB dispatch binds the exact claimed plan/object before credential/client construction.
// Changed reconciliation denies the claim; local recording failure stays unknown.
// The caller owns quiescence separately; logical return cannot authorize a second physical effect.
export async function dispatchProviderJoint(
  repository: ProviderRepositoryJoint,
  permit: Permit | NoticePermit,
  provision: Provisioning,
  credential: () => string,
  transport: GuardedTransport,
  returnDispatch: PremiumReturnDispatch | null = null,
) {
  if(permit.kind==='webhook.retrieve')permit=parseNoticePermit(permit);
  if (!await (permit.kind==='webhook.retrieve'?repository.recordNoticeDispatch(permit):repository.recordDispatch(permit))) {
    return { status: "denied" as const };
  }
  const result = permit.kind==='webhook.retrieve'?await executeProviderJoint(permit,provision,credential,transport):await executeProviderJoint(permit,provision,credential,transport,returnDispatch);
  try {
    if(permit.kind==='webhook.retrieve'){const recorded=await repository.recordNoticeObservation(permit,result as CanonicalNotice);if(exact(recorded,['status'])&&(recorded as {status:string}).status==='recorded')return await repository.reconcileNotice(permit);return recorded;}return await repository.recordObservation(permit,result as Observation);
  } catch {
    return { status: "unknown" as const };
  }
}

// Only a one-use long-collection-purpose repository ticket may expose the original PaymentIntent secret, after final owner/context consumption. The HTTP purpose adapter is separately approved; this source does not install one.
export async function readLongCollectionContinuationJoint(repository:ProviderRepositoryJoint,commitmentId:string,revision:number,provision:Provisioning,credential:()=>string,transport:GuardedTransport){
 try{
  const ctx=await repository.collectionContinuation(commitmentId,revision);if(!ctx)return null;
  const p=ctx.permit,{sdk}=createProviderClientJoint(p,provision,credential,transport);
  const intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0})));
  if(!(intent.status==='requires_action'||originalCardAuthenticationRequired(intent))||intent.amount_received!==0||intent.amount_capturable!==0||!intent.client_secret||!intent.client_secret.startsWith(intent.id+'_secret_')||!/^[A-Za-z0-9_-]{1,512}$/.test(intent.client_secret)||Date.now()>=Date.parse(ctx.ticket.expires_at)||!await repository.consumeCollectionContinuation(ctx)||Date.now()>=Date.parse(ctx.ticket.expires_at))return null;
  // Secrets exist only in this protected transient return, never ordinary DTOs, journals, errors or logs. A returned action does not provide backing or task finality.
  return {...(originalCardAuthenticationRequired(intent)?{action_mode:'confirm_original_card' as const,method_id:String(p.parameters.method_id)}:{}),purpose:'task.long_collection.continue' as const,commitment_id:commitmentId,commitment_revision:revision,provider_intent_id:intent.id,client_secret:intent.client_secret,expires_at:ctx.ticket.expires_at,return_route_key:'account_payments' as const};
 }catch{return null;}
}
// The original-intent verifier below is shared with hold/release/continuation. Collection additionally verifies the same expanded Charge, full received amount and absence of refunds.
function verifyCollectionCharge(p:Permit,intent:HoldIntent,captured:boolean):number|null{
 const charge=intent.latest_charge,amount=Number(p.parameters.amount_minor);
 if(!charge||typeof charge==='string'||charge.object!=='charge'||!/^ch_[A-Za-z0-9_]{1,240}$/.test(charge.id)||charge.payment_intent!==intent.id||charge.customer!==p.parameters.customer||charge.payment_method!==p.parameters.method_id||charge.amount!==amount||charge.currency!==p.parameters.currency||charge.livemode!==intent.livemode||charge.refunded||charge.amount_refunded!==0||!charge.paid||charge.status!=='succeeded'||charge.payment_method_details?.type!=='card'||charge.captured!==captured||charge.amount_captured!==(captured?amount:0))throw new Error('identity_mismatch');
 if(captured){if(intent.amount_received!==amount||intent.amount_capturable!==0)throw new Error('identity_mismatch');return null;}
 const seconds=charge.payment_method_details.card?.capture_before;
 if(!Number.isSafeInteger(seconds)||!seconds||seconds<1||intent.amount_received!==0||intent.amount_capturable!==amount)throw new Error('identity_mismatch');return seconds*1000;
}
// A CREATE issuer error may carry only its original failed charge ID despite
// requesting expansion. Read that same in-memory intent once under the original
// lease and guarded one-request scope, never repeat POST or select a new card.
// All raw identity/card/zero-money gates run before GET; the original charge
// pointer must equal the fully verified failed expanded charge afterwards.
async function resolveOriginalCreateDecline(p:Permit,raw:HoldIntent,sdk:OwnedOriginalSdk,transport:GuardedTransport):Promise<HoldIntent>{
 if(typeof raw.latest_charge!=='string')return verifyOriginalHoldIntent(p,raw);
 const error=raw.last_payment_error,chargeId=raw.latest_charge;
 if(p.plan!=='effect'||!['authorization.create','collection.create'].includes(p.kind)||!/^ch_[A-Za-z0-9_]{1,240}$/.test(chargeId)||error?.type!=='card_error'||error.code!=='card_declined'||typeof error.decline_code!=='string'||!error.decline_code||originalCardAuthenticationRequired(raw))throw Error('identity_mismatch');
 // A null charge is used only for complete pre-read verification of every
 // non-expansion field; the actual pointer remains mandatory and unchanged.
 const original=verifyOriginalHoldIntent(p,{...raw,latest_charge:null});
 verifyOriginalFailedCard(p,original);
 if(Date.now()>=Date.parse(p.lease_expires_at))throw Error('identity_mismatch');
 const canonical=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(original.id,{expand:['latest_charge']},{maxNetworkRetries:0})));
 if(Date.now()>=Date.parse(p.lease_expires_at)||canonical.id!==original.id||typeof canonical.latest_charge!=='object'||canonical.latest_charge===null||canonical.latest_charge.id!==chargeId||canonical.last_payment_error?.type!=='card_error'||canonical.last_payment_error.code!==error.code||canonical.last_payment_error.decline_code!==error.decline_code||originalCardAuthenticationRequired(canonical))throw Error('identity_mismatch');
 verifyOriginalFailedCard(p,canonical);
 return canonical;
}
// Stripe LastPaymentError is a diagnostic structure, not a resource with an
// object discriminator. A detached failed method is usable only as identity
// evidence for this original zero-money failed intent, never as charge authority.
function verifyOriginalFailedCard(p:Permit,raw:HoldIntent):void{
 const error=raw.last_payment_error,method=error?.payment_method,charge=raw.latest_charge;
 if(raw.status!=='requires_payment_method'||raw.amount_received!==0||raw.amount_capturable!==0||!error||error.type!=='card_error'||!method||typeof method!=='object'||method.object!=='payment_method'||method.id!==p.parameters.method_id||method.customer!==p.parameters.customer||method.livemode!==raw.livemode||method.type!=='card')throw new Error('identity_mismatch');
 // A failed expanded charge may exist; every original identity and zero-money
 // field is checked so a paid, held, refunded or foreign charge cannot be hidden.
 if(charge!==null&&(!charge||typeof charge!=='object'||charge.object!=='charge'||!/^ch_[A-Za-z0-9_]{1,240}$/.test(charge.id)||charge.payment_intent!==raw.id||charge.customer!==p.parameters.customer||charge.payment_method!==p.parameters.method_id||charge.livemode!==raw.livemode||charge.amount!==raw.amount||charge.currency!==raw.currency||charge.paid!==false||charge.status!=='failed'||charge.captured!==false||charge.amount_captured!==0||charge.refunded!==false||charge.amount_refunded!==0||charge.payment_method_details?.type!=='card'))throw new Error('identity_mismatch');
}
// A shared finite authentication diagnostic is used by projection and transient
// continuation. A conflicting decline code cannot authorize confirmation.
function originalCardAuthenticationRequired(raw:HoldIntent):boolean{
 const error=raw.last_payment_error;
 return raw.status==='requires_payment_method'&&error?.type==='card_error'&&(error.code==='authentication_required'&&(error.decline_code===undefined||error.decline_code==='authentication_required')||error.code==='card_declined'&&error.decline_code==='authentication_required');
}
// The same diagnostic mapping serves hold and collection observations. Explicit
// off-session authentication failure requests fresh customer action, while the
// provider state remains requires_payment_method and supplies no paid authority.
function failedIntentOutcome(raw:HoldIntent):Pick<Observation,'outcome'|'safe_error_code'>{
 const authentication=originalCardAuthenticationRequired(raw);
 return authentication?{outcome:'requires_action',safe_error_code:'provider_authentication_required'}:raw.last_payment_error?{outcome:'declined',safe_error_code:'provider_declined'}:{outcome:'pending',safe_error_code:null};
}
// The same original-intent verifier serves journal observations and transient owner continuation; no alternate identity interpretation is permitted.
type HoldIntent=import('stripe').Stripe.PaymentIntent & {lastResponse?:{apiVersion?:string;requestId?:string}};
function verifyOriginalHoldIntent(p:Permit,raw:HoldIntent):HoldIntent{
 const params=p.parameters,collection=p.kind==='authorization.capture'||p.kind==='collection.create',h=p.hold_configuration,creating=p.kind==='authorization.create'||p.kind==='collection.create',originalOperation=collection?p.collection_configuration!.original_operation_id:h!.authorization_operation_id;
        if(raw.object!=='payment_intent'||!holdObjectId(raw.id)||p.object_id&&raw.id!==p.object_id||!creating&&raw.id!==params.payment_intent_id||raw.customer!==params.customer||raw.livemode!==(p.configuration.environment==='live')||raw.amount!==Number(params.amount_minor)||raw.currency!==params.currency||raw.capture_method!==(p.kind==='collection.create'?'automatic':'manual')||raw.confirmation_method!=='automatic'||!exact(raw.metadata,['ante_operation','ante_commitment'])||raw.metadata?.ante_commitment!==p.subject_id||raw.metadata?.ante_operation!==originalOperation||raw.lastResponse?.apiVersion&&raw.lastResponse.apiVersion!==p.configuration.api_version)throw new Error('identity_mismatch');
        verifyExplicitCardMethodSet(raw);
        // Top-level identity stays mandatory for paid, reserved and action states.
        // Only original creation/retrieval failures can qualify the nested method.
        if(raw.payment_method!==params.method_id){
         if(raw.payment_method!==null||!creating)throw new Error('identity_mismatch');
         verifyOriginalFailedCard(p,raw);
        }else if(raw.status==='requires_payment_method'&&(raw.last_payment_error?.payment_method||originalCardAuthenticationRequired(raw))){verifyOriginalFailedCard(p,raw);}
        if(['requires_payment_method','requires_action','requires_confirmation','processing','canceled'].includes(raw.status)&&(raw.amount_received!==0||raw.amount_capturable!==0))throw new Error('identity_mismatch');
        return raw;
      
}
// Only a one-use hold-purpose repository ticket may expose the original PaymentIntent secret, after final owner/context consumption. The HTTP purpose adapter is separately approved; this source does not install one.
export async function readShortHoldContinuationJoint(repository:ProviderRepositoryJoint,commitmentId:string,revision:number,provision:Provisioning,credential:()=>string,transport:GuardedTransport){
 try{
  const ctx=await repository.holdContinuation(commitmentId,revision);if(!ctx)return null;
  const p=ctx.permit,{sdk}=createProviderClientJoint(p,provision,credential,transport);
  const intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0})));
  if(!(intent.status==='requires_action'||originalCardAuthenticationRequired(intent))||intent.amount_received!==0||intent.amount_capturable!==0||!intent.client_secret||!intent.client_secret.startsWith(intent.id+'_secret_')||!/^[A-Za-z0-9_-]{1,512}$/.test(intent.client_secret)||Date.now()>=Date.parse(ctx.ticket.expires_at)||!await repository.consumeHoldContinuation(ctx)||Date.now()>=Date.parse(ctx.ticket.expires_at))return null;
  // Secrets exist only in this protected transient return, never ordinary DTOs, journals, errors or logs. A returned action does not provide backing or task finality.
  return {...(originalCardAuthenticationRequired(intent)?{action_mode:'confirm_original_card' as const,method_id:String(p.parameters.method_id)}:{}),purpose:'task.short_hold.continue' as const,commitment_id:commitmentId,commitment_revision:revision,provider_intent_id:intent.id,client_secret:intent.client_secret,expires_at:ctx.ticket.expires_at,return_route_key:'account_payments' as const};
 }catch{return null;}
}
// Ephemeral owner continuation retrieves only a recorded SetupIntent under a persisted one-use ticket.
// No secret reaches observationJoints/history/logs; local expiry does not invalidate Stripe's secret.
export async function readProviderContinuationJoint(
  repository: ProviderRepositoryJoint,
  setupId: string,
  revision: number,
  provision: Provisioning,
  credential: () => string,
  transport: GuardedTransport,
) {
  try {
    const ctx = await repository.continuation(setupId, revision);
    if (!ctx) return null;
    const p = ctx.permit, c = p.configuration;
    const { sdk } = createProviderClientJoint(p, provision, credential, transport);
    const setup = await transport.run(() =>
      sdk.setupIntents.retrieve(p.object_id!, undefined, {
        maxNetworkRetries: 0,
      })
    );
    // The owner continuation uses the same explicit-card verifier as durable observations; no alternate configuration echo can release a secret.
    verifyExplicitCardMethodSet(setup);
    if (
      setup.id !== p.object_id || setup.customer !== p.parameters.customer ||
      setup.livemode !== (c.environment === "live") ||
      setup.usage !== "off_session" ||
      !["requires_action", "requires_confirmation", "requires_payment_method"]
        .includes(setup.status) ||
      !exact(setup.metadata,['ante_operation','ante_setup']) || setup.metadata?.ante_operation !== p.operation_id ||
      setup.metadata?.ante_setup !== p.subject_id || !setup.client_secret ||
      !/^[A-Za-z0-9_-]{1,512}$/.test(setup.client_secret) ||
      Date.now() >= Date.parse(ctx.ticket.expires_at) ||
      !await repository.consumeContinuation(ctx)
    ) return null;
    return {
      operation_id: p.operation_id,
      operation_revision: p.operation_revision,
      setup_id: setupId,
      setup_revision: revision,
      client_secret: setup.client_secret,
      expires_at: ctx.ticket.expires_at,
      return_route_key: "account_payments" as const,
    };
  } catch {
    return null;
  }
}
