// Exact additive contract parser rejects coercion, unknown keys and untyped financial authority.
import assert from 'node:assert/strict';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const hash=/^[0-9a-f]{64}$/;
const fields={quote:'operation_id task_id task_revision configuration_id configuration_revision card_id card_revision customer_revision consent_id consent_revision amount_minor currency affirmative',admit:'operation_id quote_id quote_hash task_revision card_revision customer_revision consent_revision configuration_revision affirmative',appeal:'operation_id commitment_id commitment_revision outcome_id outcome_revision outcome_hash asset_ids reason',dispute:'operation_id commitment_id commitment_revision outcome_id outcome_revision outcome_hash asset_ids reason',vote:'operation_id case_id case_revision choice reason',ack:'operation_id notice_id',recover:'operation_id'};
// Plain objects must contain exactly the reviewed keys, including no symbol or prototype additions.
function exact(value,keys){assert.ok(value&&Object.getPrototypeOf(value)===Object.prototype);assert.deepEqual(Reflect.ownKeys(value).sort(),keys.split(' ').sort());}
// Validate action-bound request types and safe integer/minor-unit bounds before copying caller input.
export function parseCommitmentRequest(action,input){assert.ok(Object.hasOwn(fields,action));exact(input,fields[action]);for(const [k,v]of Object.entries(input)){if(k.endsWith('_id'))assert.match(v,uuid);else if(k.endsWith('_hash'))assert.match(v,hash);else if(k.endsWith('_revision'))assert.ok(Number.isSafeInteger(v)&&v>=1&&v<=2147483647);else if(k==='amount_minor'){assert.equal(typeof v,'string');assert.match(v,/^[1-9][0-9]{0,15}$/);assert.ok(BigInt(v)<=9007199254740991n);}else if(k==='currency')assert.match(v,/^[A-Z]{3}$/);else if(k==='affirmative')assert.equal(typeof v,'boolean');else if(k==='asset_ids'){assert.ok(Array.isArray(v)&&v.length<=5&&new Set(v).size===v.length);for(const id of v)assert.match(id,uuid);}else if(k==='choice')assert.ok(['approved','denied'].includes(v));else if(k==='reason')assert.ok(typeof v==='string'&&v.trim()===v&&v.length>0&&Buffer.byteLength(v)<=4096);}return structuredClone(input);}
// Validate the exact receipt and nested authority while preserving immutable original/current revisions.
export function parseCommitmentReceipt(input){exact(input,'commitment_contract_version operation_id operation_revision status result error_code retry_after_seconds');assert.equal(input.commitment_contract_version,1);if(input.operation_id!==null)assert.match(input.operation_id,uuid);assert.ok(input.operation_revision===null||Number.isSafeInteger(input.operation_revision)&&input.operation_revision>=1&&input.operation_revision<=2147483647);assert.ok(['completed','pending','denied','conflict','unknown'].includes(input.status));assert.ok(input.error_code===null||['invalid_input','configuration_missing','constructor_missing','not_found','revision_conflict','payload_conflict','rate_limited','policy_changed','dependency_open','notice_missing','authority_missing','appeal_pending','adapter_missing'].includes(input.error_code));assert.ok(input.retry_after_seconds===null||Number.isInteger(input.retry_after_seconds)&&input.retry_after_seconds>=1&&input.retry_after_seconds<=60);assert.ok(input.result===null||input.status==='completed'||input.status==='pending'||input.status==='unknown');if(input.result!==null&&input.result.authority_kind==='financial-commitment-view-v1'){parseCommitmentView(input.result);}else if(input.result!==null){exact(input.result,'authority_kind resource_id revision state amount_minor currency');assert.equal(input.result.authority_kind,'financial-commitment-v1');assert.match(input.result.resource_id,uuid);assert.ok(Number.isSafeInteger(input.result.revision)&&input.result.revision>=1&&input.result.revision<=2147483647);assert.ok(['quoted','admitted','appeal_pending','dispute_pending','acknowledged','held'].includes(input.result.state));if(input.result.amount_minor!==null){assert.match(input.result.amount_minor,/^[1-9][0-9]{0,15}$/);assert.ok(BigInt(input.result.amount_minor)<=9007199254740991n);assert.match(input.result.currency,/^[A-Z]{3}$/);}else assert.equal(input.result.currency,null);}return structuredClone(input);}
// Owner views expose orthogonal financial/proof identities without provider IDs or network permits.
export function parseCommitmentView(input){exact(input,'authority_kind commitment_id task_id revision amount_minor currency started_at funding_state outcome cases finality');assert.equal(input.authority_kind,'financial-commitment-view-v1');for(const k of ['commitment_id','task_id'])assert.match(input[k],uuid);assert.ok(Number.isSafeInteger(input.revision)&&input.revision>=1&&input.revision<=2147483647);assert.match(input.amount_minor,/^[1-9][0-9]{0,15}$/);assert.ok(BigInt(input.amount_minor)<=9007199254740991n);assert.match(input.currency,/^[A-Z]{3}$/);assert.ok(input.started_at===null||typeof input.started_at==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$/.test(input.started_at)&&Number.isFinite(Date.parse(input.started_at)));assert.ok([null,'pending','authorized','active_unsecured','requires_action','unknown','declined','expired_unsecured'].includes(input.funding_state));if(input.outcome!==null){exact(input.outcome,'authority_kind outcome_id outcome_revision outcome_hash outcome proof_resolution_id proof_resolution_revision proof_resolution_hash');assert.equal(input.outcome.authority_kind,'financial-ledger-binding-v1');assert.match(input.outcome.outcome_id,uuid);assert.equal(input.outcome.outcome_revision,1);assert.equal(input.outcome.proof_resolution_revision,1);assert.match(input.outcome.proof_resolution_id,uuid);assert.match(input.outcome.outcome_hash,hash);assert.match(input.outcome.proof_resolution_hash,hash);assert.ok(['completed','failed'].includes(input.outcome.outcome));}assert.ok(Array.isArray(input.cases)&&input.cases.length<=2);for(const ca of input.cases){exact(ca,'case_id kind state');assert.match(ca.case_id,uuid);assert.ok(['appeal','issuer_dispute'].includes(ca.kind));assert.ok(['reviewer_pending','ante_pending','approved','denied','dispute_pending'].includes(ca.state));}if(input.finality!==null){exact(input.finality,'finality_id action financial_dispatch');assert.match(input.finality.finality_id,uuid);assert.ok(['release','collect'].includes(input.finality.action));assert.equal(input.finality.financial_dispatch,false);}return structuredClone(input);}
