// GENERATED finite Task12 successor from accepted96b8 V3; edit only the builder.
// GENERATED from accepted V2 by closed-web-payment-short-holds/build.mjs; change only the finite transform.
// GENERATED by closed-web-payment-subscriptions/build.mjs from pinned accepted V1; edit the finite transform.
import {
  exact,
  type Observation,
  observationV4,
  type Permit,
  providerId,
  billingObjectId,
  holdObjectId,
} from "./webPaymentProviderContractV4.ts";
import {
  createProviderClientV4,
  type GuardedTransport,
  type Provisioning,
} from "./webPaymentProviderClientV4.ts";
import type { ProviderRepositoryV4 } from "./webPaymentProviderRepositoryV4.ts";
// Only this fixed operation adapter touches the guarded private SDK; no arbitrary SDK proxy is exposed.
export async function executeProviderV4(
  p: Permit,
  provision: Provisioning,
  credential: () => string,
  transport: GuardedTransport,
): Promise<Observation> {
  // Financial dispatch consumes an authoritative finality job already fenced by SQL. Short capture uses the same live manual intent; long create is a single immutable off-session collection keyed by that job.
  if(p.kind==='authorization.capture'||p.kind==='collection.create'){
    const short=p.kind==='authorization.capture',params=p.parameters,c=p.collection_configuration!;let result=observationV4(p,'unknown');
    try{
      const {sdk}=createProviderClientV4(p,provision,credential,transport),options={idempotencyKey:p.provider_key,maxNetworkRetries:0};let intent:HoldIntent;
      if(short){
        intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(String(params.payment_intent_id),{expand:['latest_charge']},{maxNetworkRetries:0})));
        if(intent.status==='requires_capture'&&p.plan==='effect'){
          const captureBefore=verifyCollectionCharge(p,intent,false)!;
          if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
          if(captureBefore>Date.now()+c.processing_buffer_seconds*1000){
          // Full original amount only, one final capture. No amount amendments, incremental or repeated capture options exist.
          intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.capture(intent.id,{amount_to_capture:Number(params.amount_minor),final_capture:true,expand:['latest_charge']},options)));
          }
          // A known expired/cutoff hold is observed truthfully below without dispatching capture or replacement.
        }
      }else{
        try{intent=verifyOriginalHoldIntent(p,await transport.run(()=>p.plan==='retrieve'?sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0}):sdk.paymentIntents.create({amount:Number(params.amount_minor),currency:String(params.currency),customer:String(params.customer),payment_method:String(params.method_id),capture_method:'automatic',confirm:true,off_session:true,allowed_payment_method_types:['card'],payment_method_configuration:p.configuration.method_configuration,metadata:params.metadata as Record<string,string>,expand:['latest_charge']},options)));}
        catch(error){const rejected=error as {type?:string;payment_intent?:HoldIntent};if(rejected.type!=='StripeCardError'||!rejected.payment_intent)throw error;intent=verifyOriginalHoldIntent(p,rejected.payment_intent);}
      }
      if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
      result={...result,transport_outcome:'received',safe_error_code:null,object_id:intent.id,customer_id:String(params.customer),method_id:String(params.method_id),method_type:'card',livemode:intent.livemode,payment_state:intent.status,amount_minor:String(intent.amount),amount_received:String(intent.amount_received),amount_capturable:String(intent.amount_capturable),currency:intent.currency,request_id:providerId(intent.lastResponse?.requestId)?String(intent.lastResponse?.requestId):null};
      if(intent.status==='succeeded'){verifyCollectionCharge(p,intent,true);return {...result,outcome:'verified',charge_id:typeof intent.latest_charge==='object'&&intent.latest_charge?intent.latest_charge.id:null};}
      if(intent.amount_received!==0)throw new Error('identity_mismatch');
      if(intent.status==='requires_capture'&&short){const before=verifyCollectionCharge(p,intent,false)!;return {...result,outcome:'pending',capture_before:new Date(before).toISOString(),charge_id:typeof intent.latest_charge==='object'&&intent.latest_charge?intent.latest_charge.id:null};}
      if(intent.amount_capturable!==0)throw new Error('identity_mismatch');
      if(intent.status==='requires_action')return {...result,outcome:'requires_action'};
      if(intent.status==='requires_payment_method')return {...result,outcome:intent.last_payment_error?'declined':'pending',safe_error_code:intent.last_payment_error?'provider_declined':null};
      if(['processing','requires_confirmation','canceled'].includes(intent.status))return {...result,outcome:'pending'};
      throw new Error('identity_mismatch');
    }catch{return observationV4(p,'unknown');}
  }
  // A fixed adapter extends the sole shared SDK call catalog. It cannot capture, modify amount, replace a method or construct a second intent after an uncertain result.
  if(p.kind==='authorization.create'||p.kind==='authorization.cancel'){
    const h=p.hold_configuration!,params=p.parameters,creating=p.kind==='authorization.create';let holdResult=observationV4(p,'unknown');
    try{
      const {sdk}=createProviderClientV4(p,provision,credential,transport),options={idempotencyKey:p.provider_key,maxNetworkRetries:0};
      // Only fields proved against the original immutable snapshot are retained; the SDK object, next_action and client_secret never enter the journal.
      const verify=(raw:HoldIntent)=>verifyOriginalHoldIntent(p,raw);
      let intent:HoldIntent;
      if(creating){
        try{intent=verify(await transport.run(()=>p.plan==='retrieve'?sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0}):sdk.paymentIntents.create({amount:Number(params.amount_minor),currency:String(params.currency),customer:String(params.customer),payment_method:String(params.method_id),capture_method:'manual',confirm:true,off_session:true,allowed_payment_method_types:['card'],payment_method_configuration:p.configuration.method_configuration,metadata:params.metadata as Record<string,string>,expand:['latest_charge']},options)));}
        catch(error){const rejected=error as {type?:string;payment_intent?:HoldIntent};if(rejected.type!=='StripeCardError'||!rejected.payment_intent)throw error;intent=verify(rejected.payment_intent);}
      }else{
        intent=verify(await transport.run(()=>sdk.paymentIntents.retrieve(String(params.payment_intent_id),{expand:['latest_charge']},{maxNetworkRetries:0})));
        // Original known-hold release is liability-reducing; it does not need new consent or a still-commercially-active creation policy.
        if(intent.status!=='canceled'&&p.plan==='effect'){
          if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
          if(intent.status!=='requires_capture')throw new Error('provider_unknown');
          intent=verify(await transport.run(()=>sdk.paymentIntents.cancel(intent.id,{expand:['latest_charge']},options)));
        }
      }
      if(Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
      holdResult={...holdResult,transport_outcome:'received',safe_error_code:null,object_id:intent.id,customer_id:String(params.customer),method_id:String(params.method_id),method_type:'card',livemode:intent.livemode,payment_state:intent.status,amount_minor:String(intent.amount),amount_capturable:String(intent.amount_capturable),currency:intent.currency,request_id:providerId(intent.lastResponse?.requestId)?String(intent.lastResponse?.requestId):null};
      if(intent.status==='requires_capture'){
        const charge=intent.latest_charge;
        if(!charge||typeof charge==='string'||charge.object!=='charge'||!/^ch_[A-Za-z0-9_]{1,240}$/.test(charge.id)||charge.payment_intent!==intent.id||charge.customer!==params.customer||charge.payment_method!==params.method_id||charge.amount!==intent.amount||charge.currency!==intent.currency||charge.livemode!==intent.livemode||charge.captured||charge.amount_captured!==0||charge.refunded||charge.amount_refunded!==0||!charge.paid||charge.status!=='succeeded'||charge.payment_method_details?.type!=='card')throw new Error('identity_mismatch');
        const seconds=charge.payment_method_details.card?.capture_before;
        if(!Number.isSafeInteger(seconds)||!seconds||seconds<1||!Number.isFinite(seconds*1000)||intent.amount_capturable!==intent.amount)throw new Error('identity_mismatch');
        const captureBefore=new Date(seconds*1000).toISOString();holdResult={...holdResult,charge_id:charge.id,capture_before:captureBefore,outcome:seconds*1000>Date.parse(h.original_due_at)+h.processing_buffer_seconds*1000&&seconds*1000>Date.now()?'verified':'pending'};
      }else if(intent.status==='canceled'){
        if(intent.amount_capturable!==0||intent.amount_received!==0)throw new Error('identity_mismatch');holdResult={...holdResult,outcome:'verified'};
      }else if(intent.status==='requires_action')holdResult={...holdResult,outcome:'requires_action'};
      else if(intent.status==='requires_payment_method')holdResult={...holdResult,outcome:intent.last_payment_error?'declined':'pending',safe_error_code:intent.last_payment_error?'provider_declined':null};
      else if(intent.status==='requires_confirmation'||intent.status==='processing')holdResult={...holdResult,outcome:'pending'};
      else throw new Error('identity_mismatch');
      // A cancel observation can settle release only for an actually canceled original intent; an attached live hold stays unknown on recovery.
      if(!creating&&intent.status!=='canceled')return {...holdResult,outcome:'unknown',safe_error_code:'provider_unknown'};
      return holdResult;
    }catch{return observationV4(p,'unknown');}
  }
  // A current accepted B0 subscription-purpose return adapter is required before Checkout credentials or I/O.
  if(p.kind==='subscription.create'&&p.plan==='effect')return observationV4(p,'denied');
  if(p.kind==='subscription.create'||p.kind==='subscription.cancel') {
    let billingResult=observationV4(p,'unknown');
    try {
      const {sdk}=createProviderClientV4(p,provision,credential,transport),b=p.billing_configuration!,params=p.parameters;
      if(p.kind==='subscription.create'&&(Date.now()<Date.parse(b.effective_at)||Date.now()>=Date.parse(b.expires_at)))throw new Error('activation_closed');
      // New enrollment verifies the actual recurring SKU. Existing cancellation uses its immutable terms and known customer/subscription, even after commercial expiry or delisting.
      if(p.kind==='subscription.create'){
      const price=await transport.run(()=>sdk.prices.retrieve(b.price_id,undefined,{maxNetworkRetries:0}));
      const product=await transport.run(()=>sdk.products.retrieve(b.product_id,undefined,{maxNetworkRetries:0}));
      if(price.id!==b.price_id||!price.active||price.type!=='recurring'||price.currency!==b.currency||price.unit_amount!==b.unit_amount||price.product!==b.product_id||price.recurring?.interval!==b.interval||price.recurring.interval_count!==1||price.tax_behavior!==b.tax_behavior||price.livemode!==(p.configuration.environment==='live')||product.id!==b.product_id||!product.active||product.deleted||product.livemode!==(p.configuration.environment==='live')||Date.now()>=Date.parse(p.lease_expires_at))throw new Error('identity_mismatch');
      }
      const options={idempotencyKey:p.provider_key,maxNetworkRetries:0};
      // This branch remains unreachable for effects until the real typed return successor replaces the closed guard above.
      const raw=p.kind==='subscription.create'?await transport.run(()=>p.plan==='retrieve'?sdk.checkout.sessions.retrieve(p.object_id!,undefined,{maxNetworkRetries:0}):sdk.checkout.sessions.create({mode:'subscription',customer:String(params.customer),line_items:[{price:b.price_id,quantity:1}],metadata:params.metadata as Record<string,string>,subscription_data:{metadata:params.metadata as Record<string,string>},automatic_tax:{enabled:false}},options)):await transport.run(()=>p.plan==='retrieve'?sdk.subscriptions.retrieve(String(params.subscription_id),undefined,{maxNetworkRetries:0}):sdk.subscriptions.update(String(params.subscription_id),{cancel_at_period_end:true},options));
      if(raw.customer!==params.customer||raw.livemode!==(p.configuration.environment==='live')||!billingObjectId(p.object_kind!,raw.id)||p.object_id&&raw.id!==p.object_id||raw.lastResponse.apiVersion&&raw.lastResponse.apiVersion!==p.configuration.api_version)throw new Error('identity_mismatch');
      billingResult={...billingResult,outcome:'verified',transport_outcome:'received',safe_error_code:null,object_id:raw.id,customer_id:String(params.customer),livemode:raw.livemode,request_id:providerId(raw.lastResponse.requestId)?raw.lastResponse.requestId:null};
      if(p.kind==='subscription.create') {
        const session=raw as import('stripe').Stripe.Checkout.Session;
        if(session.object!=='checkout.session'||session.mode!=='subscription'||session.metadata?.ante_operation!==p.operation_id||session.metadata?.ante_subscription!==p.subject_id||!['open','complete','expired'].includes(String(session.status)))throw new Error('identity_mismatch');
        // Completion is recorded lineage only. It never creates a paid interval or delivers an unaccepted browser URL.
        billingResult={...billingResult,checkout_state:session.status as 'open'|'complete'|'expired',provider_subscription_id:typeof session.subscription==='string'&&billingObjectId('subscription',session.subscription)?session.subscription:null};
      }else {
        const subscription=raw as import('stripe').Stripe.Subscription;
        if(subscription.object!=='subscription'||subscription.id!==params.subscription_id||!subscription.cancel_at_period_end)throw new Error('identity_mismatch');
        billingResult={...billingResult,provider_subscription_id:subscription.id,cancel_at_period_end:true,subscription_state:subscription.status};
      }
      return billingResult;
    }catch{return observationV4(p,'unknown');}
  }
  let result = observationV4(p, "unknown");
  try {
    const { sdk } = createProviderClientV4(p, provision, credential, transport),
      params = p.parameters,
      c = p.configuration;
    const options = { idempotencyKey: p.provider_key, maxNetworkRetries: 0 };
    let raw: unknown;
    if (p.kind === "customer.create") {
      if (!exact(params, ["metadata"])) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        p.plan === "retrieve"
          ? sdk.customers.retrieve(p.object_id!, undefined, {
            maxNetworkRetries: 0,
          })
          : sdk.customers.create({
            metadata: params.metadata as Record<string, string>,
          }, options)
      );
    } else if (p.kind === "setup.create") {
      if (
        !exact(params, [
          "customer",
          "usage",
          "allowed_payment_method_types",
          "payment_method_configuration",
          "metadata",
        ]) || params.usage !== "off_session" ||
        JSON.stringify(params.allowed_payment_method_types) !== '["card"]' ||
        params.payment_method_configuration !== c.method_configuration
      ) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        p.plan === "retrieve"
          ? sdk.setupIntents.retrieve(p.object_id!, undefined, {
            maxNetworkRetries: 0,
          })
          : sdk.setupIntents.create({
            customer: String(params.customer),
            usage: "off_session",
            allowed_payment_method_types: ["card"],
            payment_method_configuration: c.method_configuration,
            metadata: params.metadata as Record<string, string>,
          }, options)
      );
    } else if (p.kind === "setup.retrieve") {
      if (
        !exact(params, ["setup_id", "customer", "payment_method_configuration"])
      ) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        sdk.setupIntents.retrieve(String(params.setup_id), undefined, {
          maxNetworkRetries: 0,
        })
      );
    } else if (p.kind === "customer.default") {
      if (
        !exact(params, ["customer", "invoice_settings"]) ||
        c.default_policy !== "invoice"
      ) throw new Error("identity_mismatch");
      const desired = params.invoice_settings as {
        default_payment_method: string;
      };
      if (
        !exact(desired, ["default_payment_method"]) ||
        !providerId(desired.default_payment_method)
      ) throw new Error("identity_mismatch");
      raw = await transport.run(() =>
        p.plan === "retrieve"
          ? sdk.customers.retrieve(String(params.customer), undefined, {
            maxNetworkRetries: 0,
          })
          : sdk.customers.update(String(params.customer), {
            invoice_settings: desired,
          }, options)
      );
    } else {
      if (
        !exact(params, ["method_id", "customer"]) ||
        c.removal_policy !== "block_dependencies"
      ) throw new Error("identity_mismatch");
      const original = await transport.run(() =>
        sdk.paymentMethods.retrieve(String(params.method_id), undefined, {
          maxNetworkRetries: 0,
        })
      );
      if (
        original.id !== params.method_id || original.type !== "card" ||
        original.livemode !== (c.environment === "live") ||
        original.customer !== params.customer && original.customer !== null
      ) throw new Error("identity_mismatch");
      // Reconciliation never re-detaches an attached target after an uncertain/expired-key write.
      // The same recorded method can only be observed detached; unresolved attachment stays unknown.
      if (p.plan === "retrieve" && original.customer !== null) {
        throw new Error("provider_unknown");
      }
      raw = original.customer === null
        ? original
        : await transport.run(() =>
          sdk.paymentMethods.detach(String(params.method_id), {}, options)
        );
    }
    if (!raw || typeof raw !== "object") throw new Error("identity_mismatch");
    const object = raw as Record<string, unknown>;
    if (
      !providerId(object.id) || object.deleted ||
      object.livemode !== (c.environment === "live")
    ) throw new Error("identity_mismatch");
    if (p.object_id && object.id !== p.object_id) {
      throw new Error("identity_mismatch");
    }
    result = {
      ...result,
      outcome: "verified",
      transport_outcome: "received",
      safe_error_code: null,
      object_id: String(object.id),
      livemode: Boolean(object.livemode),
    };
    // Header absence cannot establish merchant identity: trusted provisioning was checked before I/O.
    const last = object.lastResponse as {
      requestId?: string;
      apiVersion?: string;
    } | undefined;
    if (last?.apiVersion && last.apiVersion !== c.api_version) {
      throw new Error("identity_mismatch");
    }
    if (providerId(last?.requestId)) result.request_id = last!.requestId!;
    if (p.kind === "customer.create") {
      const metadata = object.metadata as Record<string, string>;
      if (
        object.object !== "customer" ||
        metadata?.ante_operation !== p.operation_id ||
        metadata?.ante_customer !== p.customer_id
      ) throw new Error("identity_mismatch");
    } else if (p.kind === "customer.default") {
      const settings = object.invoice_settings as Record<string, unknown>;
      if (
        object.object !== "customer" || object.id !== params.customer ||
        settings?.default_payment_method !==
          (params.invoice_settings as Record<string, unknown>)
            .default_payment_method
      ) throw new Error("identity_mismatch");
      result.customer_id = String(params.customer);
      result.default_method_id = String(settings.default_payment_method);
    } else if (p.kind === "card.detach") {
      if (
        object.object !== "payment_method" || object.id !== params.method_id ||
        object.type !== "card" || object.customer !== null
      ) throw new Error("identity_mismatch");
      result.method_type = "card";
    } else {
      const config = object.payment_method_configuration_details as {
        id?: string;
      } | null;
      if (
        object.object !== "setup_intent" ||
        object.customer !== params.customer || object.usage !== "off_session" ||
        config?.id !== c.method_configuration ||
        JSON.stringify(object.allowed_payment_method_types) !== '["card"]' ||
        JSON.stringify(object.payment_method_types) !== '["card"]'
      ) throw new Error("identity_mismatch");
      if (p.kind === "setup.create") {
        const metadata = object.metadata as Record<string, string>;
        if (
          metadata?.ante_operation !== p.operation_id ||
          metadata?.ante_setup !== p.subject_id
        ) throw new Error("identity_mismatch");
      }
      result.customer_id = String(params.customer);
      result.usage = "off_session";
      result.method_configuration = c.method_configuration;
      switch (object.status) {
        case "succeeded": {
          if (
            p.kind !== "setup.retrieve" || !providerId(object.payment_method)
          ) throw new Error("identity_mismatch");
          const method = await transport.run(() =>
            sdk.paymentMethods.retrieve(
              String(object.payment_method),
              undefined,
              { maxNetworkRetries: 0 },
            )
          );
          if (
            method.id !== object.payment_method || method.type !== "card" ||
            method.customer !== params.customer ||
            method.livemode !== (c.environment === "live") || !method.card ||
            !/^[0-9]{4}$/.test(method.card.last4) ||
            !/^[a-z_]{1,32}$/.test(method.card.brand) ||
            method.card.exp_month < 1 || method.card.exp_month > 12 ||
            method.card.exp_year < 2000 || method.card.exp_year > 2200
          ) throw new Error("identity_mismatch");
          result = {
            ...result,
            setup_state: "succeeded",
            method_id: method.id,
            method_type: "card",
            brand: method.card.brand,
            last4: method.card.last4,
            expiry_month: method.card.exp_month,
            expiry_year: method.card.exp_year,
          };
          break;
        }
        case "requires_action":
          result = {
            ...result,
            outcome: "requires_action",
            setup_state: "requires_action",
          };
          break;
        case "canceled":
          result = { ...result, outcome: "pending", setup_state: "canceled" };
          break;
        case "requires_payment_method":
          if (object.last_setup_error) {
            result = observationV4(p, "declined");
            result.safe_error_code = "provider_declined";
          } else {result = {
              ...result,
              outcome: "pending",
              setup_state: "pending",
            };}
          break;
        case "requires_confirmation":
        case "processing":
          result = { ...result, outcome: "pending", setup_state: "pending" };
          break;
        default:
          throw new Error("identity_mismatch");
      }
    }
    return result;
  } catch {
    return observationV4(p, "unknown");
  }
}
// DB dispatch binds the exact claimed plan/object before credential/client construction.
// Changed reconciliation denies the claim; local recording failure stays unknown.
// The caller owns quiescence separately; logical return cannot authorize a second physical effect.
export async function dispatchProviderV4(
  repository: ProviderRepositoryV4,
  permit: Permit,
  provision: Provisioning,
  credential: () => string,
  transport: GuardedTransport,
) {
  if (!await repository.recordDispatch(permit)) {
    return { status: "denied" as const };
  }
  const result = await executeProviderV4(
    permit,
    provision,
    credential,
    transport,
  );
  try {
    return await repository.recordObservation(permit, result);
  } catch {
    return { status: "unknown" as const };
  }
}

// Only a one-use long-collection-purpose repository ticket may expose the original PaymentIntent secret, after final owner/context consumption. The HTTP purpose adapter is separately approved; this source does not install one.
export async function readLongCollectionContinuationV4(repository:ProviderRepositoryV4,commitmentId:string,revision:number,provision:Provisioning,credential:()=>string,transport:GuardedTransport){
 try{
  const ctx=await repository.collectionContinuation(commitmentId,revision);if(!ctx)return null;
  const p=ctx.permit,{sdk}=createProviderClientV4(p,provision,credential,transport);
  const intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0})));
  if(intent.status!=='requires_action'||intent.amount_received!==0||intent.amount_capturable!==0||!intent.client_secret||!/^[A-Za-z0-9_-]{1,512}$/.test(intent.client_secret)||Date.now()>=Date.parse(ctx.ticket.expires_at)||!await repository.consumeCollectionContinuation(ctx)||Date.now()>=Date.parse(ctx.ticket.expires_at))return null;
  // Secrets exist only in this protected transient return, never ordinary DTOs, journals, errors or logs. A returned action does not provide backing or task finality.
  return {purpose:'task.long_collection.continue' as const,commitment_id:commitmentId,commitment_revision:revision,provider_intent_id:intent.id,client_secret:intent.client_secret,expires_at:ctx.ticket.expires_at,return_route_key:'account_payments' as const};
 }catch{return null;}
}
// The original-intent verifier below is shared with hold/release/continuation. Collection additionally verifies the same expanded Charge, full received amount and absence of refunds.
function verifyCollectionCharge(p:Permit,intent:HoldIntent,captured:boolean):number|null{
 const charge=intent.latest_charge,amount=Number(p.parameters.amount_minor);
 if(!charge||typeof charge==='string'||charge.object!=='charge'||!/^ch_[A-Za-z0-9_]{1,240}$/.test(charge.id)||charge.payment_intent!==intent.id||charge.customer!==p.parameters.customer||charge.payment_method!==p.parameters.method_id||charge.amount!==amount||charge.currency!==p.parameters.currency||charge.livemode!==intent.livemode||charge.refunded||charge.amount_refunded!==0||!charge.paid||charge.status!=='succeeded'||charge.payment_method_details?.type!=='card'||charge.captured!==captured||charge.amount_captured!==(captured?amount:0))throw new Error('identity_mismatch');
 if(captured){if(intent.amount_received!==amount||intent.amount_capturable!==0)throw new Error('identity_mismatch');return null;}
 const seconds=charge.payment_method_details.card?.capture_before;
 if(!Number.isSafeInteger(seconds)||!seconds||seconds<1||intent.amount_received!==0||intent.amount_capturable!==amount)throw new Error('identity_mismatch');return seconds*1000;
}
// The same original-intent verifier serves journal observations and transient owner continuation; no alternate identity interpretation is permitted.
type HoldIntent=import('stripe').Stripe.PaymentIntent & {lastResponse?:{apiVersion?:string;requestId?:string}};
function verifyOriginalHoldIntent(p:Permit,raw:HoldIntent):HoldIntent{
 const params=p.parameters,collection=p.kind==='authorization.capture'||p.kind==='collection.create',h=p.hold_configuration,creating=p.kind==='authorization.create'||p.kind==='collection.create',originalOperation=collection?p.collection_configuration!.original_operation_id:h!.authorization_operation_id;
        if(raw.object!=='payment_intent'||!holdObjectId(raw.id)||p.object_id&&raw.id!==p.object_id||!creating&&raw.id!==params.payment_intent_id||raw.customer!==params.customer||raw.payment_method!==params.method_id||raw.livemode!==(p.configuration.environment==='live')||raw.amount!==Number(params.amount_minor)||raw.currency!==params.currency||raw.capture_method!==(p.kind==='collection.create'?'automatic':'manual')||raw.confirmation_method!=='automatic'||!exact(raw.metadata,['ante_operation','ante_commitment'])||raw.metadata?.ante_commitment!==p.subject_id||raw.metadata?.ante_operation!==originalOperation||raw.lastResponse?.apiVersion&&raw.lastResponse.apiVersion!==p.configuration.api_version)throw new Error('identity_mismatch');
        if(JSON.stringify(raw.allowed_payment_method_types)!=='["card"]'||JSON.stringify(raw.payment_method_types)!=='["card"]'||raw.payment_method_configuration_details?.id!==p.configuration.method_configuration)throw new Error('identity_mismatch');
        return raw;
      
}
// Only a one-use hold-purpose repository ticket may expose the original PaymentIntent secret, after final owner/context consumption. The HTTP purpose adapter is separately approved; this source does not install one.
export async function readShortHoldContinuationV4(repository:ProviderRepositoryV4,commitmentId:string,revision:number,provision:Provisioning,credential:()=>string,transport:GuardedTransport){
 try{
  const ctx=await repository.holdContinuation(commitmentId,revision);if(!ctx)return null;
  const p=ctx.permit,{sdk}=createProviderClientV4(p,provision,credential,transport);
  const intent=verifyOriginalHoldIntent(p,await transport.run(()=>sdk.paymentIntents.retrieve(p.object_id!,{expand:['latest_charge']},{maxNetworkRetries:0})));
  if(intent.status!=='requires_action'||intent.amount_received!==0||intent.amount_capturable!==0||!intent.client_secret||!/^[A-Za-z0-9_-]{1,512}$/.test(intent.client_secret)||Date.now()>=Date.parse(ctx.ticket.expires_at)||!await repository.consumeHoldContinuation(ctx)||Date.now()>=Date.parse(ctx.ticket.expires_at))return null;
  // Secrets exist only in this protected transient return, never ordinary DTOs, journals, errors or logs. A returned action does not provide backing or task finality.
  return {purpose:'task.short_hold.continue' as const,commitment_id:commitmentId,commitment_revision:revision,provider_intent_id:intent.id,client_secret:intent.client_secret,expires_at:ctx.ticket.expires_at,return_route_key:'account_payments' as const};
 }catch{return null;}
}
// Ephemeral owner continuation retrieves only a recorded SetupIntent under a persisted one-use ticket.
// No secret reaches observationV4s/history/logs; local expiry does not invalidate Stripe's secret.
export async function readProviderContinuationV4(
  repository: ProviderRepositoryV4,
  setupId: string,
  revision: number,
  provision: Provisioning,
  credential: () => string,
  transport: GuardedTransport,
) {
  try {
    const ctx = await repository.continuation(setupId, revision);
    if (!ctx) return null;
    const p = ctx.permit, c = p.configuration;
    const { sdk } = createProviderClientV4(p, provision, credential, transport);
    const setup = await transport.run(() =>
      sdk.setupIntents.retrieve(p.object_id!, undefined, {
        maxNetworkRetries: 0,
      })
    );
    if (
      setup.id !== p.object_id || setup.customer !== p.parameters.customer ||
      setup.livemode !== (c.environment === "live") ||
      setup.usage !== "off_session" ||
      setup.payment_method_configuration_details?.id !==
        c.method_configuration ||
      JSON.stringify(setup.allowed_payment_method_types) !== '["card"]' ||
      JSON.stringify(setup.payment_method_types) !== '["card"]' ||
      !["requires_action", "requires_confirmation", "requires_payment_method"]
        .includes(setup.status) ||
      setup.metadata?.ante_operation !== p.operation_id ||
      setup.metadata?.ante_setup !== p.subject_id || !setup.client_secret ||
      !/^[A-Za-z0-9_-]{1,512}$/.test(setup.client_secret) ||
      Date.now() >= Date.parse(ctx.ticket.expires_at) ||
      !await repository.consumeContinuation(ctx)
    ) return null;
    return {
      operation_id: p.operation_id,
      operation_revision: p.operation_revision,
      setup_id: setupId,
      setup_revision: revision,
      client_secret: setup.client_secret,
      expires_at: ctx.ticket.expires_at,
      return_route_key: "account_payments" as const,
    };
  } catch {
    return null;
  }
}
